// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
	"time"
)

// MensagemRadar ...
type MensagemRadar struct {
	XMLName          xml.Name            `xml:"mensagemRadar"`
	Cabecalho        *CabecalhoTransacao `xml:"cabecalho"`
	OperadoraParaANS *OperadoraANS       `xml:"operadoraParaANS"`
	AnsParaOperadora *AnsOperadora       `xml:"ansParaOperadora"`
	Epilogo          *Epilogo            `xml:"epilogo"`
}

// IdentificacaoTransacao ...
type IdentificacaoTransacao struct {
	XMLName               xml.Name  `xml:"identificacaoTransacao"`
	TipoTransacao         string    `xml:"tipoTransacao"`
	SequencialTransacao   string    `xml:"sequencialTransacao"`
	DataRegistroTransacao string    `xml:"dataRegistroTransacao"`
	HoraRegistroTransacao time.Time `xml:"horaRegistroTransacao"`
}

// Origem ...
type Origem struct {
	XMLName     xml.Name `xml:"origem"`
	RegistroANS string   `xml:"registroANS"`
	ANS         string   `xml:"ANS"`
}

// Destino ...
type Destino struct {
	XMLName     xml.Name `xml:"destino"`
	RegistroANS string   `xml:"registroANS"`
	ANS         string   `xml:"ANS"`
}

// CabecalhoTransacao ...
type CabecalhoTransacao struct {
	XMLName                xml.Name                `xml:"cabecalhoTransacao"`
	IdentificacaoTransacao *IdentificacaoTransacao `xml:"identificacaoTransacao"`
	Origem                 *Origem                 `xml:"origem"`
	Destino                *Destino                `xml:"destino"`
}

// OperadoraANS ...
type OperadoraANS struct {
	XMLName      xml.Name       `xml:"operadoraANS"`
	Pergunta1    *Pergunta01    `xml:"pergunta1"`
	Pergunta2    *Pergunta02    `xml:"pergunta2"`
	Pergunta3    *Pergunta03    `xml:"pergunta3"`
	Pergunta4    *Pergunta04    `xml:"pergunta4"`
	Pergunta5    *Pergunta05    `xml:"pergunta5"`
	Pergunta6    *Pergunta06    `xml:"pergunta6"`
	Pergunta7    *Pergunta07    `xml:"pergunta7"`
	Pergunta8a10 *Pergunta08a10 `xml:"pergunta8a10"`
	Pergunta11   *Pergunta11    `xml:"pergunta11"`
}

// AnsOperadora ...
type AnsOperadora struct {
	XMLName        xml.Name  `xml:"ansOperadora"`
	ReciboPesquisa *Ctrecibo `xml:"reciboPesquisa"`
	ErroPesquisa   *Cterro   `xml:"erroPesquisa"`
}

// Epilogo ...
type Epilogo struct {
	XMLName xml.Name `xml:"epilogo"`
	Hash    string   `xml:"hash"`
}

// Ctrecibo ...
type Ctrecibo struct {
	XMLName         xml.Name  `xml:"ct_recibo"`
	RegistroANS     string    `xml:"registroANS"`
	DataRecebimento string    `xml:"dataRecebimento"`
	HoraRecebimento time.Time `xml:"horaRecebimento"`
	Resultado       string    `xml:"resultado"`
}

// Cterro ...
type Cterro struct {
	XMLName     xml.Name  `xml:"ct_erro"`
	RegistroANS string    `xml:"registroANS"`
	DataEnvio   string    `xml:"dataEnvio"`
	HoraEnvio   time.Time `xml:"horaEnvio"`
	TextoErro   string    `xml:"textoErro"`
}
