// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// MensagemRadar ...
type MensagemRadar struct {
	XMLName          xml.Name    `xml:"mensagemRadar"`
	Cabecalho        interface{} `xml:"cabecalho"`
	OperadoraParaANS interface{} `xml:"operadoraParaANS"`
	AnsParaOperadora interface{} `xml:"ansParaOperadora"`
	Epilogo          interface{} `xml:"epilogo"`
}

// IdentificacaoTransacao ...
type IdentificacaoTransacao struct {
	XMLName               xml.Name    `xml:"identificacaoTransacao"`
	TipoTransacao         interface{} `xml:"tipoTransacao"`
	SequencialTransacao   interface{} `xml:"sequencialTransacao"`
	DataRegistroTransacao interface{} `xml:"dataRegistroTransacao"`
	HoraRegistroTransacao interface{} `xml:"horaRegistroTransacao"`
}

// Origem ...
type Origem struct {
	XMLName     xml.Name    `xml:"origem"`
	RegistroANS interface{} `xml:"registroANS"`
	ANS         interface{} `xml:"ANS"`
}

// Destino ...
type Destino struct {
	XMLName     xml.Name    `xml:"destino"`
	RegistroANS interface{} `xml:"registroANS"`
	ANS         interface{} `xml:"ANS"`
}

// CabecalhoTransacao ...
type CabecalhoTransacao struct {
	XMLName                xml.Name    `xml:"cabecalhoTransacao"`
	IdentificacaoTransacao interface{} `xml:"identificacaoTransacao"`
	Origem                 interface{} `xml:"origem"`
	Destino                interface{} `xml:"destino"`
}

// OperadoraANS ...
type OperadoraANS struct {
	XMLName      xml.Name    `xml:"operadoraANS"`
	Pergunta1    interface{} `xml:"pergunta1"`
	Pergunta2    interface{} `xml:"pergunta2"`
	Pergunta3    interface{} `xml:"pergunta3"`
	Pergunta4    interface{} `xml:"pergunta4"`
	Pergunta5    interface{} `xml:"pergunta5"`
	Pergunta6    interface{} `xml:"pergunta6"`
	Pergunta7    interface{} `xml:"pergunta7"`
	Pergunta8a10 interface{} `xml:"pergunta8a10"`
	Pergunta11   interface{} `xml:"pergunta11"`
}

// AnsOperadora ...
type AnsOperadora struct {
	XMLName        xml.Name    `xml:"ansOperadora"`
	ReciboPesquisa interface{} `xml:"reciboPesquisa"`
	ErroPesquisa   interface{} `xml:"erroPesquisa"`
}

// Epilogo ...
type Epilogo struct {
	XMLName xml.Name `xml:"epilogo"`
	Hash    string   `xml:"hash"`
}

// Ctrecibo ...
type Ctrecibo struct {
	XMLName         xml.Name    `xml:"ct_recibo"`
	RegistroANS     interface{} `xml:"registroANS"`
	DataRecebimento interface{} `xml:"dataRecebimento"`
	HoraRecebimento interface{} `xml:"horaRecebimento"`
	Resultado       interface{} `xml:"resultado"`
}

// Cterro ...
type Cterro struct {
	XMLName     xml.Name    `xml:"ct_erro"`
	RegistroANS interface{} `xml:"registroANS"`
	DataEnvio   interface{} `xml:"dataEnvio"`
	HoraEnvio   interface{} `xml:"horaEnvio"`
	TextoErro   interface{} `xml:"textoErro"`
}
