// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// Questao01 ...
type Questao01 struct {
	XMLName       xml.Name `xml:"questao01"`
	GrupoEvento   string   `xml:"grupoEvento"`
	TpValorEvento string   `xml:"tpValorEvento"`
	Valorevento   float64  `xml:"valorevento"`
}

// Pergunta01 ...
type Pergunta01 struct {
	XMLName   xml.Name     `xml:"pergunta01"`
	Questao01 []*Questao01 `xml:"questao01"`
}

// Questao02 ...
type Questao02 struct {
	XMLName        xml.Name `xml:"questao02"`
	TipoIdent      string   `xml:"tipoIdent"`
	CodIdent       string   `xml:"codIdent"`
	CodMunic       string   `xml:"codMunic"`
	TipoGuia       string   `xml:"tipoGuia"`
	QtdGuiasEletro int      `xml:"qtdGuiasEletro"`
	QtdItensEletro int      `xml:"qtdItensEletro"`
	ValorEletro    float64  `xml:"valorEletro"`
	QtdGuiasTotal  int      `xml:"qtdGuiasTotal"`
	QtdItensTotal  int      `xml:"qtdItensTotal"`
	ValorTotal     float64  `xml:"valorTotal"`
	VersaoTiss     string   `xml:"versaoTiss"`
}

// Pergunta02 ...
type Pergunta02 struct {
	XMLName   xml.Name     `xml:"pergunta02"`
	Questao02 []*Questao02 `xml:"questao02"`
}

// Questao03 ...
type Questao03 struct {
	XMLName            xml.Name `xml:"questao03"`
	VerifElegibilidade string   `xml:"verifElegibilidade"`
	GrupoEvento        string   `xml:"grupoEvento"`
	QtdElegibilidade   int      `xml:"qtdElegibilidade"`
}

// Pergunta03 ...
type Pergunta03 struct {
	XMLName   xml.Name     `xml:"pergunta03"`
	Questao03 []*Questao03 `xml:"questao03"`
}

// Questao04 ...
type Questao04 struct {
	XMLName       xml.Name `xml:"questao04"`
	MsgEletronica string   `xml:"msgEletronica"`
	TpCanalMsg    string   `xml:"tpCanalMsg"`
	Elegibilidade string   `xml:"elegibilidade"`
}

// Pergunta04 ...
type Pergunta04 struct {
	XMLName   xml.Name     `xml:"pergunta04"`
	Questao04 []*Questao04 `xml:"questao04"`
}

// Pergunta05 ...
type Pergunta05 struct {
	XMLName              xml.Name `xml:"pergunta05"`
	PossuiCertificado    string   `xml:"possuiCertificado"`
	NomeCertificado      string   `xml:"nomeCertificado"`
	QtdPrestadoresCertif int      `xml:"qtdPrestadoresCertif"`
}

// Questao06 ...
type Questao06 struct {
	XMLName           xml.Name `xml:"questao06"`
	FormAcesso        string   `xml:"formAcesso"`
	ImplElegibilidade string   `xml:"implElegibilidade"`
	QtdElegibilidade  int      `xml:"qtdElegibilidade"`
}

// Pergunta06 ...
type Pergunta06 struct {
	XMLName   xml.Name     `xml:"pergunta06"`
	Questao06 []*Questao06 `xml:"questao06"`
}

// Pergunta07 ...
type Pergunta07 struct {
	XMLName      xml.Name `xml:"pergunta07"`
	RelacaoDocs  string   `xml:"relacaoDocs"`
	DocUtilizado string   `xml:"docUtilizado"`
}

// Pergunta08a10 ...
type Pergunta08a10 struct {
	XMLName                xml.Name `xml:"pergunta08a10"`
	PrincipaisDemandas     string   `xml:"principaisDemandas"`
	PrincipaisDificuldades string   `xml:"principaisDificuldades"`
	SugestoesMelhorias     string   `xml:"sugestoesMelhorias"`
}

// Pergunta11 ...
type Pergunta11 struct {
	XMLName          xml.Name `xml:"pergunta11"`
	NomeResponsavel  string   `xml:"nomeResponsavel"`
	CargoResponsavel string   `xml:"cargoResponsavel"`
	TelResponsavel   string   `xml:"telResponsavel"`
	EmailResponsavel string   `xml:"emailResponsavel"`
}
