// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// Questao01 ...
type Questao01 struct {
	XMLName       xml.Name    `xml:"questao01"`
	GrupoEvento   interface{} `xml:"grupoEvento"`
	TpValorEvento interface{} `xml:"tpValorEvento"`
	Valorevento   interface{} `xml:"valorevento"`
}

// Pergunta01 ...
type Pergunta01 struct {
	XMLName   xml.Name      `xml:"pergunta01"`
	Questao01 []interface{} `xml:"questao01"`
}

// Questao02 ...
type Questao02 struct {
	XMLName        xml.Name    `xml:"questao02"`
	TipoIdent      interface{} `xml:"tipoIdent"`
	CodIdent       interface{} `xml:"codIdent"`
	CodMunic       interface{} `xml:"codMunic"`
	TipoGuia       interface{} `xml:"tipoGuia"`
	QtdGuiasEletro interface{} `xml:"qtdGuiasEletro"`
	QtdItensEletro interface{} `xml:"qtdItensEletro"`
	ValorEletro    interface{} `xml:"valorEletro"`
	QtdGuiasTotal  interface{} `xml:"qtdGuiasTotal"`
	QtdItensTotal  interface{} `xml:"qtdItensTotal"`
	ValorTotal     interface{} `xml:"valorTotal"`
	VersaoTiss     interface{} `xml:"versaoTiss"`
}

// Pergunta02 ...
type Pergunta02 struct {
	XMLName   xml.Name      `xml:"pergunta02"`
	Questao02 []interface{} `xml:"questao02"`
}

// Questao03 ...
type Questao03 struct {
	XMLName            xml.Name    `xml:"questao03"`
	VerifElegibilidade interface{} `xml:"verifElegibilidade"`
	GrupoEvento        interface{} `xml:"grupoEvento"`
	QtdElegibilidade   interface{} `xml:"qtdElegibilidade"`
}

// Pergunta03 ...
type Pergunta03 struct {
	XMLName   xml.Name      `xml:"pergunta03"`
	Questao03 []interface{} `xml:"questao03"`
}

// Questao04 ...
type Questao04 struct {
	XMLName       xml.Name    `xml:"questao04"`
	MsgEletronica interface{} `xml:"msgEletronica"`
	TpCanalMsg    interface{} `xml:"tpCanalMsg"`
	Elegibilidade interface{} `xml:"elegibilidade"`
}

// Pergunta04 ...
type Pergunta04 struct {
	XMLName   xml.Name      `xml:"pergunta04"`
	Questao04 []interface{} `xml:"questao04"`
}

// Pergunta05 ...
type Pergunta05 struct {
	XMLName              xml.Name    `xml:"pergunta05"`
	PossuiCertificado    interface{} `xml:"possuiCertificado"`
	NomeCertificado      interface{} `xml:"nomeCertificado"`
	QtdPrestadoresCertif interface{} `xml:"qtdPrestadoresCertif"`
}

// Questao06 ...
type Questao06 struct {
	XMLName           xml.Name    `xml:"questao06"`
	FormAcesso        interface{} `xml:"formAcesso"`
	ImplElegibilidade interface{} `xml:"implElegibilidade"`
	QtdElegibilidade  interface{} `xml:"qtdElegibilidade"`
}

// Pergunta06 ...
type Pergunta06 struct {
	XMLName   xml.Name      `xml:"pergunta06"`
	Questao06 []interface{} `xml:"questao06"`
}

// Pergunta07 ...
type Pergunta07 struct {
	XMLName               xml.Name    `xml:"pergunta07"`
	PossuiCanalLoginSenha interface{} `xml:"possuiCanalLoginSenha"`
	AcessoDadosCadastrais interface{} `xml:"acessoDadosCadastrais"`
	AcessoRedePrestadores interface{} `xml:"acessoRedePrestadores"`
	AcessoDadosUtilizacao interface{} `xml:"acessoDadosUtilizacao"`
	AcessoOutrosDados     interface{} `xml:"acessoOutrosDados"`
}

// Pergunta08a10 ...
type Pergunta08a10 struct {
	XMLName                xml.Name    `xml:"pergunta08a10"`
	PrincipaisDemandas     interface{} `xml:"principaisDemandas"`
	PrincipaisDificuldades interface{} `xml:"principaisDificuldades"`
	ImplantacaoV3          interface{} `xml:"implantacaoV3"`
}

// Pergunta11 ...
type Pergunta11 struct {
	XMLName          xml.Name    `xml:"pergunta11"`
	NomeResponsavel  interface{} `xml:"nomeResponsavel"`
	CargoResponsavel interface{} `xml:"cargoResponsavel"`
	TelResponsavel   interface{} `xml:"telResponsavel"`
	EmailResponsavel interface{} `xml:"emailResponsavel"`
}
