// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// Sthost ...
type Sthost string

// Stwsurl ...
type Stwsurl string

// Stport ...
type Stport int

// Cthostporta ...
type Cthostporta struct {
	XMLName xml.Name `xml:"ct_hostporta"`
	Host    string   `xml:"host"`
	Port    int      `xml:"port"`
}

// PontoAPonto ...
type PontoAPonto struct {
	XMLName xml.Name     `xml:"pontoAPonto"`
	Socket  *Cthostporta `xml:"socket"`
	Service string       `xml:"service"`
}

// WebServices ...
type WebServices struct {
	XMLName                               xml.Name `xml:"webServices"`
	TissCancelaGuia                       string   `xml:"tissCancelaGuia"`
	TissLoteGuias                         string   `xml:"tissLoteGuias"`
	TissSolicitacaoAnaliseConta           string   `xml:"tissSolicitacaoAnaliseConta"`
	TissSolicitacaoDemonstrativoPagamento string   `xml:"tissSolicitacaoDemonstrativoPagamento"`
	TissSolicitacaoProcedimento           string   `xml:"tissSolicitacaoProcedimento"`
	TissSolicitacaoStatusProtocolo        string   `xml:"tissSolicitacaoStatusProtocolo"`
	TissVerificaElegibilidade             string   `xml:"tissVerificaElegibilidade"`
}

// Nodotissnet ...
type Nodotissnet struct {
	XMLName     xml.Name     `xml:"nodo_tissnet"`
	Operadora   string       `xml:"operadora"`
	PontoAPonto *PontoAPonto `xml:"pontoAPonto"`
	WebServices *WebServices `xml:"webServices"`
}

// DefinicaoTissNet ...
type DefinicaoTissNet struct {
	XMLName xml.Name       `xml:"definicaoTissNet"`
	Nodo    []*Nodotissnet `xml:"nodo"`
}
