// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
	"time"
)

// IdentificacaoTransacao ...
type IdentificacaoTransacao struct {
	XMLName               xml.Name  `xml:"identificacaoTransacao"`
	TipoTransacao         string    `xml:"tipoTransacao"`
	SequencialTransacao   int       `xml:"sequencialTransacao"`
	DataRegistroTransacao string    `xml:"dataRegistroTransacao"`
	HoraRegistroTransacao time.Time `xml:"horaRegistroTransacao"`
}

// FalhaNegocio ...
type FalhaNegocio struct {
	XMLName    xml.Name `xml:"falhaNegocio"`
	Observacao string   `xml:"observacao"`
	*CtmotivoGlosa
}

// Origem ...
type Origem struct {
	XMLName                    xml.Name                            `xml:"origem"`
	CodigoPrestadorNaOperadora *CtidentificacaoPrestadorExecutante `xml:"codigoPrestadorNaOperadora"`
	RegistroANS                string                              `xml:"registroANS"`
	CnpjPagador                string                              `xml:"cnpjPagador"`
}

// Destino ...
type Destino struct {
	XMLName                    xml.Name                            `xml:"destino"`
	CodigoPrestadorNaOperadora *CtidentificacaoPrestadorExecutante `xml:"codigoPrestadorNaOperadora"`
	RegistroANS                string                              `xml:"registroANS"`
	CnpjPagador                string                              `xml:"cnpjPagador"`
}

// CabecalhoTransacao ...
type CabecalhoTransacao struct {
	XMLName                      xml.Name                        `xml:"cabecalhoTransacao"`
	IdentificacaoTransacao       *IdentificacaoTransacao         `xml:"identificacaoTransacao"`
	FalhaNegocio                 *FalhaNegocio                   `xml:"falhaNegocio"`
	Origem                       *Origem                         `xml:"origem"`
	Destino                      *Destino                        `xml:"destino"`
	VersaoPadrao                 string                          `xml:"versaoPadrao"`
	IdentificacaoSoftwareGerador *CtidentificacaoSoftwareGerador `xml:"identificacaoSoftwareGerador"`
}

// DemonstrativosRetorno ...
type DemonstrativosRetorno struct {
	XMLName                   xml.Name                       `xml:"demonstrativosRetorno"`
	DemonstrativoAnaliseConta []*CtdemonstrativoAnaliseConta `xml:"demonstrativoAnaliseConta"`
	DemonstrativoOdontologia  []*CtdemonstrativoOdontologia  `xml:"demonstrativoOdontologia"`
	DemonstrativoPagamento    []*CtdemonstrativoPagamento    `xml:"demonstrativoPagamento"`
	MensagemErro              []string                       `xml:"mensagemErro"`
}

// DiariaProrrogacaoAutorizada ...
type DiariaProrrogacaoAutorizada struct {
	XMLName                  xml.Name       `xml:"diariaProrrogacaoAutorizada"`
	TipoAcomodacaoAutorizada string         `xml:"tipoAcomodacaoAutorizada"`
	QuantidadeAutorizada     float64        `xml:"quantidadeAutorizada"`
	MotivoGlosa              *CtmotivoGlosa `xml:"motivoGlosa"`
	*CtdiariaProrrogacao
}

// AutorizacaoServico ...
type AutorizacaoServico struct {
	XMLName                     xml.Name                     `xml:"autorizacaoServico"`
	DiariaProrrogacaoAutorizada *DiariaProrrogacaoAutorizada `xml:"diariaProrrogacaoAutorizada"`
	*CtautorizacaoProcedimento
}

// AutorizacaoServicoOdonto ...
type AutorizacaoServicoOdonto struct {
	XMLName xml.Name `xml:"autorizacaoServicoOdonto"`
	*CtautorizacaoProcedimentoOdonto
}

// OperadoraParaPrestador ...
type OperadoraParaPrestador struct {
	XMLName                   xml.Name                         `xml:"operadoraParaPrestador"`
	ProtocoloRecebimento      *CtprotocoloRecebimento          `xml:"protocoloRecebimento"`
	ProtocoloRecebimentoAnexo *CtprotocoloRecebimentoAnexo     `xml:"protocoloRecebimentoAnexo"`
	DemonstrativosRetorno     *DemonstrativosRetorno           `xml:"demonstrativosRetorno"`
	SituacaoProtocolo         *CtStatusProtocolo               `xml:"situacaoProtocolo"`
	AutorizacaoServico        []*AutorizacaoServico            `xml:"autorizacaoServico"`
	AutorizacaoServicoOdonto  *AutorizacaoServicoOdonto        `xml:"autorizacaoServicoOdonto"`
	SituacaoAutorizacao       *CtsituacaoAutorizacao           `xml:"situacaoAutorizacao"`
	RespostaElegibilidade     *CtretornoElegibilidade          `xml:"respostaElegibilidade"`
	ReciboCancelaGuia         *CtreciboCancelaGuia             `xml:"reciboCancelaGuia"`
	ReciboComunicacao         *CtreciboComunicacaoBeneficiario `xml:"reciboComunicacao"`
}

// SolicitacaoProcedimento ...
type SolicitacaoProcedimento struct {
	XMLName                    xml.Name                      `xml:"solicitacaoProcedimento"`
	GuiaSolicInternacao        *CtguiaSolicInternacao        `xml:"guiaSolicInternacao"`
	GuiaSolicitacaoSADT        *CtguiaSolicitacaoSPSADT      `xml:"guiaSolicitacaoSADT"`
	GuiaSolicitacaoOdontologia *CtguiaSolicitacaoOdonto      `xml:"guiaSolicitacaoOdontologia"`
	GuiaSolicitacaoProrrogacao *CtguiaSolicitacaoProrrogacao `xml:"guiaSolicitacaoProrrogacao"`
}

// ComunicacaoBeneficiario ...
type ComunicacaoBeneficiario struct {
	XMLName xml.Name `xml:"comunicacaoBeneficiario"`
	*CtcomunicacaoBeneficiario
}

// PrestadorParaOperadora ...
type PrestadorParaOperadora struct {
	XMLName                         xml.Name                             `xml:"prestadorParaOperadora"`
	LoteGuias                       *CtloteGuias                         `xml:"loteGuias"`
	LoteAnexo                       *CtloteAnexo                         `xml:"loteAnexo"`
	SolicitacaoDemonstrativoRetorno *CtsolicitacaoDemonstrativoPagamento `xml:"solicitacaoDemonstrativoRetorno"`
	SolicitacaoStatusProtocolo      *CtsolicitacaoStatusProtocolo        `xml:"solicitacaoStatusProtocolo"`
	SolicitacaoProcedimento         *SolicitacaoProcedimento             `xml:"solicitacaoProcedimento"`
	SolicitaStatusAutorizacao       *CtsolicitaStatusAutorizacao         `xml:"solicitaStatusAutorizacao"`
	VerificaElegibilidade           *CtsolicitaElegibilidade             `xml:"verificaElegibilidade"`
	CancelaGuia                     *CtcancelaGuia                       `xml:"cancelaGuia"`
	ComunicacaoBeneficiario         *ComunicacaoBeneficiario             `xml:"comunicacaoBeneficiario"`
}

// Epilogo ...
type Epilogo struct {
	XMLName xml.Name `xml:"epilogo"`
	Hash    string   `xml:"hash"`
}

// MensagemTISS ...
type MensagemTISS struct {
	XMLName                xml.Name                `xml:"mensagemTISS"`
	Cabecalho              *CabecalhoTransacao     `xml:"cabecalho"`
	OperadoraParaPrestador *OperadoraParaPrestador `xml:"operadoraParaPrestador"`
	PrestadorParaOperadora *PrestadorParaOperadora `xml:"prestadorParaOperadora"`
	Epilogo                *Epilogo                `xml:"epilogo"`
}
