// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
	"time"
)

// OperadoraParaANS ...
type OperadoraParaANS struct {
	XMLName              xml.Name               `xml:"operadoraParaANS"`
	SemMovimentoInclusao string                 `xml:"semMovimentoInclusao"`
	GuiaMonitoramento    []*CtmonitoramentoGuia `xml:"guiaMonitoramento"`
}

// ArquivoRejeitado ...
type ArquivoRejeitado struct {
	XMLName        xml.Name `xml:"arquivoRejeitado"`
	NomeArquivo    string   `xml:"nomeArquivo"`
	CodigoRejeicao string   `xml:"codigoRejeicao"`
}

// ContratadoExecutante ...
type ContratadoExecutante struct {
	XMLName                 xml.Name `xml:"contratadoExecutante"`
	CNES                    string   `xml:"CNES"`
	IdentificadorExecutante string   `xml:"identificadorExecutante"`
	CodigoCNPJCPF           string   `xml:"codigoCNPJ_CPF"`
}

// ErrosGuia ...
type ErrosGuia struct {
	XMLName            xml.Name `xml:"errosGuia"`
	IdentificadorCampo string   `xml:"identificadorCampo"`
	CodigoErro         string   `xml:"codigoErro"`
}

// Procedimento ...
type Procedimento struct {
	GrupoProcedimento  string `xml:"grupoProcedimento"`
	CodigoProcedimento string `xml:"codigoProcedimento"`
}

// IdentProcedimento ...
type IdentProcedimento struct {
	XMLName      xml.Name      `xml:"identProcedimento"`
	CodigoTabela string        `xml:"codigoTabela"`
	Procedimento *Procedimento `xml:"Procedimento"`
}

// DenteRegiao ...
type DenteRegiao struct {
	XMLName   xml.Name `xml:"denteRegiao"`
	CodDente  string   `xml:"codDente"`
	CodRegiao string   `xml:"codRegiao"`
}

// RelacaoErros ...
type RelacaoErros struct {
	XMLName            xml.Name `xml:"relacaoErros"`
	IdentificadorCampo string   `xml:"identificadorCampo"`
	CodigoErro         string   `xml:"codigoErro"`
}

// ErrosItensGuia ...
type ErrosItensGuia struct {
	XMLName           xml.Name           `xml:"errosItensGuia"`
	IdentProcedimento *IdentProcedimento `xml:"identProcedimento"`
	DenteRegiao       *DenteRegiao       `xml:"denteRegiao"`
	DenteFace         string             `xml:"denteFace"`
	RelacaoErros      []*RelacaoErros    `xml:"relacaoErros"`
}

// RegistrosRejeitados ...
type RegistrosRejeitados struct {
	XMLName                xml.Name              `xml:"registrosRejeitados"`
	ContratadoExecutante   *ContratadoExecutante `xml:"contratadoExecutante"`
	NumeroGuiaPrestador    string                `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora    string                `xml:"numeroGuiaOperadora"`
	IdentificadorReembolso string                `xml:"identificadorReembolso"`
	DataProcessamento      string                `xml:"dataProcessamento"`
	ErrosGuia              []*ErrosGuia          `xml:"errosGuia"`
	ErrosItensGuia         []*ErrosItensGuia     `xml:"errosItensGuia"`
}

// ResumoProcessamentoTotais ...
type ResumoProcessamentoTotais struct {
	XMLName            xml.Name `xml:"resumoProcessamentoTotais"`
	RegistrosIncluidos int      `xml:"registrosIncluidos"`
	RegistrosAlterados int      `xml:"registrosAlterados"`
	RegistrosExcluidos int      `xml:"registrosExcluidos"`
	RegistrosComErros  int      `xml:"registrosComErros"`
}

// ResumoProcessamento ...
type ResumoProcessamento struct {
	XMLName                   xml.Name                   `xml:"resumoProcessamento"`
	NomeArquivo               string                     `xml:"nomeArquivo"`
	RegistrosRejeitados       []*RegistrosRejeitados     `xml:"registrosRejeitados"`
	ResumoProcessamentoTotais *ResumoProcessamentoTotais `xml:"resumoProcessamentoTotais"`
	ArquivoProcessadoPelaANS  string                     `xml:"arquivoProcessadoPelaANS"`
}

// AnsParaOperadora ...
type AnsParaOperadora struct {
	XMLName             xml.Name             `xml:"ansParaOperadora"`
	ArquivoRejeitado    *ArquivoRejeitado    `xml:"arquivoRejeitado"`
	ResumoProcessamento *ResumoProcessamento `xml:"resumoProcessamento"`
}

// Mensagem ...
type Mensagem struct {
	OperadoraParaANS *OperadoraParaANS `xml:"operadoraParaANS"`
	AnsParaOperadora *AnsParaOperadora `xml:"ansParaOperadora"`
}

// MensagemEnvioANS ...
type MensagemEnvioANS struct {
	XMLName   xml.Name            `xml:"mensagemEnvioANS"`
	Cabecalho *CabecalhoTransacao `xml:"cabecalho"`
	Mensagem  *Mensagem           `xml:"Mensagem"`
	Epilogo   *Epilogo            `xml:"epilogo"`
}

// DadosContratadoExecutante ...
type DadosContratadoExecutante struct {
	XMLName                 xml.Name `xml:"dadosContratadoExecutante"`
	CNES                    string   `xml:"CNES"`
	IdentificadorExecutante string   `xml:"identificadorExecutante"`
	CodigoCNPJCPF           string   `xml:"codigoCNPJ_CPF"`
	MunicipioExecutante     string   `xml:"municipioExecutante"`
}

// DadosSemCartao ...
type DadosSemCartao struct {
	XMLName             xml.Name `xml:"dadosSemCartao"`
	Sexo                string   `xml:"sexo"`
	DataNascimento      string   `xml:"dataNascimento"`
	MunicipioResidencia string   `xml:"municipioResidencia"`
}

// IdentBeneficiario ...
type IdentBeneficiario struct {
	XMLName                   xml.Name        `xml:"identBeneficiario"`
	NumeroCartaoNacionalSaude string          `xml:"numeroCartaoNacionalSaude"`
	DadosSemCartao            *DadosSemCartao `xml:"dadosSemCartao"`
}

// DadosBeneficiario ...
type DadosBeneficiario struct {
	XMLName             xml.Name           `xml:"dadosBeneficiario"`
	IdentBeneficiario   *IdentBeneficiario `xml:"identBeneficiario"`
	NumeroRegistroPlano string             `xml:"numeroRegistroPlano"`
}

// DiagnosticosCID10 ...
type DiagnosticosCID10 struct {
	XMLName       xml.Name `xml:"diagnosticosCID10"`
	DiagnoticoCID []string `xml:"diagnoticoCID"`
}

// ValoresGuia ...
type ValoresGuia struct {
	XMLName                     xml.Name `xml:"valoresGuia"`
	ValorTotalInformado         float64  `xml:"valorTotalInformado"`
	ValorProcessado             float64  `xml:"valorProcessado"`
	ValorTotalPagoProcedimentos float64  `xml:"valorTotalPagoProcedimentos"`
	ValorTotalDiarias           float64  `xml:"valorTotalDiarias"`
	ValorTotalTaxas             float64  `xml:"valorTotalTaxas"`
	ValorTotalMateriais         float64  `xml:"valorTotalMateriais"`
	ValorTotalOPME              float64  `xml:"valorTotalOPME"`
	ValorTotalMedicamentos      float64  `xml:"valorTotalMedicamentos"`
	ValorGlosaGuia              float64  `xml:"valorGlosaGuia"`
	ValorPagoGuia               float64  `xml:"valorPagoGuia"`
	ValorPagoFornecedores       float64  `xml:"valorPagoFornecedores"`
	ValorTotalTabelaPropria     float64  `xml:"valorTotalTabelaPropria"`
}

// DetalhePacote ...
type DetalhePacote struct {
	XMLName            xml.Name `xml:"detalhePacote"`
	CodigoTabela       string   `xml:"codigoTabela"`
	CodigoProcedimento string   `xml:"codigoProcedimento"`
	Quantidade         float64  `xml:"quantidade"`
}

// Procedimentos ...
type Procedimentos struct {
	XMLName             xml.Name           `xml:"procedimentos"`
	IdentProcedimento   *IdentProcedimento `xml:"identProcedimento"`
	DenteRegiao         *DenteRegiao       `xml:"denteRegiao"`
	DenteFace           string             `xml:"denteFace"`
	QuantidadeInformada float64            `xml:"quantidadeInformada"`
	ValorInformado      float64            `xml:"valorInformado"`
	QuantidadePaga      float64            `xml:"quantidadePaga"`
	ValorPagoProc       float64            `xml:"valorPagoProc"`
	ValorPagoFornecedor float64            `xml:"valorPagoFornecedor"`
	CNPJFornecedor      string             `xml:"CNPJFornecedor"`
	DetalhePacote       []*DetalhePacote   `xml:"detalhePacote"`
}

// CtmonitoramentoGuia ...
type CtmonitoramentoGuia struct {
	XMLName                   xml.Name                   `xml:"ct_monitoramentoGuia"`
	TipoRegistro              string                     `xml:"tipoRegistro"`
	VersaoTISSPrestador       string                     `xml:"versaoTISSPrestador"`
	IndicadorEnvioPapel       string                     `xml:"indicadorEnvioPapel"`
	DadosContratadoExecutante *DadosContratadoExecutante `xml:"dadosContratadoExecutante"`
	DadosBeneficiario         *DadosBeneficiario         `xml:"dadosBeneficiario"`
	TipoEventoAtencao         string                     `xml:"tipoEventoAtencao"`
	OrigemEventoAtencao       string                     `xml:"origemEventoAtencao"`
	NumeroGuiaprestador       string                     `xml:"numeroGuia_prestador"`
	NumeroGuiaoperadora       string                     `xml:"numeroGuia_operadora"`
	IdentificacaoReembolso    string                     `xml:"identificacaoReembolso"`
	GuiaSolicitacaoInternacao string                     `xml:"guiaSolicitacaoInternacao"`
	DataSolicitacao           string                     `xml:"dataSolicitacao"`
	DataAutorizacao           string                     `xml:"dataAutorizacao"`
	DataRealizacao            string                     `xml:"dataRealizacao"`
	DataInicialFaturamento    string                     `xml:"dataInicialFaturamento"`
	DataFimPeriodo            string                     `xml:"dataFimPeriodo"`
	DataProtocoloCobranca     string                     `xml:"dataProtocoloCobranca"`
	DataPagamento             string                     `xml:"dataPagamento"`
	DataProcessamentoGuia     string                     `xml:"dataProcessamentoGuia"`
	TipoConsulta              string                     `xml:"tipoConsulta"`
	CboExecutante             string                     `xml:"cboExecutante"`
	IndicacaoRecemNato        string                     `xml:"indicacaoRecemNato"`
	IndicacaoAcidente         string                     `xml:"indicacaoAcidente"`
	CaraterAtendimento        string                     `xml:"caraterAtendimento"`
	TipoInternacao            string                     `xml:"tipoInternacao"`
	RegimeInternacao          string                     `xml:"regimeInternacao"`
	DiagnosticosCID10         *DiagnosticosCID10         `xml:"diagnosticosCID10"`
	TipoAtendimento           string                     `xml:"tipoAtendimento"`
	TipoFaturamento           string                     `xml:"tipoFaturamento"`
	DiariasAcompanhante       int                        `xml:"diariasAcompanhante"`
	DiariasUTI                int                        `xml:"diariasUTI"`
	MotivoSaida               string                     `xml:"motivoSaida"`
	ValoresGuia               *ValoresGuia               `xml:"valoresGuia"`
	DeclaracaoNascido         []string                   `xml:"declaracaoNascido"`
	DeclaracaoObito           []string                   `xml:"declaracaoObito"`
	Procedimentos             []*Procedimentos           `xml:"procedimentos"`
}

// Epilogo ...
type Epilogo struct {
	XMLName xml.Name `xml:"epilogo"`
	Hash    string   `xml:"hash"`
}

// IdentificacaoTransacao ...
type IdentificacaoTransacao struct {
	XMLName               xml.Name  `xml:"identificacaoTransacao"`
	TipoTransacao         string    `xml:"tipoTransacao"`
	NumeroLote            string    `xml:"numeroLote"`
	CompetenciaLote       string    `xml:"competenciaLote"`
	DataRegistroTransacao string    `xml:"dataRegistroTransacao"`
	HoraRegistroTransacao time.Time `xml:"horaRegistroTransacao"`
}

// CabecalhoTransacao ...
type CabecalhoTransacao struct {
	XMLName                xml.Name                `xml:"cabecalhoTransacao"`
	IdentificacaoTransacao *IdentificacaoTransacao `xml:"identificacaoTransacao"`
	RegistroANS            string                  `xml:"registroANS"`
	VersaoPadrao           string                  `xml:"versaoPadrao"`
}
