// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// SolicitacaoProcedimento ...
type SolicitacaoProcedimento struct {
	XMLName                    xml.Name                      `xml:"solicitacaoProcedimento"`
	GuiaSolicInternacao        *CtguiaSolicInternacao        `xml:"guiaSolicInternacao"`
	GuiaSolicitacaoSADT        *CtguiaSolicitacaoSPSADT      `xml:"guiaSolicitacaoSADT"`
	GuiaSolicitacaoOdontologia *CtguiaSolicitacaoOdonto      `xml:"guiaSolicitacaoOdontologia"`
	GuiaSolicitacaoProrrogacao *CtguiaSolicitacaoProrrogacao `xml:"guiaSolicitacaoProrrogacao"`
}

// WssolicitacaoProcedimento ...
type WssolicitacaoProcedimento struct {
	XMLName                 xml.Name                   `xml:"ws_solicitacaoProcedimento"`
	Cabecalho               *CabecalhoTransacao        `xml:"cabecalho"`
	SolicitacaoProcedimento *WssolicitacaoProcedimento `xml:"solicitacaoProcedimento"`
	Hash                    string                     `xml:"hash"`
}

// TotalOdonto ...
type TotalOdonto struct {
	XMLName                     xml.Name      `xml:"totalOdonto"`
	Totalvalor                  *Stquantidade `xml:"totalvalor"`
	TotalFranquiaCoparticipacao *Stquantidade `xml:"totalFranquiaCoparticipacao"`
	TotalquantidadeUS           *Stquantidade `xml:"totalquantidadeUS"`
}

// CtdiariaProrrogacaoAutorizada ...
type CtdiariaProrrogacaoAutorizada struct {
	XMLName                  xml.Name          `xml:"ct_diariaProrrogacaoAutorizada"`
	TipoAcomodacaoAutorizada *SttipoAcomodacao `xml:"tipoAcomodacaoAutorizada"`
	QuantidadeAutorizada     *Stquantidade     `xml:"quantidadeAutorizada"`
	MotivoGlosa              *CtmotivoGlosa    `xml:"motivoGlosa"`
	*CtdiariaProrrogacao
}

// AutorizacaoServico ...
type AutorizacaoServico struct {
	XMLName                       xml.Name                       `xml:"autorizacaoServico"`
	TotalOdonto                   *TotalOdonto                   `xml:"totalOdonto"`
	CtdiariaProrrogacaoAutorizada *CtdiariaProrrogacaoAutorizada `xml:"ct_diariaProrrogacaoAutorizada"`
	*CtautorizacaoProcedimento
}

// WsautorizacaoProcedimento ...
type WsautorizacaoProcedimento struct {
	XMLName            xml.Name              `xml:"ws_autorizacaoProcedimento"`
	Cabecalho          *CabecalhoTransacao   `xml:"cabecalho"`
	AutorizacaoServico []*AutorizacaoServico `xml:"autorizacaoServico"`
	Hash               string                `xml:"hash"`
}

// AutorizacaoProcedimento ...
type AutorizacaoProcedimento *WsautorizacaoProcedimento

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// VersaoInvalida ...
type VersaoInvalida string

// HashInvalido ...
type HashInvalido string
