// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// WssolicitacaoStatusProtocolo ...
type WssolicitacaoStatusProtocolo struct {
	XMLName                    xml.Name                      `xml:"ws_solicitacaoStatusProtocolo"`
	Cabecalho                  *CabecalhoTransacao           `xml:"cabecalho"`
	SolicitacaoStatusProtocolo *CtsolicitacaoStatusProtocolo `xml:"solicitacaoStatusProtocolo"`
	Hash                       string                        `xml:"hash"`
}

// WssituacaoProtocolo ...
type WssituacaoProtocolo struct {
	XMLName           xml.Name            `xml:"ws_situacaoProtocolo"`
	Cabecalho         *CabecalhoTransacao `xml:"cabecalho"`
	SituacaoProtocolo *CtStatusProtocolo  `xml:"situacaoProtocolo"`
	Hash              string              `xml:"hash"`
}

// SolicitacaoStatusProtocolo ...
type SolicitacaoStatusProtocolo *WssolicitacaoStatusProtocolo

// SituacaoProtocolo ...
type SituacaoProtocolo *WssituacaoProtocolo

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// VersaoInvalida ...
type VersaoInvalida string

// HashInvalido ...
type HashInvalido string

// ProtocoloInexistente ...
type ProtocoloInexistente string
