// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
	"time"
)

// CtanexoCabecalho ...
type CtanexoCabecalho struct {
	XMLName                xml.Name `xml:"ct_anexoCabecalho"`
	RegistroANS            string   `xml:"registroANS"`
	NumeroGuiaAnexo        string   `xml:"numeroGuiaAnexo"`
	NumeroGuiaReferenciada string   `xml:"numeroGuiaReferenciada"`
	NumeroGuiaOperadora    string   `xml:"numeroGuiaOperadora"`
	DataSolicitacao        string   `xml:"dataSolicitacao"`
	Senha                  string   `xml:"senha"`
	DataAutorizacao        string   `xml:"dataAutorizacao"`
}

// AnexosClinicos ...
type AnexosClinicos struct {
	XMLName              xml.Name                   `xml:"anexosClinicos"`
	AnexoOPME            *CtmautorizacaoOPME        `xml:"anexoOPME"`
	AnexoQuimio          *CtmautorizacaoQuimio      `xml:"anexoQuimio"`
	AnexoRadio           *CtmautorizacaoRadio       `xml:"anexoRadio"`
	AnexoSituacaoInicial []*CtoanexoSituacaoInicial `xml:"anexoSituacaoInicial"`
}

// CtanexoRecebimento is estrutura de recibo do recebimento de um lote de anexos dos prestadores
type CtanexoRecebimento struct {
	XMLName                xml.Name           `xml:"ct_anexoRecebimento"`
	NrProtocoloRecebimento string             `xml:"nrProtocoloRecebimento"`
	DataEnvioAnexo         string             `xml:"dataEnvioAnexo"`
	NumeroLote             string             `xml:"numeroLote"`
	RegistroANS            string             `xml:"registroANS"`
	DadosPrestador         *CtcontratadoDados `xml:"dadosPrestador"`
	QtAnexosClinicos       int                `xml:"qtAnexosClinicos"`
	AnexosClinicos         *AnexosClinicos    `xml:"anexosClinicos"`
	Observacao             string             `xml:"observacao"`
}

// CtautorizacaoDados ...
type CtautorizacaoDados struct {
	XMLName             xml.Name `xml:"ct_autorizacaoDados"`
	NumeroGuiaPrestador string   `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora string   `xml:"numeroGuiaOperadora"`
	DataAutorizacao     string   `xml:"dataAutorizacao"`
	Senha               string   `xml:"senha"`
	DataValidadeSenha   string   `xml:"dataValidadeSenha"`
}

// CtautorizacaoSADT ...
type CtautorizacaoSADT struct {
	XMLName             xml.Name `xml:"ct_autorizacaoSADT"`
	NumeroGuiaOperadora string   `xml:"numeroGuiaOperadora"`
	DataAutorizacao     string   `xml:"dataAutorizacao"`
	Senha               string   `xml:"senha"`
	DataValidadeSenha   string   `xml:"dataValidadeSenha"`
}

// CtautorizacaoInternacao ...
type CtautorizacaoInternacao struct {
	XMLName             xml.Name `xml:"ct_autorizacaoInternacao"`
	NumeroGuiaOperadora string   `xml:"numeroGuiaOperadora"`
	DataAutorizacao     string   `xml:"dataAutorizacao"`
	Senha               string   `xml:"senha"`
	DataValidadeSenha   string   `xml:"dataValidadeSenha"`
}

// CtautorizacaoSolicitaStatus ...
type CtautorizacaoSolicitaStatus struct {
	XMLName                  xml.Name             `xml:"ct_autorizacaoSolicitaStatus"`
	IdentificacaoSolicitacao *CtguiaCabecalho     `xml:"identificacaoSolicitacao"`
	DadosBeneficiario        *CtbeneficiarioDados `xml:"dadosBeneficiario"`
	DadosContratado          *CtcontratadoDados   `xml:"dadosContratado"`
}

// CtbeneficiarioDados ...
type CtbeneficiarioDados struct {
	XMLName                   xml.Name `xml:"ct_beneficiarioDados"`
	NumeroCarteira            string   `xml:"numeroCarteira"`
	AtendimentoRN             string   `xml:"atendimentoRN"`
	NomeBeneficiario          string   `xml:"nomeBeneficiario"`
	NumeroCNS                 string   `xml:"numeroCNS"`
	IdentificadorBeneficiario string   `xml:"identificadorBeneficiario"`
}

// RelacaoGlosa ...
type RelacaoGlosa struct {
	XMLName    xml.Name `xml:"relacaoGlosa"`
	ValorGlosa float64  `xml:"valorGlosa"`
	TipoGlosa  string   `xml:"tipoGlosa"`
}

// DetalhesGuia ...
type DetalhesGuia struct {
	XMLName          xml.Name             `xml:"detalhesGuia"`
	DataRealizacao   string               `xml:"dataRealizacao"`
	Procedimento     *CtprocedimentoDados `xml:"procedimento"`
	GrauParticipacao string               `xml:"grauParticipacao"`
	ValorInformado   float64              `xml:"valorInformado"`
	QtdExecutada     float64              `xml:"qtdExecutada"`
	ValorProcessado  float64              `xml:"valorProcessado"`
	ValorLiberado    float64              `xml:"valorLiberado"`
	RelacaoGlosa     []*RelacaoGlosa      `xml:"relacaoGlosa"`
}

// RelacaoGuias ...
type RelacaoGuias struct {
	XMLName             xml.Name         `xml:"relacaoGuias"`
	NumeroGuiaPrestador string           `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora string           `xml:"numeroGuiaOperadora"`
	Senha               string           `xml:"senha"`
	NomeBeneficiario    string           `xml:"nomeBeneficiario"`
	NumeroCarteira      string           `xml:"numeroCarteira"`
	DataInicioFat       string           `xml:"dataInicioFat"`
	HoraInicioFat       time.Time        `xml:"horaInicioFat"`
	DataFimFat          string           `xml:"dataFimFat"`
	HoraFimFat          time.Time        `xml:"horaFimFat"`
	MotivoGlosaGuia     []*CtmotivoGlosa `xml:"motivoGlosaGuia"`
	SituacaoGuia        string           `xml:"situacaoGuia"`
	DetalhesGuia        []*DetalhesGuia  `xml:"detalhesGuia"`
	ValorInformadoGuia  float64          `xml:"valorInformadoGuia"`
	ValorProcessadoGuia float64          `xml:"valorProcessadoGuia"`
	ValorLiberadoGuia   float64          `xml:"valorLiberadoGuia"`
	ValorGlosaGuia      float64          `xml:"valorGlosaGuia"`
}

// CtcontaMedicaResumo is utilizado no demonstrativo de análise de conta
type CtcontaMedicaResumo struct {
	XMLName                  xml.Name        `xml:"ct_contaMedicaResumo"`
	NumeroLotePrestador      string          `xml:"numeroLotePrestador"`
	NumeroProtocolo          string          `xml:"numeroProtocolo"`
	DataProtocolo            string          `xml:"dataProtocolo"`
	GlosaProtocolo           *CtmotivoGlosa  `xml:"GlosaProtocolo"`
	SituacaoProtocolo        string          `xml:"situacaoProtocolo"`
	RelacaoGuias             []*RelacaoGuias `xml:"relacaoGuias"`
	ValorInformadoProtocolo  float64         `xml:"valorInformadoProtocolo"`
	ValorProcessadoProtocolo float64         `xml:"valorProcessadoProtocolo"`
	ValorLiberadoProtocolo   float64         `xml:"valorLiberadoProtocolo"`
	ValorGlosaProtocolo      float64         `xml:"valorGlosaProtocolo"`
}

// CtcontratadoDados ...
type CtcontratadoDados struct {
	XMLName                    xml.Name `xml:"ct_contratadoDados"`
	CodigoPrestadorNaOperadora string   `xml:"codigoPrestadorNaOperadora"`
	CpfContratado              string   `xml:"cpfContratado"`
	CnpjContratado             string   `xml:"cnpjContratado"`
	NomeContratado             string   `xml:"nomeContratado"`
}

// CtcontratadoProfissionalDados ...
type CtcontratadoProfissionalDados struct {
	XMLName                    xml.Name `xml:"ct_contratadoProfissionalDados"`
	NomeProfissional           string   `xml:"nomeProfissional"`
	ConselhoProfissional       string   `xml:"conselhoProfissional"`
	NumeroConselhoProfissional string   `xml:"numeroConselhoProfissional"`
	UF                         string   `xml:"UF"`
	CBOS                       string   `xml:"CBOS"`
}

// CtcreditoOdonto ...
type CtcreditoOdonto struct {
	XMLName      xml.Name `xml:"ct_creditoOdonto"`
	ValorCredito float64  `xml:"valorCredito"`
	Descricao    string   `xml:"descricao"`
}

// CtdadosResumoDemonstrativo ...
type CtdadosResumoDemonstrativo struct {
	XMLName         xml.Name `xml:"ct_dadosResumoDemonstrativo"`
	DataProtocolo   string   `xml:"dataProtocolo"`
	NumeroProtocolo string   `xml:"numeroProtocolo"`
	NumeroLote      string   `xml:"numeroLote"`
	ValorInformado  float64  `xml:"valorInformado"`
	ValorProcessado float64  `xml:"valorProcessado"`
	ValorLiberado   float64  `xml:"valorLiberado"`
	ValorGlosa      float64  `xml:"valorGlosa"`
}

// CtdadosComplementaresBeneficiario ...
type CtdadosComplementaresBeneficiario struct {
	XMLName            xml.Name `xml:"ct_dadosComplementaresBeneficiario"`
	Peso               float64  `xml:"peso"`
	Altura             float64  `xml:"altura"`
	SuperficieCorporal float64  `xml:"superficieCorporal"`
	Idade              int      `xml:"idade"`
	Sexo               string   `xml:"sexo"`
}

// CtdadosComplementaresBeneficiarioRadio ...
type CtdadosComplementaresBeneficiarioRadio struct {
	XMLName xml.Name `xml:"ct_dadosComplementaresBeneficiarioRadio"`
	Idade   int      `xml:"idade"`
	Sexo    string   `xml:"sexo"`
}

// CtdemonstrativoCabecalho ...
type CtdemonstrativoCabecalho struct {
	XMLName             xml.Name `xml:"ct_demonstrativoCabecalho"`
	RegistroANS         string   `xml:"registroANS"`
	NumeroDemonstrativo string   `xml:"numeroDemonstrativo"`
	NomeOperadora       string   `xml:"nomeOperadora"`
	NumeroCNPJ          string   `xml:"numeroCNPJ"`
	DataEmissao         string   `xml:"dataEmissao"`
}

// SituacaoDemonstrativoRetorno ...
type SituacaoDemonstrativoRetorno struct {
	XMLName                           xml.Name           `xml:"situacaoDemonstrativoRetorno"`
	IdentificacaoOperadora            string             `xml:"identificacaoOperadora"`
	DadosPrestador                    *CtcontratadoDados `xml:"dadosPrestador"`
	NumeroProtocolo                   string             `xml:"numeroProtocolo"`
	ProtocoloSolicitacaoDemonstrativo string             `xml:"protocoloSolicitacaoDemonstrativo"`
	TipoDemonstrativo                 string             `xml:"tipoDemonstrativo"`
	DataSituacaoDemonstrativo         string             `xml:"dataSituacaoDemonstrativo"`
	SituacaoDemonstrativo             string             `xml:"situacaoDemonstrativo"`
}

// CtdemonstrativoRetorno ...
type CtdemonstrativoRetorno struct {
	XMLName                      xml.Name                        `xml:"ct_demonstrativoRetorno"`
	MensagemErro                 *CtmotivoGlosa                  `xml:"mensagemErro"`
	DemonstrativoAnaliseConta    []*CtmdemonstrativoAnaliseConta `xml:"demonstrativoAnaliseConta"`
	DemonstrativoPagamento       *CtmdemonstrativoPagamento      `xml:"demonstrativoPagamento"`
	DemonstrativoPagamentoOdonto *CtodemonstrativoOdontologia    `xml:"demonstrativoPagamentoOdonto"`
	SituacaoDemonstrativoRetorno *SituacaoDemonstrativoRetorno   `xml:"situacaoDemonstrativoRetorno"`
}

// Periodo ...
type Periodo struct {
	XMLName       xml.Name `xml:"periodo"`
	DataPagamento string   `xml:"dataPagamento"`
	Competencia   string   `xml:"competencia"`
}

// DemonstrativoPagamento ...
type DemonstrativoPagamento struct {
	XMLName           xml.Name           `xml:"demonstrativoPagamento"`
	DadosPrestador    *CtcontratadoDados `xml:"dadosPrestador"`
	DataSolicitacao   string             `xml:"dataSolicitacao"`
	TipoDemonstrativo string             `xml:"tipoDemonstrativo"`
	Periodo           *Periodo           `xml:"periodo"`
}

// Protocolos ...
type Protocolos struct {
	XMLName         xml.Name `xml:"protocolos"`
	NumeroProtocolo []string `xml:"numeroProtocolo"`
}

// DemonstrativoAnalise ...
type DemonstrativoAnalise struct {
	XMLName         xml.Name           `xml:"demonstrativoAnalise"`
	DadosPrestador  *CtcontratadoDados `xml:"dadosPrestador"`
	DataSolicitacao string             `xml:"dataSolicitacao"`
	Protocolos      *Protocolos        `xml:"protocolos"`
}

// CtdemonstrativoSolicitacao is estrutura para solicitação de demonstrativo de pagamento
type CtdemonstrativoSolicitacao struct {
	XMLName                xml.Name                `xml:"ct_demonstrativoSolicitacao"`
	DemonstrativoPagamento *DemonstrativoPagamento `xml:"demonstrativoPagamento"`
	DemonstrativoAnalise   *DemonstrativoAnalise   `xml:"demonstrativoAnalise"`
}

// Ctdiagnostico ...
type Ctdiagnostico struct {
	XMLName              xml.Name `xml:"ct_diagnostico"`
	TabelaDiagnostico    string   `xml:"tabelaDiagnostico"`
	CodigoDiagnostico    string   `xml:"codigoDiagnostico"`
	DescricaoDiagnostico string   `xml:"descricaoDiagnostico"`
}

// CtdiagnosticoOncologico ...
type CtdiagnosticoOncologico struct {
	XMLName                  xml.Name `xml:"ct_diagnosticoOncologico"`
	DataDiagnostico          string   `xml:"dataDiagnostico"`
	DiagnosticoCID           []string `xml:"diagnosticoCID"`
	Estadiamento             string   `xml:"estadiamento"`
	Finalidade               string   `xml:"finalidade"`
	Ecog                     string   `xml:"ecog"`
	DiagnosticoHispatologico string   `xml:"diagnosticoHispatologico"`
	InfoRelevantes           string   `xml:"infoRelevantes"`
}

// Ctdescontos ...
type Ctdescontos struct {
	XMLName           xml.Name `xml:"ct_descontos"`
	Indicador         string   `xml:"indicador"`
	TipoDebitoCredito string   `xml:"tipoDebitoCredito"`
	DescricaoDbCr     string   `xml:"descricaoDbCr"`
	ValorDbCr         float64  `xml:"valorDbCr"`
}

// CtdrogasSolicitadas ...
type CtdrogasSolicitadas struct {
	XMLName          xml.Name             `xml:"ct_drogasSolicitadas"`
	DataProvavel     string               `xml:"dataProvavel"`
	Identificacao    *CtprocedimentoDados `xml:"identificacao"`
	QtDoses          float64              `xml:"qtDoses"`
	UnidadeMedida    string               `xml:"unidadeMedida"`
	ViaAdministracao string               `xml:"viaAdministracao"`
	Frequencia       int                  `xml:"frequencia"`
}

// MotivosNegativa ...
type MotivosNegativa struct {
	XMLName        xml.Name         `xml:"motivosNegativa"`
	MotivoNegativa []*CtmotivoGlosa `xml:"motivoNegativa"`
}

// CtelegibilidadeRecibo ...
type CtelegibilidadeRecibo struct {
	XMLName                   xml.Name         `xml:"ct_elegibilidadeRecibo"`
	RegistroANS               string           `xml:"registroANS"`
	NumeroCarteira            string           `xml:"numeroCarteira"`
	ValidadeCarteira          string           `xml:"validadeCarteira"`
	NomeBeneficiario          string           `xml:"nomeBeneficiario"`
	NumeroCNS                 string           `xml:"numeroCNS"`
	IdentificadorBeneficiario string           `xml:"identificadorBeneficiario"`
	RespostaSolicitacao       string           `xml:"respostaSolicitacao"`
	MotivosNegativa           *MotivosNegativa `xml:"motivosNegativa"`
}

// DadosContratado ...
type DadosContratado struct {
	XMLName         xml.Name `xml:"dadosContratado"`
	CodigoPrestador string   `xml:"codigoPrestador"`
	NomePrestador   string   `xml:"nomePrestador"`
}

// RecursoProtocolo ...
type RecursoProtocolo struct {
	XMLName                        xml.Name `xml:"recursoProtocolo"`
	CodigoGlosaProtocolo           string   `xml:"codigoGlosaProtocolo"`
	JustificativaProtocolo         string   `xml:"justificativaProtocolo"`
	RecursoAcatado                 string   `xml:"recursoAcatado"`
	JustificativaOPSnaoAcatadoProt string   `xml:"justificativaOPSnaoAcatadoProt"`
}

// RecursoGuia ...
type RecursoGuia struct {
	XMLName           xml.Name                   `xml:"recursoGuia"`
	RespostaGuia      *CtrespostaGlosaGuiaMedica `xml:"respostaGuia"`
	RespostaGuiaItens *CtrespostaGlosaItemMedico `xml:"respostaGuiaItens"`
}

// OpcaoRecurso ...
type OpcaoRecurso struct {
	XMLName          xml.Name          `xml:"opcaoRecurso"`
	RecursoProtocolo *RecursoProtocolo `xml:"recursoProtocolo"`
	RecursoGuia      []*RecursoGuia    `xml:"recursoGuia"`
}

// CtglosaRecibo is recibo de recurso de glosa
type CtglosaRecibo struct {
	XMLName                     xml.Name         `xml:"ct_glosaRecibo"`
	RegistroANS                 string           `xml:"registroANS"`
	NumeroGuiaRecGlosaPrestador string           `xml:"numeroGuiaRecGlosaPrestador"`
	NumeroGuiaRecGlosaOperadora string           `xml:"numeroGuiaRecGlosaOperadora"`
	NomeOperadora               string           `xml:"nomeOperadora"`
	ObjetoRecurso               string           `xml:"objetoRecurso"`
	DadosContratado             *DadosContratado `xml:"dadosContratado"`
	NumeroLote                  int              `xml:"numeroLote"`
	NumeroProtocolo             int              `xml:"numeroProtocolo"`
	OpcaoRecurso                *OpcaoRecurso    `xml:"opcaoRecurso"`
	DataRecurso                 string           `xml:"dataRecurso"`
	ValorTotalRecursado         float64          `xml:"valorTotalRecursado"`
	ValorTotalAcatado           float64          `xml:"valorTotalAcatado"`
}

// CtglosaReciboOdonto is retorno do recurso de glosa de odonto
type CtglosaReciboOdonto struct {
	XMLName                     xml.Name         `xml:"ct_glosaReciboOdonto"`
	RegistroANS                 string           `xml:"registroANS"`
	NumeroGuiaRecGlosaPrestador string           `xml:"numeroGuiaRecGlosaPrestador"`
	NomeOperadora               string           `xml:"nomeOperadora"`
	NumeroGuiaRecGlosaOperadora string           `xml:"numeroGuiaRecGlosaOperadora"`
	ObjetoRecurso               string           `xml:"objetoRecurso"`
	DadosContratado             *DadosContratado `xml:"dadosContratado"`
	NumeroLote                  int              `xml:"numeroLote"`
	NumeroProtocolo             int              `xml:"numeroProtocolo"`
	OpcaoRecurso                *OpcaoRecurso    `xml:"opcaoRecurso"`
	DataRecurso                 string           `xml:"dataRecurso"`
	ValorTotalRecursado         float64          `xml:"valorTotalRecursado"`
	ValorTotalAcatado           float64          `xml:"valorTotalAcatado"`
}

// CtelegibilidadeVerifica ...
type CtelegibilidadeVerifica struct {
	XMLName                   xml.Name           `xml:"ct_elegibilidadeVerifica"`
	DadosPrestador            *CtcontratadoDados `xml:"dadosPrestador"`
	NumeroCarteira            string             `xml:"numeroCarteira"`
	NomeBeneficiario          string             `xml:"nomeBeneficiario"`
	NumeroCNS                 string             `xml:"numeroCNS"`
	IdentificadorBeneficiario string             `xml:"identificadorBeneficiario"`
	ValidadeCarteira          string             `xml:"validadeCarteira"`
}

// CtfontePagadora ...
type CtfontePagadora struct {
	XMLName                      xml.Name `xml:"ct_fontePagadora"`
	RegistroANS                  string   `xml:"registroANS"`
	IdentificacaoUnidadePagadora string   `xml:"identificacaoUnidadePagadora"`
}

// CtguiaCabecalho ...
type CtguiaCabecalho struct {
	XMLName             xml.Name `xml:"ct_guiaCabecalho"`
	RegistroANS         string   `xml:"registroANS"`
	NumeroGuiaPrestador string   `xml:"numeroGuiaPrestador"`
}

// GuiasCancelamento ...
type GuiasCancelamento struct {
	XMLName             xml.Name `xml:"guiasCancelamento"`
	NumeroGuiaPrestador string   `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora string   `xml:"numeroGuiaOperadora"`
}

// CtguiaCancelamento ...
type CtguiaCancelamento struct {
	XMLName           xml.Name             `xml:"ct_guiaCancelamento"`
	TipoGuia          string               `xml:"tipoGuia"`
	DadosPrestador    *CtcontratadoDados   `xml:"dadosPrestador"`
	NumeroProtocolo   string               `xml:"numeroProtocolo"`
	GuiasCancelamento []*GuiasCancelamento `xml:"guiasCancelamento"`
}

// DadosGuia ...
type DadosGuia struct {
	XMLName             xml.Name `xml:"dadosGuia"`
	NumeroGuiaPrestador string   `xml:"numeroGuiaPrestador"`
	TipoGuia            string   `xml:"tipoGuia"`
	StatusCancelamento  string   `xml:"statusCancelamento"`
}

// GuiasCanceladas ...
type GuiasCanceladas struct {
	XMLName   xml.Name     `xml:"guiasCanceladas"`
	DadosGuia []*DadosGuia `xml:"dadosGuia"`
}

// CtguiaCancelamentoRecibo ...
type CtguiaCancelamentoRecibo struct {
	XMLName         xml.Name           `xml:"ct_guiaCancelamentoRecibo"`
	RegistroANS     string             `xml:"registroANS"`
	DadosPrestador  *CtcontratadoDados `xml:"dadosPrestador"`
	GuiasCanceladas *GuiasCanceladas   `xml:"guiasCanceladas"`
}

// GlosaGuia ...
type GlosaGuia struct {
	XMLName     xml.Name         `xml:"glosaGuia"`
	MotivoGlosa []*CtmotivoGlosa `xml:"motivoGlosa"`
}

// GlosasProcedimento ...
type GlosasProcedimento struct {
	XMLName                xml.Name         `xml:"glosasProcedimento"`
	MotivoGlosa            []*CtmotivoGlosa `xml:"motivoGlosa"`
	ValorGlosaProcedimento float64          `xml:"valorGlosaProcedimento"`
}

// ProcedimentoRealizado ...
type ProcedimentoRealizado struct {
	XMLName            xml.Name            `xml:"procedimentoRealizado"`
	GlosasProcedimento *GlosasProcedimento `xml:"glosasProcedimento"`
	*CtprocedimentoExecutado
}

// ProcedimentosRealizados ...
type ProcedimentosRealizados struct {
	XMLName               xml.Name                 `xml:"procedimentosRealizados"`
	ProcedimentoRealizado []*ProcedimentoRealizado `xml:"procedimentoRealizado"`
}

// CtguiaDados ...
type CtguiaDados struct {
	XMLName                 xml.Name                 `xml:"ct_guiaDados"`
	NumeroGuiaPrestador     string                   `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora     string                   `xml:"numeroGuiaOperadora"`
	DadosBeneficiario       *CtbeneficiarioDados     `xml:"dadosBeneficiario"`
	DataRealizacao          string                   `xml:"dataRealizacao"`
	VlInformadoGuia         *CtvalorTotal            `xml:"vlInformadoGuia"`
	GlosaGuia               *GlosaGuia               `xml:"glosaGuia"`
	ProcedimentosRealizados *ProcedimentosRealizados `xml:"procedimentosRealizados"`
}

// GlosaAnexo ...
type GlosaAnexo struct {
	XMLName      xml.Name         `xml:"glosaAnexo"`
	MotivoGlosa  []*CtmotivoGlosa `xml:"motivoGlosa"`
	VlGlosaAnexo float64          `xml:"vlGlosaAnexo"`
}

// ProcedimentoSolicitado ...
type ProcedimentoSolicitado struct {
	XMLName            xml.Name             `xml:"procedimentoSolicitado"`
	Procedimento       *CtprocedimentoDados `xml:"procedimento"`
	OpcaoFabricante    string               `xml:"opcaoFabricante"`
	QtdSolicitada      float64              `xml:"qtdSolicitada"`
	ValorSolicitado    float64              `xml:"valorSolicitado"`
	QtdAutorizada      float64              `xml:"qtdAutorizada"`
	ValorAutorizado    float64              `xml:"valorAutorizado"`
	GlosasProcedimento *GlosasProcedimento  `xml:"glosasProcedimento"`
}

// ProcedimentosSolicitados ...
type ProcedimentosSolicitados struct {
	XMLName                xml.Name                  `xml:"procedimentosSolicitados"`
	ProcedimentoSolicitado []*ProcedimentoSolicitado `xml:"procedimentoSolicitado"`
}

// CtguiaDadosAnexo ...
type CtguiaDadosAnexo struct {
	XMLName                     xml.Name                  `xml:"ct_guiaDadosAnexo"`
	NumeroGuiaPrestador         string                    `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora         string                    `xml:"numeroGuiaOperadora"`
	DadosBeneficiario           *CtbeneficiarioDados      `xml:"dadosBeneficiario"`
	DataEmissaoSolicitacaoAnexo string                    `xml:"dataEmissao_SolicitacaoAnexo"`
	VlInformadoGuia             *CtvalorTotal             `xml:"vlInformadoGuia"`
	GlosaAnexo                  *GlosaAnexo               `xml:"glosaAnexo"`
	ProcedimentosSolicitados    *ProcedimentosSolicitados `xml:"procedimentosSolicitados"`
}

// CtguiaDadosOdonto ...
type CtguiaDadosOdonto struct {
	XMLName                   xml.Name                 `xml:"ct_guiaDadosOdonto"`
	NumeroGuiaPrestador       string                   `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora       string                   `xml:"numeroGuiaOperadora"`
	NumeroCarteira            string                   `xml:"numeroCarteira"`
	AtendimentoRN             string                   `xml:"atendimentoRN"`
	NomeBeneficiario          string                   `xml:"nomeBeneficiario"`
	NumeroCNS                 string                   `xml:"numeroCNS"`
	IdentificadorBeneficiario string                   `xml:"identificadorBeneficiario"`
	VlInformadoGuia           *CtvalorTotal            `xml:"vlInformadoGuia"`
	GlosaGuia                 *GlosaGuia               `xml:"glosaGuia"`
	ProcedimentosRealizados   *ProcedimentosRealizados `xml:"procedimentosRealizados"`
}

// CtguiaRecurso is estrutura utilizada no retorno do recurso de glosa
type CtguiaRecurso struct {
	XMLName             xml.Name         `xml:"ct_guiaRecurso"`
	NumeroProtocolo     string           `xml:"numeroProtocolo"`
	NumDemoAnalisePagto string           `xml:"numDemoAnalisePagto"`
	NumeroGuiaRecurso   string           `xml:"numeroGuiaRecurso"`
	NumeroGuiaOrigem    string           `xml:"numeroGuiaOrigem"`
	MotivosGlosa        []*CtmotivoGlosa `xml:"motivosGlosa"`
}

// CtguiaRecursoLote is lote de recurso de glosa
type CtguiaRecursoLote struct {
	XMLName                xml.Name               `xml:"ct_guiaRecursoLote"`
	GuiaRecursoGlosaOdonto *CtorecursoGlosaOdonto `xml:"guiaRecursoGlosaOdonto"`
	GuiaRecursoGlosa       *CtmrecursoGlosa       `xml:"guiaRecursoGlosa"`
}

// CtguiaValorTotal ...
type CtguiaValorTotal struct {
	XMLName              xml.Name `xml:"ct_guiaValorTotal"`
	ValorProcedimentos   float64  `xml:"valorProcedimentos"`
	ValorDiarias         float64  `xml:"valorDiarias"`
	ValorTaxasAlugueis   float64  `xml:"valorTaxasAlugueis"`
	ValorMateriais       float64  `xml:"valorMateriais"`
	ValorMedicamentos    float64  `xml:"valorMedicamentos"`
	ValorOPME            float64  `xml:"valorOPME"`
	ValorGasesMedicinais float64  `xml:"valorGasesMedicinais"`
	ValorTotalGeral      float64  `xml:"valorTotalGeral"`
}

// CtguiaValorTotalSADT ...
type CtguiaValorTotalSADT struct {
	XMLName              xml.Name `xml:"ct_guiaValorTotalSADT"`
	ValorProcedimentos   float64  `xml:"valorProcedimentos"`
	ValorTaxasAlugueis   float64  `xml:"valorTaxasAlugueis"`
	ValorMateriais       float64  `xml:"valorMateriais"`
	ValorMedicamentos    float64  `xml:"valorMedicamentos"`
	ValorOPME            float64  `xml:"valorOPME"`
	ValorGasesMedicinais float64  `xml:"valorGasesMedicinais"`
	ValorTotalGeral      float64  `xml:"valorTotalGeral"`
}

// CthipoteseDiagnostica ...
type CthipoteseDiagnostica struct {
	XMLName           xml.Name       `xml:"ct_hipoteseDiagnostica"`
	Diagnostico       *Ctdiagnostico `xml:"diagnostico"`
	IndicacaoAcidente string         `xml:"indicacaoAcidente"`
}

// CodProfissional ...
type CodProfissional struct {
	XMLName                    xml.Name `xml:"codProfissional"`
	CodigoPrestadorNaOperadora string   `xml:"codigoPrestadorNaOperadora"`
	CpfContratado              string   `xml:"cpfContratado"`
}

// CtidentEquipe ...
type CtidentEquipe struct {
	XMLName                    xml.Name         `xml:"ct_identEquipe"`
	GrauPart                   string           `xml:"grauPart"`
	CodProfissional            *CodProfissional `xml:"codProfissional"`
	NomeProf                   string           `xml:"nomeProf"`
	Conselho                   string           `xml:"conselho"`
	NumeroConselhoProfissional string           `xml:"numeroConselhoProfissional"`
	UF                         string           `xml:"UF"`
	CBOS                       string           `xml:"CBOS"`
}

// CtidentEquipeSADT ...
type CtidentEquipeSADT struct {
	XMLName                    xml.Name         `xml:"ct_identEquipeSADT"`
	GrauPart                   string           `xml:"grauPart"`
	CodProfissional            *CodProfissional `xml:"codProfissional"`
	NomeProf                   string           `xml:"nomeProf"`
	Conselho                   string           `xml:"conselho"`
	NumeroConselhoProfissional string           `xml:"numeroConselhoProfissional"`
	UF                         string           `xml:"UF"`
	CBOS                       string           `xml:"CBOS"`
}

// CtintervaloCiclos ...
type CtintervaloCiclos struct {
	XMLName xml.Name `xml:"ct_intervaloCiclos"`
	Tempo   int      `xml:"tempo"`
	Unidade string   `xml:"unidade"`
}

// GuiasMedicas ...
type GuiasMedicas struct {
	XMLName xml.Name     `xml:"guiasMedicas"`
	Guias   *CtguiaDados `xml:"guias"`
}

// GuiasOdonto ...
type GuiasOdonto struct {
	XMLName xml.Name           `xml:"guiasOdonto"`
	Guias   *CtguiaDadosOdonto `xml:"guias"`
}

// GuiasTISS ...
type GuiasTISS struct {
	XMLName      xml.Name        `xml:"guiasTISS"`
	GuiasMedicas []*GuiasMedicas `xml:"guiasMedicas"`
	GuiasOdonto  []*GuiasOdonto  `xml:"guiasOdonto"`
}

// CtloteStatus is resposta a uma solicitação de situação de protocolo
type CtloteStatus struct {
	XMLName         xml.Name      `xml:"ct_loteStatus"`
	StatusProtocolo string        `xml:"statusProtocolo"`
	NumeroProtocolo string        `xml:"numeroProtocolo"`
	NumeroLote      string        `xml:"numeroLote"`
	DataEnvioLote   string        `xml:"dataEnvioLote"`
	ValorTotalLote  *CtvalorTotal `xml:"valorTotalLote"`
	GuiasTISS       *GuiasTISS    `xml:"guiasTISS"`
}

// CtloteAnexoStatus is resposta a uma solicitação de situação de protocolo
type CtloteAnexoStatus struct {
	XMLName         xml.Name        `xml:"ct_loteAnexoStatus"`
	StatusProtocolo string          `xml:"statusProtocolo"`
	NumeroProtocolo string          `xml:"numeroProtocolo"`
	NumeroLote      string          `xml:"numeroLote"`
	DataEnvioLote   string          `xml:"dataEnvioLote"`
	AnexosClinicos  *AnexosClinicos `xml:"anexosClinicos"`
}

// CtmotivoGlosa ...
type CtmotivoGlosa struct {
	XMLName        xml.Name `xml:"ct_motivoGlosa"`
	CodigoGlosa    string   `xml:"codigoGlosa"`
	DescricaoGlosa string   `xml:"descricaoGlosa"`
}

// CtopmeDados ...
type CtopmeDados struct {
	XMLName           xml.Name             `xml:"ct_opmeDados"`
	IdentificacaoOPME *CtprocedimentoDados `xml:"identificacaoOPME"`
	NomeFabricante    string               `xml:"nomeFabricante"`
}

// IdentificacaoOPM ...
type IdentificacaoOPM struct {
	XMLName           xml.Name             `xml:"identificacaoOPM"`
	IdentificacaoOPME *CtprocedimentoDados `xml:"identificacaoOPME"`
	Quantidade        int                  `xml:"quantidade"`
	CodigoBarra       string               `xml:"codigoBarra"`
	ValorUnitario     float64              `xml:"valorUnitario"`
	ValorTotal        float64              `xml:"valorTotal"`
}

// OPM ...
type OPM struct {
	IdentificacaoOPM []*IdentificacaoOPM `xml:"identificacaoOPM"`
}

// CtopmUtilizada ...
type CtopmUtilizada struct {
	XMLName       xml.Name `xml:"ct_opmUtilizada"`
	OPM           *OPM     `xml:"OPM"`
	ValorTotalOPM float64  `xml:"valorTotalOPM"`
}

// Despesa ...
type Despesa struct {
	XMLName            xml.Name                       `xml:"despesa"`
	CodigoDespesa      string                         `xml:"codigoDespesa"`
	ServicosExecutados *CtprocedimentoExecutadoOutras `xml:"servicosExecutados"`
}

// CtoutrasDespesas ...
type CtoutrasDespesas struct {
	XMLName xml.Name   `xml:"ct_outrasDespesas"`
	Despesa []*Despesa `xml:"despesa"`
}

// CtpagamentoDados ...
type CtpagamentoDados struct {
	XMLName        xml.Name `xml:"ct_pagamentoDados"`
	DataPagamento  string   `xml:"dataPagamento"`
	FormaPagamento string   `xml:"formaPagamento"`
	Banco          string   `xml:"banco"`
	Agencia        string   `xml:"agencia"`
	NrContaCheque  string   `xml:"nrContaCheque"`
}

// CtpagamentoResumo ...
type CtpagamentoResumo struct {
	XMLName         xml.Name      `xml:"ct_pagamentoResumo"`
	NumeroFatura    string        `xml:"numeroFatura"`
	NumeroLote      string        `xml:"numeroLote"`
	NumeroProtocolo string        `xml:"numeroProtocolo"`
	ValorTotalLote  *CtvalorTotal `xml:"valorTotalLote"`
}

// CtprestadorIdentificacao ...
type CtprestadorIdentificacao struct {
	XMLName                    xml.Name `xml:"ct_prestadorIdentificacao"`
	CNPJ                       string   `xml:"CNPJ"`
	CPF                        string   `xml:"CPF"`
	CodigoPrestadorNaOperadora string   `xml:"codigoPrestadorNaOperadora"`
}

// CtloginSenha ...
type CtloginSenha struct {
	XMLName        xml.Name `xml:"ct_loginSenha"`
	LoginPrestador string   `xml:"loginPrestador"`
	SenhaPrestador string   `xml:"senhaPrestador"`
}

// CtprocedimentoAutorizado ...
type CtprocedimentoAutorizado struct {
	XMLName                  xml.Name             `xml:"ct_procedimentoAutorizado"`
	Procedimento             *CtprocedimentoDados `xml:"procedimento"`
	QuantidadeSolicitada     int                  `xml:"quantidadeSolicitada"`
	QuantidadeAutorizada     int                  `xml:"quantidadeAutorizada"`
	ValorSolicitado          float64              `xml:"valorSolicitado"`
	ValorAutorizado          float64              `xml:"valorAutorizado"`
	OpcaoFabricante          string               `xml:"opcaoFabricante"`
	RegistroANVISA           string               `xml:"registroANVISA"`
	CodigoRefFabricante      string               `xml:"codigoRefFabricante"`
	AutorizacaoFuncionamento string               `xml:"autorizacaoFuncionamento"`
	MotivosNegativa          *MotivosNegativa     `xml:"motivosNegativa"`
}

// CtprocedimentosComplementares ...
type CtprocedimentosComplementares struct {
	XMLName       xml.Name             `xml:"ct_procedimentosComplementares"`
	DataProvavel  string               `xml:"dataProvavel"`
	Identificacao *CtprocedimentoDados `xml:"identificacao"`
	Quantidade    float64              `xml:"quantidade"`
}

// CtprocedimentoDados ...
type CtprocedimentoDados struct {
	XMLName               xml.Name `xml:"ct_procedimentoDados"`
	CodigoTabela          string   `xml:"codigoTabela"`
	CodigoProcedimento    string   `xml:"codigoProcedimento"`
	DescricaoProcedimento string   `xml:"descricaoProcedimento"`
}

// CtprocedimentoExecutado ...
type CtprocedimentoExecutado struct {
	XMLName               xml.Name             `xml:"ct_procedimentoExecutado"`
	DataExecucao          string               `xml:"dataExecucao"`
	HoraInicial           time.Time            `xml:"horaInicial"`
	HoraFinal             time.Time            `xml:"horaFinal"`
	Procedimento          *CtprocedimentoDados `xml:"procedimento"`
	UnidadeMedida         string               `xml:"unidadeMedida"`
	QuantidadeExecutada   float64              `xml:"quantidadeExecutada"`
	ViaAcesso             string               `xml:"viaAcesso"`
	TecnicaUtilizada      string               `xml:"tecnicaUtilizada"`
	ValorUnitario         float64              `xml:"valorUnitario"`
	ValorTotal            float64              `xml:"valorTotal"`
	CodigoDespesa         string               `xml:"codigoDespesa"`
	FatorReducaoAcrescimo float64              `xml:"fatorReducaoAcrescimo"`
}

// DenteRegiao ...
type DenteRegiao struct {
	XMLName   xml.Name `xml:"denteRegiao"`
	CodDente  string   `xml:"codDente"`
	CodRegiao string   `xml:"codRegiao"`
}

// CtprocedimentoExecutadoOdonto ...
type CtprocedimentoExecutadoOdonto struct {
	XMLName        xml.Name             `xml:"ct_procedimentoExecutadoOdonto"`
	Procedimento   *CtprocedimentoDados `xml:"procedimento"`
	DenteRegiao    *DenteRegiao         `xml:"denteRegiao"`
	DenteFace      string               `xml:"denteFace"`
	QtdProc        int                  `xml:"qtdProc"`
	QtdUS          float64              `xml:"qtdUS"`
	ValorProc      float64              `xml:"valorProc"`
	ValorFranquia  float64              `xml:"valorFranquia"`
	Autorizado     string               `xml:"autorizado"`
	DataRealizacao string               `xml:"dataRealizacao"`
}

// CtprocedimentoExecutadoOutras ...
type CtprocedimentoExecutadoOutras struct {
	XMLName                  xml.Name  `xml:"ct_procedimentoExecutadoOutras"`
	DataExecucao             string    `xml:"dataExecucao"`
	HoraInicial              time.Time `xml:"horaInicial"`
	HoraFinal                time.Time `xml:"horaFinal"`
	CodigoTabela             string    `xml:"codigoTabela"`
	CodigoProcedimento       string    `xml:"codigoProcedimento"`
	QuantidadeExecutada      float64   `xml:"quantidadeExecutada"`
	UnidadeMedida            string    `xml:"unidadeMedida"`
	ReducaoAcrescimo         float64   `xml:"reducaoAcrescimo"`
	ValorUnitario            float64   `xml:"valorUnitario"`
	ValorTotal               float64   `xml:"valorTotal"`
	DescricaoProcedimento    string    `xml:"descricaoProcedimento"`
	RegistroANVISA           string    `xml:"registroANVISA"`
	CodigoRefFabricante      string    `xml:"codigoRefFabricante"`
	AutorizacaoFuncionamento string    `xml:"autorizacaoFuncionamento"`
}

// IdentEquipe ...
type IdentEquipe struct {
	XMLName             xml.Name       `xml:"identEquipe"`
	IdentificacaoEquipe *CtidentEquipe `xml:"identificacaoEquipe"`
}

// CtprocedimentoExecutadoInt ...
type CtprocedimentoExecutadoInt struct {
	XMLName             xml.Name             `xml:"ct_procedimentoExecutadoInt"`
	DataExecucao        string               `xml:"dataExecucao"`
	HoraInicial         time.Time            `xml:"horaInicial"`
	HoraFinal           time.Time            `xml:"horaFinal"`
	Procedimento        *CtprocedimentoDados `xml:"procedimento"`
	QuantidadeExecutada int                  `xml:"quantidadeExecutada"`
	ViaAcesso           string               `xml:"viaAcesso"`
	TecnicaUtilizada    string               `xml:"tecnicaUtilizada"`
	ReducaoAcrescimo    float64              `xml:"reducaoAcrescimo"`
	ValorUnitario       float64              `xml:"valorUnitario"`
	ValorTotal          float64              `xml:"valorTotal"`
	IdentEquipe         []*IdentEquipe       `xml:"identEquipe"`
}

// Profissionais ...
type Profissionais struct {
	XMLName                    xml.Name         `xml:"profissionais"`
	GrauParticipacao           string           `xml:"grauParticipacao"`
	CodProfissional            *CodProfissional `xml:"codProfissional"`
	NomeProfissional           string           `xml:"nomeProfissional"`
	ConselhoProfissional       string           `xml:"conselhoProfissional"`
	NumeroConselhoProfissional string           `xml:"numeroConselhoProfissional"`
	UF                         string           `xml:"UF"`
	CBO                        string           `xml:"CBO"`
}

// CtprocedimentoExecutadoHonorIndiv ...
type CtprocedimentoExecutadoHonorIndiv struct {
	XMLName             xml.Name             `xml:"ct_procedimentoExecutadoHonorIndiv"`
	DataExecucao        string               `xml:"dataExecucao"`
	HoraInicial         time.Time            `xml:"horaInicial"`
	HoraFinal           time.Time            `xml:"horaFinal"`
	Procedimento        *CtprocedimentoDados `xml:"procedimento"`
	QuantidadeExecutada int                  `xml:"quantidadeExecutada"`
	ViaAcesso           string               `xml:"viaAcesso"`
	TecnicaUtilizada    string               `xml:"tecnicaUtilizada"`
	ReducaoAcrescimo    float64              `xml:"reducaoAcrescimo"`
	ValorUnitario       float64              `xml:"valorUnitario"`
	ValorTotal          float64              `xml:"valorTotal"`
	Profissionais       []*Profissionais     `xml:"profissionais"`
}

// CtprocedimentoExecutadoSadt ...
type CtprocedimentoExecutadoSadt struct {
	XMLName             xml.Name             `xml:"ct_procedimentoExecutadoSadt"`
	DataExecucao        string               `xml:"dataExecucao"`
	HoraInicial         time.Time            `xml:"horaInicial"`
	HoraFinal           time.Time            `xml:"horaFinal"`
	Procedimento        *CtprocedimentoDados `xml:"procedimento"`
	QuantidadeExecutada int                  `xml:"quantidadeExecutada"`
	ViaAcesso           string               `xml:"viaAcesso"`
	TecnicaUtilizada    string               `xml:"tecnicaUtilizada"`
	ReducaoAcrescimo    float64              `xml:"reducaoAcrescimo"`
	ValorUnitario       float64              `xml:"valorUnitario"`
	ValorTotal          float64              `xml:"valorTotal"`
	EquipeSadt          []*CtidentEquipeSADT `xml:"equipeSadt"`
}

// CtprocedimentoSolicitado ...
type CtprocedimentoSolicitado struct {
	XMLName              xml.Name             `xml:"ct_procedimentoSolicitado"`
	Procedimento         *CtprocedimentoDados `xml:"procedimento"`
	UnidadeMedida        string               `xml:"unidadeMedida"`
	QuantidadeSolicitada int                  `xml:"quantidadeSolicitada"`
}

// MotivosGlosa ...
type MotivosGlosa struct {
	XMLName     xml.Name         `xml:"motivosGlosa"`
	MotivoGlosa []*CtmotivoGlosa `xml:"motivoGlosa"`
}

// GlosaProtocolo ...
type GlosaProtocolo struct {
	XMLName          xml.Name      `xml:"glosaProtocolo"`
	MotivosGlosa     *MotivosGlosa `xml:"motivosGlosa"`
	VlGlosaProtocolo float64       `xml:"vlGlosaProtocolo"`
}

// DadosGuiasProtocolo ...
type DadosGuiasProtocolo struct {
	XMLName          xml.Name             `xml:"dadosGuiasProtocolo"`
	DadosGuias       []*CtguiaDados       `xml:"dadosGuias"`
	DadosGuiasOdonto []*CtguiaDadosOdonto `xml:"dadosGuiasOdonto"`
}

// CtprotocoloDetalhe ...
type CtprotocoloDetalhe struct {
	XMLName             xml.Name             `xml:"ct_protocoloDetalhe"`
	NumeroProtocolo     string               `xml:"numeroProtocolo"`
	ValorTotalProtocolo float64              `xml:"valorTotalProtocolo"`
	GlosaProtocolo      *GlosaProtocolo      `xml:"glosaProtocolo"`
	DadosGuiasProtocolo *DadosGuiasProtocolo `xml:"dadosGuiasProtocolo"`
}

// AnexosGuiasTISS ...
type AnexosGuiasTISS struct {
	AnexoSituacaoInicial   []*CtoanexoSituacaoInicial `xml:"anexoSituacaoInicial"`
	AnexoSolicitacaoRadio  *CtmanexoSolicitacaoRadio  `xml:"anexoSolicitacaoRadio"`
	AnexoSolicitacaoQuimio *CtmanexoSolicitacaoQuimio `xml:"anexoSolicitacaoQuimio"`
	AnexoSolicitacaoOPME   *CtmanexoSolicitacaoOPME   `xml:"anexoSolicitacaoOPME"`
}

// CtanexoLote is estrutura da resposta da operadora a um lote de anexos
type CtanexoLote struct {
	XMLName         xml.Name         `xml:"ct_anexoLote"`
	NumeroLote      string           `xml:"numeroLote"`
	AnexosGuiasTISS *AnexosGuiasTISS `xml:"AnexosGuiasTISS"`
}

// CtprotocoloDetalheAnexo ...
type CtprotocoloDetalheAnexo struct {
	XMLName             xml.Name            `xml:"ct_protocoloDetalheAnexo"`
	NumeroProtocolo     string              `xml:"numeroProtocolo"`
	ValorTotalProtocolo float64             `xml:"valorTotalProtocolo"`
	GlosasProtocolo     []*CtmotivoGlosa    `xml:"glosasProtocolo"`
	VlGlosaProtocolo    float64             `xml:"vlGlosaProtocolo"`
	DadosGuias          []*CtguiaDadosAnexo `xml:"dadosGuias"`
}

// CtprotocoloRecurso is estrutura da resposta da operadora a um lote de guias de recurso de glosa de medicina e de odonto
type CtprotocoloRecurso struct {
	XMLName         xml.Name         `xml:"ct_protocoloRecurso"`
	NumeroProtocolo string           `xml:"numeroProtocolo"`
	GlosaProtocolo  []*CtmotivoGlosa `xml:"glosaProtocolo"`
	DadosGuias      []*CtguiaRecurso `xml:"dadosGuias"`
}

// CtprotocoloRecebimentoAnexo ...
type CtprotocoloRecebimentoAnexo struct {
	XMLName                xml.Name                 `xml:"ct_protocoloRecebimentoAnexo"`
	NumeroProtocolo        string                   `xml:"numeroProtocolo"`
	IdentificacaoOperadora *CtfontePagadora         `xml:"identificacaoOperadora"`
	DadosPrestador         *CtcontratadoDados       `xml:"dadosPrestador"`
	NumeroLote             string                   `xml:"numeroLote"`
	DataEnvioLote          string                   `xml:"dataEnvioLote"`
	DetalheProtocolo       *CtprotocoloDetalheAnexo `xml:"detalheProtocolo"`
}

// CtprotocoloRecebimento ...
type CtprotocoloRecebimento struct {
	XMLName          xml.Name            `xml:"ct_protocoloRecebimento"`
	RegistroANS      string              `xml:"registroANS"`
	DadosPrestador   *CtcontratadoDados  `xml:"dadosPrestador"`
	NumeroLote       string              `xml:"numeroLote"`
	DataEnvioLote    string              `xml:"dataEnvioLote"`
	DetalheProtocolo *CtprotocoloDetalhe `xml:"detalheProtocolo"`
}

// CtprotocoloRecebimentoRecurso ...
type CtprotocoloRecebimentoRecurso struct {
	XMLName                xml.Name            `xml:"ct_protocoloRecebimentoRecurso"`
	NumeroProtocolo        string              `xml:"numeroProtocolo"`
	IdentificacaoOperadora *CtfontePagadora    `xml:"identificacaoOperadora"`
	DadosPrestador         *CtcontratadoDados  `xml:"dadosPrestador"`
	NumeroLote             string              `xml:"numeroLote"`
	DataEnvioLote          string              `xml:"dataEnvioLote"`
	DetalheProtocolo       *CtprotocoloRecurso `xml:"detalheProtocolo"`
}

// CtprotocoloSolicitacaoStatus ...
type CtprotocoloSolicitacaoStatus struct {
	XMLName         xml.Name           `xml:"ct_protocoloSolicitacaoStatus"`
	DadosPrestador  *CtcontratadoDados `xml:"dadosPrestador"`
	NumeroProtocolo string             `xml:"numeroProtocolo"`
}

// Lote ...
type Lote struct {
	XMLName      xml.Name       `xml:"lote"`
	DetalheLote  *CtloteStatus  `xml:"detalheLote"`
	MensagemErro *CtmotivoGlosa `xml:"mensagemErro"`
}

// CtprotocoloStatus is estrutura utilizada na resposta da operadora sobre a situação do protocolo
type CtprotocoloStatus struct {
	XMLName                xml.Name           `xml:"ct_protocoloStatus"`
	IdentificacaoOperadora string             `xml:"identificacaoOperadora"`
	DadosPrestador         *CtcontratadoDados `xml:"dadosPrestador"`
	Lote                   *Lote              `xml:"lote"`
}

// LoteAnexo ...
type LoteAnexo struct {
	XMLName          xml.Name           `xml:"loteAnexo"`
	DetalheLoteAnexo *CtloteAnexoStatus `xml:"detalheLoteAnexo"`
	MensagemErro     *CtmotivoGlosa     `xml:"mensagemErro"`
}

// CtprotocoloAnexoStatus is estrutura utilizada na resposta da operadora sobre a situação do protocolo
type CtprotocoloAnexoStatus struct {
	XMLName                xml.Name           `xml:"ct_protocoloAnexoStatus"`
	IdentificacaoOperadora string             `xml:"identificacaoOperadora"`
	DadosPrestador         *CtcontratadoDados `xml:"dadosPrestador"`
	LoteAnexo              *LoteAnexo         `xml:"loteAnexo"`
}

// ItensGuia ...
type ItensGuia struct {
	XMLName           xml.Name             `xml:"itensGuia"`
	DataInicio        string               `xml:"dataInicio"`
	DataFim           string               `xml:"dataFim"`
	ProcRecurso       *CtprocedimentoDados `xml:"procRecurso"`
	DenteRegiao       *DenteRegiao         `xml:"denteRegiao"`
	DenteFace         string               `xml:"denteFace"`
	CodGlosaItem      string               `xml:"codGlosaItem"`
	ValorRecursado    float64              `xml:"valorRecursado"`
	JustificativaItem string               `xml:"justificativaItem"`
}

// OpcaoRecursoGuia ...
type OpcaoRecursoGuia struct {
	XMLName     xml.Name       `xml:"opcaoRecursoGuia"`
	RecursoGuia []*RecursoGuia `xml:"recursoGuia"`
	ItensGuia   []*ItensGuia   `xml:"itensGuia"`
}

// GuiasRecurso ...
type GuiasRecurso struct {
	XMLName             xml.Name          `xml:"guiasRecurso"`
	NumeroGuiaOrigem    string            `xml:"numeroGuiaOrigem"`
	NumeroGuiaOperadora string            `xml:"numeroGuiaOperadora"`
	Senha               string            `xml:"senha"`
	OpcaoRecursoGuia    *OpcaoRecursoGuia `xml:"opcaoRecursoGuia"`
}

// CtrecursoGlosaRecebimento ...
type CtrecursoGlosaRecebimento struct {
	XMLName                 xml.Name           `xml:"ct_recursoGlosaRecebimento"`
	NrProtocoloRecursoGlosa string             `xml:"nrProtocoloRecursoGlosa"`
	DataEnvioRecurso        string             `xml:"dataEnvioRecurso"`
	DataRecebimentoRecurso  string             `xml:"dataRecebimentoRecurso"`
	NumeroLote              string             `xml:"numeroLote"`
	RegistroANS             string             `xml:"registroANS"`
	DadosPrestador          *CtcontratadoDados `xml:"dadosPrestador"`
	NrProtocoloRecursado    string             `xml:"nrProtocoloRecursado"`
	RecursoProtocolo        *RecursoProtocolo  `xml:"recursoProtocolo"`
	QtGuiasRecurso          int                `xml:"qtGuiasRecurso"`
	GuiasRecurso            []*GuiasRecurso    `xml:"guiasRecurso"`
	Observacao              string             `xml:"observacao"`
	ValorTotalRecursado     float64            `xml:"valorTotalRecursado"`
}

// CtrecebimentoLote ...
type CtrecebimentoLote struct {
	XMLName              xml.Name                `xml:"ct_recebimentoLote"`
	MensagemErro         *CtmotivoGlosa          `xml:"mensagemErro"`
	ProtocoloRecebimento *CtprotocoloRecebimento `xml:"protocoloRecebimento"`
}

// CtrecebimentoRecurso ...
type CtrecebimentoRecurso struct {
	XMLName              xml.Name                   `xml:"ct_recebimentoRecurso"`
	MensagemErro         *CtmotivoGlosa             `xml:"mensagemErro"`
	ProtocoloRecebimento *CtrecursoGlosaRecebimento `xml:"protocoloRecebimento"`
}

// CtreciboCancelaGuia ...
type CtreciboCancelaGuia struct {
	XMLName           xml.Name                  `xml:"ct_reciboCancelaGuia"`
	MensagemErro      *CtmotivoGlosa            `xml:"mensagemErro"`
	ReciboCancelaGuia *CtguiaCancelamentoRecibo `xml:"reciboCancelaGuia"`
}

// CtreciboComunicacao ...
type CtreciboComunicacao struct {
	XMLName           xml.Name                          `xml:"ct_reciboComunicacao"`
	MensagemErro      *CtmotivoGlosa                    `xml:"mensagemErro"`
	ReciboComunicacao *CtmbeneficiarioComunicacaoRecibo `xml:"reciboComunicacao"`
}

// CtrespostaElegibilidade ...
type CtrespostaElegibilidade struct {
	XMLName             xml.Name               `xml:"ct_respostaElegibilidade"`
	MensagemErro        *CtmotivoGlosa         `xml:"mensagemErro"`
	ReciboElegibilidade *CtelegibilidadeRecibo `xml:"reciboElegibilidade"`
}

// ReciboGlosaStatus ...
type ReciboGlosaStatus struct {
	XMLName                         xml.Name           `xml:"reciboGlosaStatus"`
	NrProtocoloRecursoGlosa         string             `xml:"nrProtocoloRecursoGlosa"`
	DataEnvioRecurso                string             `xml:"dataEnvioRecurso"`
	DataRecebimentoRecurso          string             `xml:"dataRecebimentoRecurso"`
	NumeroLote                      string             `xml:"numeroLote"`
	RegistroANS                     string             `xml:"registroANS"`
	DadosPrestador                  *CtcontratadoDados `xml:"dadosPrestador"`
	NrProtocoloSituacaoRecursoGlosa string             `xml:"nrProtocoloSituacaoRecursoGlosa"`
	DataSituacao                    string             `xml:"dataSituacao"`
	SituacaoProtocolo               string             `xml:"situacaoProtocolo"`
}

// CtrespostaGlosa ...
type CtrespostaGlosa struct {
	XMLName           xml.Name             `xml:"ct_respostaGlosa"`
	ReciboGlosa       *CtglosaRecibo       `xml:"reciboGlosa"`
	ReciboGlosaOdonto *CtglosaReciboOdonto `xml:"reciboGlosaOdonto"`
	ReciboGlosaStatus *ReciboGlosaStatus   `xml:"reciboGlosaStatus"`
	MensagemErro      *CtmotivoGlosa       `xml:"mensagemErro"`
}

// CtrespostaGlosaGuiaMedica ...
type CtrespostaGlosaGuiaMedica struct {
	XMLName                        xml.Name `xml:"ct_respostaGlosaGuiaMedica"`
	NumeroGuiaPrestador            string   `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora            string   `xml:"numeroGuiaOperadora"`
	Senha                          string   `xml:"senha"`
	CodGlosa                       string   `xml:"codGlosa"`
	JustificativaPrestador         string   `xml:"justificativaPrestador"`
	RecursoGuiaAcatado             string   `xml:"recursoGuiaAcatado"`
	JustificativaOPSnaoAcatadoGuia string   `xml:"justificativaOPSnaoAcatadoGuia"`
}

// CtrespostaGlosaItemMedico ...
type CtrespostaGlosaItemMedico struct {
	XMLName                xml.Name             `xml:"ct_respostaGlosaItemMedico"`
	NumeroGuiaPrestador    string               `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora    string               `xml:"numeroGuiaOperadora"`
	Senha                  string               `xml:"senha"`
	DataRealizacao         string               `xml:"dataRealizacao"`
	DataFim                string               `xml:"dataFim"`
	ProcRecurso            *CtprocedimentoDados `xml:"procRecurso"`
	CodGlosa               string               `xml:"codGlosa"`
	ValorRecursado         float64              `xml:"valorRecursado"`
	JustificativaPrestador string               `xml:"justificativaPrestador"`
	ValorAcatadado         float64              `xml:"valorAcatadado"`
	JustificativaOperadora string               `xml:"justificativaOperadora"`
}

// CtrespostaRecursoGuiaOdonto ...
type CtrespostaRecursoGuiaOdonto struct {
	XMLName             xml.Name `xml:"ct_respostaRecursoGuiaOdonto"`
	NumeroGuiaPrestador string   `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora string   `xml:"numeroGuiaOperadora"`
	Senha               string   `xml:"senha"`
	NomeBeneficiario    string   `xml:"nomeBeneficiario"`
	CodGlosaGuia        string   `xml:"codGlosaGuia"`
	JustificativaGuia   string   `xml:"justificativaGuia"`
	RecursoAcatadoGuia  string   `xml:"recursoAcatadoGuia"`
}

// RecursoProcedimento ...
type RecursoProcedimento struct {
	XMLName                xml.Name             `xml:"recursoProcedimento"`
	DataRealizacao         string               `xml:"dataRealizacao"`
	DenteRegiao            *DenteRegiao         `xml:"denteRegiao"`
	DenteFace              string               `xml:"denteFace"`
	Quantidade             int                  `xml:"quantidade"`
	ProcRecurso            *CtprocedimentoDados `xml:"procRecurso"`
	CodGlosaProc           string               `xml:"codGlosaProc"`
	ValorRecursado         float64              `xml:"valorRecursado"`
	JustificativaPrestador string               `xml:"justificativaPrestador"`
	ValorAcatado           float64              `xml:"valorAcatado"`
	JustificativaOperadora string               `xml:"justificativaOperadora"`
}

// CtrespostaRecursoItemOdonto ...
type CtrespostaRecursoItemOdonto struct {
	XMLName             xml.Name               `xml:"ct_respostaRecursoItemOdonto"`
	NumeroGuiaPrestador string                 `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora string                 `xml:"numeroGuiaOperadora"`
	Senha               string                 `xml:"senha"`
	NomeBeneficiario    string                 `xml:"nomeBeneficiario"`
	RecursoProcedimento []*RecursoProcedimento `xml:"recursoProcedimento"`
}

// CtsituacaoAutorizacao ...
type CtsituacaoAutorizacao struct {
	XMLName                  xml.Name                   `xml:"ct_situacaoAutorizacao"`
	MensagemErro             *CtmotivoGlosa             `xml:"mensagemErro"`
	AutorizacaoInternacao    *CtmautorizacaoInternacao  `xml:"autorizacaoInternacao"`
	AutorizacaoServico       *CtmautorizacaoServico     `xml:"autorizacaoServico"`
	AutorizacaoProrrogacao   *CtmautorizacaoProrrogacao `xml:"autorizacaoProrrogacao"`
	AutorizacaoServicoOdonto *CtoautorizacaoServico     `xml:"autorizacaoServicoOdonto"`
}

// CtsituacaoProtocolo ...
type CtsituacaoProtocolo struct {
	XMLName                xml.Name                `xml:"ct_situacaoProtocolo"`
	MensagemErro           *CtmotivoGlosa          `xml:"mensagemErro"`
	SituacaoDoProtocolo    *CtprotocoloStatus      `xml:"situacaoDoProtocolo"`
	SituacaoProtocoloAnexo *CtprotocoloAnexoStatus `xml:"situacaoProtocoloAnexo"`
}

// Dentes ...
type Dentes struct {
	XMLName          xml.Name `xml:"dentes"`
	ElementoDentario string   `xml:"elementoDentario"`
	CondicaoClinica  string   `xml:"condicaoClinica"`
}

// CtsituacaoClinica ...
type CtsituacaoClinica struct {
	XMLName xml.Name  `xml:"ct_situacaoClinica"`
	Dentes  []*Dentes `xml:"dentes"`
}

// CtsolicitacaoProcedimento ...
type CtsolicitacaoProcedimento struct {
	XMLName xml.Name `xml:"ct_solicitacaoProcedimento"`
	*CtmsolicitacaoLote
}

// CtvalorCreditoDesconto ...
type CtvalorCreditoDesconto struct {
	XMLName        xml.Name `xml:"ct_valorCreditoDesconto"`
	TipoLancamento string   `xml:"tipoLancamento"`
	Descricao      string   `xml:"descricao"`
	Valor          float64  `xml:"valor"`
}

// CtvalorTotal ...
type CtvalorTotal struct {
	XMLName         xml.Name `xml:"ct_valorTotal"`
	ValorProcessado float64  `xml:"valorProcessado"`
	ValorGlosa      float64  `xml:"valorGlosa"`
	ValorLiberado   float64  `xml:"valorLiberado"`
}
