// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
	"time"
)

// MensagemTISS ...
type MensagemTISS struct {
	XMLName                xml.Name            `xml:"mensagemTISS"`
	Cabecalho              *CabecalhoTransacao `xml:"cabecalho"`
	OperadoraParaPrestador *OperadoraPrestador `xml:"operadoraParaPrestador"`
	PrestadorParaOperadora *PrestadorOperadora `xml:"prestadorParaOperadora"`
	Epilogo                *Epilogo            `xml:"epilogo"`
	AssinaturaDigital      *AssinaturaDigital  `xml:"assinaturaDigital"`
}

// IdentificacaoTransacao ...
type IdentificacaoTransacao struct {
	XMLName               xml.Name  `xml:"identificacaoTransacao"`
	TipoTransacao         string    `xml:"tipoTransacao"`
	SequencialTransacao   string    `xml:"sequencialTransacao"`
	DataRegistroTransacao string    `xml:"dataRegistroTransacao"`
	HoraRegistroTransacao time.Time `xml:"horaRegistroTransacao"`
}

// IdentificacaoPrestador ...
type IdentificacaoPrestador struct {
	XMLName xml.Name `xml:"identificacaoPrestador"`
	*CtprestadorIdentificacao
}

// Origem ...
type Origem struct {
	XMLName                xml.Name                `xml:"origem"`
	IdentificacaoPrestador *IdentificacaoPrestador `xml:"identificacaoPrestador"`
	RegistroANS            string                  `xml:"registroANS"`
}

// Destino ...
type Destino struct {
	XMLName                xml.Name                  `xml:"destino"`
	IdentificacaoPrestador *CtprestadorIdentificacao `xml:"identificacaoPrestador"`
	RegistroANS            string                    `xml:"registroANS"`
}

// CabecalhoTransacao ...
type CabecalhoTransacao struct {
	XMLName                xml.Name                `xml:"cabecalhoTransacao"`
	IdentificacaoTransacao *IdentificacaoTransacao `xml:"identificacaoTransacao"`
	FalhaNegocio           string                  `xml:"falhaNegocio"`
	Origem                 *Origem                 `xml:"origem"`
	Destino                *Destino                `xml:"destino"`
	VersaoPadrao           string                  `xml:"versaoPadrao"`
	LoginSenhaPrestador    *CtloginSenha           `xml:"loginSenhaPrestador"`
}

// RecebimentoAnexo ...
type RecebimentoAnexo struct {
	XMLName                   xml.Name            `xml:"recebimentoAnexo"`
	MensagemErro              *CtmotivoGlosa      `xml:"mensagemErro"`
	ProtocoloRecebimentoAnexo *CtanexoRecebimento `xml:"protocoloRecebimentoAnexo"`
}

// RespostaElegibilidade ...
type RespostaElegibilidade struct {
	XMLName             xml.Name               `xml:"respostaElegibilidade"`
	MensagemErro        *CtmotivoGlosa         `xml:"mensagemErro"`
	ReciboElegibilidade *CtelegibilidadeRecibo `xml:"reciboElegibilidade"`
}

// OperadoraPrestador ...
type OperadoraPrestador struct {
	XMLName                 xml.Name                `xml:"operadoraPrestador"`
	RecebimentoLote         *CtrecebimentoLote      `xml:"recebimentoLote"`
	RecebimentoAnexo        *RecebimentoAnexo       `xml:"recebimentoAnexo"`
	RecebimentoRecursoGlosa *CtrecebimentoRecurso   `xml:"recebimentoRecursoGlosa"`
	DemonstrativosRetorno   *CtdemonstrativoRetorno `xml:"demonstrativosRetorno"`
	SituacaoProtocolo       *CtsituacaoProtocolo    `xml:"situacaoProtocolo"`
	AutorizacaoServicos     *CtsituacaoAutorizacao  `xml:"autorizacaoServicos"`
	SituacaoAutorizacao     *CtsituacaoAutorizacao  `xml:"situacaoAutorizacao"`
	RespostaElegibilidade   *RespostaElegibilidade  `xml:"respostaElegibilidade"`
	ReciboCancelaGuia       *CtreciboCancelaGuia    `xml:"reciboCancelaGuia"`
	ReciboComunicacao       *CtreciboComunicacao    `xml:"reciboComunicacao"`
	RespostaRecursoGlosa    *CtrespostaGlosa        `xml:"respostaRecursoGlosa"`
}

// PrestadorOperadora ...
type PrestadorOperadora struct {
	XMLName                         xml.Name                      `xml:"prestadorOperadora"`
	LoteGuias                       *CtmguiaLote                  `xml:"loteGuias"`
	LoteAnexos                      *CtanexoLote                  `xml:"loteAnexos"`
	SolicitacaoDemonstrativoRetorno *CtdemonstrativoSolicitacao   `xml:"solicitacaoDemonstrativoRetorno"`
	SolicitacaoStatusProtocolo      *CtprotocoloSolicitacaoStatus `xml:"solicitacaoStatusProtocolo"`
	SolicitacaoProcedimento         *CtsolicitacaoProcedimento    `xml:"solicitacaoProcedimento"`
	SolicitaStatusAutorizacao       *CtautorizacaoSolicitaStatus  `xml:"solicitaStatusAutorizacao"`
	VerificaElegibilidade           *CtelegibilidadeVerifica      `xml:"verificaElegibilidade"`
	CancelaGuia                     *CtguiaCancelamento           `xml:"cancelaGuia"`
	ComunicacaoInternacao           *CtmbeneficiarioComunicacao   `xml:"comunicacaoInternacao"`
	RecursoGlosa                    *CtguiaRecursoLote            `xml:"recursoGlosa"`
	SolicitacaoStatusRecursoGlosa   *CtprotocoloSolicitacaoStatus `xml:"solicitacaoStatusRecursoGlosa"`
}

// Epilogo ...
type Epilogo struct {
	XMLName xml.Name `xml:"epilogo"`
	Hash    string   `xml:"hash"`
}
