// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
	"time"
)

// AnsParaOperadora ...
type AnsParaOperadora struct {
	XMLName           xml.Name              `xml:"ansParaOperadora"`
	ControleQualidade *MsgControleQualidade `xml:"controleQualidade"`
}

// Mensagem ...
type Mensagem struct {
	AnsParaOperadora *AnsParaOperadora `xml:"ansParaOperadora"`
}

// MensagemEnvioANS ...
type MensagemEnvioANS struct {
	XMLName   xml.Name            `xml:"mensagemEnvioANS"`
	Cabecalho *CabecalhoTransacao `xml:"cabecalho"`
	Mensagem  *Mensagem           `xml:"Mensagem"`
	Epilogo   *Epilogo            `xml:"epilogo"`
}

// IdentificacaoTransacao ...
type IdentificacaoTransacao struct {
	XMLName               xml.Name  `xml:"identificacaoTransacao"`
	TipoTransacao         string    `xml:"tipoTransacao"`
	NumeroLote            string    `xml:"numeroLote"`
	CompetenciaLote       string    `xml:"competenciaLote"`
	DataRegistroTransacao string    `xml:"dataRegistroTransacao"`
	HoraRegistroTransacao time.Time `xml:"horaRegistroTransacao"`
}

// CabecalhoTransacao ...
type CabecalhoTransacao struct {
	XMLName                xml.Name                `xml:"cabecalhoTransacao"`
	IdentificacaoTransacao *IdentificacaoTransacao `xml:"identificacaoTransacao"`
	RegistroANS            string                  `xml:"registroANS"`
	VersaoPadrao           string                  `xml:"versaoPadrao"`
}

// ContratadoExecutante ...
type ContratadoExecutante struct {
	XMLName                 xml.Name `xml:"contratadoExecutante"`
	CNES                    string   `xml:"CNES"`
	IdentificadorExecutante string   `xml:"identificadorExecutante"`
	CodigoCNPJCPF           string   `xml:"codigoCNPJ_CPF"`
}

// LancamentosRegistradosANS ...
type LancamentosRegistradosANS struct {
	XMLName           xml.Name `xml:"lancamentosRegistradosANS"`
	DataProcessamento []string `xml:"dataProcessamento"`
}

// Procedimento ...
type Procedimento struct {
	XMLName            xml.Name `xml:"procedimento"`
	GrupoProcedimento  string   `xml:"grupoProcedimento"`
	CodigoProcedimento string   `xml:"codigoProcedimento"`
}

// DenteRegiao ...
type DenteRegiao struct {
	XMLName   xml.Name `xml:"denteRegiao"`
	CodDente  string   `xml:"codDente"`
	CodRegiao string   `xml:"codRegiao"`
}

// Pacote ...
type Pacote struct {
	XMLName            xml.Name                  `xml:"pacote"`
	CodigoTabela       string                    `xml:"codigoTabela"`
	CodigoProcedimento string                    `xml:"codigoProcedimento"`
	OcorrenciasPacote  *OcorrenciaGrupoElementos `xml:"ocorrenciasPacote"`
}

// DetalhamentoPacote ...
type DetalhamentoPacote struct {
	XMLName xml.Name  `xml:"detalhamentoPacote"`
	Pacote  []*Pacote `xml:"pacote"`
}

// ProcedimentoItemAssistencial ...
type ProcedimentoItemAssistencial struct {
	XMLName                                 xml.Name                  `xml:"procedimentoItemAssistencial"`
	CodigoTabela                            string                    `xml:"codigoTabela"`
	Procedimento                            *Procedimento             `xml:"procedimento"`
	DenteRegiao                             *DenteRegiao              `xml:"denteRegiao"`
	DenteFace                               string                    `xml:"denteFace"`
	OcorrenciasProcedimentoItemAssistencial *OcorrenciaGrupoElementos `xml:"ocorrenciasProcedimentoItemAssistencial"`
	DetalhamentoPacote                      *DetalhamentoPacote       `xml:"detalhamentoPacote"`
}

// ItensLancamento ...
type ItensLancamento struct {
	XMLName                      xml.Name                        `xml:"itensLancamento"`
	ProcedimentoItemAssistencial []*ProcedimentoItemAssistencial `xml:"procedimentoItemAssistencial"`
}

// Lancamento ...
type Lancamento struct {
	XMLName               xml.Name                  `xml:"lancamento"`
	DataProcessamento     string                    `xml:"dataProcessamento"`
	OcorrenciasLancamento *OcorrenciaGrupoElementos `xml:"ocorrenciasLancamento"`
	ItensLancamento       *ItensLancamento          `xml:"itensLancamento"`
}

// LancamentosCompetencia ...
type LancamentosCompetencia struct {
	XMLName    xml.Name      `xml:"lancamentosCompetencia"`
	Lancamento []*Lancamento `xml:"lancamento"`
}

// GuiaAtendimento ...
type GuiaAtendimento struct {
	XMLName                   xml.Name                   `xml:"guiaAtendimento"`
	ContratadoExecutante      *ContratadoExecutante      `xml:"contratadoExecutante"`
	NumeroGuiaPrestador       string                     `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora       string                     `xml:"numeroGuiaOperadora"`
	IdentificadorReembolso    string                     `xml:"identificadorReembolso"`
	LancamentosRegistradosANS *LancamentosRegistradosANS `xml:"lancamentosRegistradosANS"`
	LancamentosCompetencia    *LancamentosCompetencia    `xml:"lancamentosCompetencia"`
}

// MsgControleQualidade ...
type MsgControleQualidade struct {
	XMLName         xml.Name           `xml:"msgControleQualidade"`
	GuiaAtendimento []*GuiaAtendimento `xml:"guiaAtendimento"`
}

// Epilogo ...
type Epilogo struct {
	XMLName xml.Name `xml:"epilogo"`
	Hash    string   `xml:"hash"`
}

// Ocorrencia ...
type Ocorrencia struct {
	XMLName            xml.Name `xml:"ocorrencia"`
	IdentificadorCampo string   `xml:"identificadorCampo"`
	ConteudoCampo      string   `xml:"conteudoCampo"`
	CodigoErro         string   `xml:"codigoErro"`
}

// OcorrenciaGrupoElementos ...
type OcorrenciaGrupoElementos struct {
	XMLName    xml.Name      `xml:"ocorrenciaGrupoElementos"`
	Ocorrencia []*Ocorrencia `xml:"ocorrencia"`
}
