// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// Guias ...
type Guias struct {
	XMLName xml.Name `xml:"guias"`
	*Ctguias
}

// CtloteGuias ...
type CtloteGuias struct {
	XMLName    xml.Name `xml:"ct_loteGuias"`
	NumeroLote int      `xml:"numeroLote"`
	Guias      *Guias   `xml:"guias"`
}

// GuiaFaturamento ...
type GuiaFaturamento struct {
	XMLName                 xml.Name                     `xml:"guiaFaturamento"`
	GuiaConsulta            []*CtguiaConsulta            `xml:"guiaConsulta"`
	GuiaSPSADT              []*CtguiaSPSADT              `xml:"guiaSP_SADT"`
	GuiaResumoInternacao    []*CtguiaResumoInternacao    `xml:"guiaResumoInternacao"`
	GuiaHonorarioIndividual []*CtguiaHonorarioIndividual `xml:"guiaHonorarioIndividual"`
	GuiaOdontologia         []*CtguiaOdontologia         `xml:"guiaOdontologia"`
}

// GuiaRevisaoGlosa ...
type GuiaRevisaoGlosa struct {
	XMLName                               xml.Name                                      `xml:"guiaRevisaoGlosa"`
	GuiaConsultaReapresentacao            []*CtguiaConsultaReapresentacao               `xml:"guiaConsultaReapresentacao"`
	GuiaSPSADTReapresentacao              []*CtguiaSPSADTReapresentacao                 `xml:"guiaSP_SADTReapresentacao"`
	GuiaResumoInternacaoReapresentacao    []*CtguiaResumoInternacaoReapresentacao       `xml:"guiaResumoInternacaoReapresentacao"`
	GuiaHonorarioIndividualReapresentacao []*CtguiaHonorarioIndividualReapresentacao    `xml:"guiaHonorarioIndividualReapresentacao"`
	GuiaOdontologiaReapresentacao         []*CtguiaTratamentoOdontologicoReapresentacao `xml:"guiaOdontologiaReapresentacao"`
}

// Ctguias ...
type Ctguias struct {
	XMLName          xml.Name          `xml:"ct_guias"`
	GuiaFaturamento  *GuiaFaturamento  `xml:"guiaFaturamento"`
	GuiaRevisaoGlosa *GuiaRevisaoGlosa `xml:"guiaRevisaoGlosa"`
}

// ContratadoExecutante ...
type ContratadoExecutante struct {
	XMLName                   xml.Name                  `xml:"contratadoExecutante"`
	IdentificacaoProfissional *CtprofissionalExecutante `xml:"identificacaoProfissional"`
	PosicaoProfissional       string                    `xml:"posicaoProfissional"`
	TipoAcomodacao            string                    `xml:"tipoAcomodacao"`
	*Ctcontratado
}

// ProcedimentosExamesRealizados ...
type ProcedimentosExamesRealizados struct {
	XMLName             xml.Name `xml:"procedimentosExamesRealizados"`
	TotalGeralHonorario float64  `xml:"totalGeralHonorario"`
	*CtprocedimentosRealizados
}

// CtguiaHonorarioIndividual ...
type CtguiaHonorarioIndividual struct {
	XMLName                              xml.Name                       `xml:"ct_guiaHonorarioIndividual"`
	IdentificacaoGuiaHonorarioIndividual *CtcabecalhoGuia               `xml:"identificacaoGuiaHonorarioIndividual"`
	NumeroGuiaPrincipal                  string                         `xml:"numeroGuiaPrincipal"`
	DadosBeneficiario                    *Ctbeneficiario                `xml:"dadosBeneficiario"`
	Contratado                           *Ctcontratado                  `xml:"contratado"`
	ContratadoExecutante                 *ContratadoExecutante          `xml:"contratadoExecutante"`
	ProcedimentosExamesRealizados        *ProcedimentosExamesRealizados `xml:"procedimentosExamesRealizados"`
	Observacao                           string                         `xml:"observacao"`
}

// CtguiaHonorarioIndividualReapresentacao ...
type CtguiaHonorarioIndividualReapresentacao struct {
	XMLName                              xml.Name                       `xml:"ct_guiaHonorarioIndividualReapresentacao"`
	IdentificacaoGuiaHonorarioIndividual *CtcabecalhoGuia               `xml:"identificacaoGuiaHonorarioIndividual"`
	NumeroGuiaPrincipal                  string                         `xml:"numeroGuiaPrincipal"`
	DadosBeneficiario                    *Ctbeneficiario                `xml:"dadosBeneficiario"`
	Contratado                           *Ctcontratado                  `xml:"contratado"`
	ContratadoExecutante                 *ContratadoExecutante          `xml:"contratadoExecutante"`
	ProcedimentosExamesRealizados        *ProcedimentosExamesRealizados `xml:"procedimentosExamesRealizados"`
	Observacao                           string                         `xml:"observacao"`
}

// HipoteseDiagnostica ...
type HipoteseDiagnostica struct {
	XMLName               xml.Name                   `xml:"hipoteseDiagnostica"`
	DiagnosticoSecundario *CtdiagnosticosSecundarios `xml:"diagnosticoSecundario"`
	*CtdiagnosticoAtendimento
}

// DadosAtendimento ...
type DadosAtendimento struct {
	XMLName xml.Name `xml:"dadosAtendimento"`
	*CtatendimentoConsulta
}

// CtguiaConsulta ...
type CtguiaConsulta struct {
	XMLName                xml.Name                     `xml:"ct_guiaConsulta"`
	IdentificacaoGuia      *CtcabecalhoGuia             `xml:"identificacaoGuia"`
	Beneficiario           *Ctbeneficiario              `xml:"beneficiario"`
	DadosContratado        *Ctcontratado                `xml:"dadosContratado"`
	ProfissionalExecutante *CtidentificacaoProfissional `xml:"profissionalExecutante"`
	HipoteseDiagnostica    *HipoteseDiagnostica         `xml:"hipoteseDiagnostica"`
	DadosAtendimento       *DadosAtendimento            `xml:"dadosAtendimento"`
	Observacao             string                       `xml:"observacao"`
}

// CtguiaConsultaReapresentacao ...
type CtguiaConsultaReapresentacao struct {
	XMLName                xml.Name                     `xml:"ct_guiaConsultaReapresentacao"`
	IdentificacaoGuia      *CtcabecalhoGuia             `xml:"identificacaoGuia"`
	Beneficiario           *Ctbeneficiario              `xml:"beneficiario"`
	DadosContratado        *Ctcontratado                `xml:"dadosContratado"`
	ProfissionalExecutante *CtidentificacaoProfissional `xml:"profissionalExecutante"`
	HipoteseDiagnostica    *CtdiagnosticoAtendimento    `xml:"hipoteseDiagnostica"`
	DadosAtendimento       *CtatendimentoConsultaReapr  `xml:"dadosAtendimento"`
	Observacao             string                       `xml:"observacao"`
}

// DadosBeneficiario ...
type DadosBeneficiario struct {
	XMLName        xml.Name `xml:"dadosBeneficiario"`
	NomeEmpresa    string   `xml:"nomeEmpresa"`
	NumeroTelefone string   `xml:"numeroTelefone"`
	NomeTitular    string   `xml:"nomeTitular"`
	*Ctbeneficiario
}

// DadosContratado ...
type DadosContratado struct {
	XMLName              xml.Name                `xml:"dadosContratado"`
	ConselhoProfissional *CtconselhoProfissional `xml:"conselhoProfissional"`
	*Ctcontratado
}

// DadosContratadoExecutante ...
type DadosContratadoExecutante struct {
	XMLName         xml.Name                  `xml:"dadosContratadoExecutante"`
	DadosContratado *DadosContratado          `xml:"dadosContratado"`
	DadosExecutante *CtprofissionalExecutante `xml:"dadosExecutante"`
}

// ProcedimentoExecutado ...
type ProcedimentoExecutado struct {
	XMLName        xml.Name `xml:"procedimentoExecutado"`
	DataRealizacao string   `xml:"dataRealizacao"`
	*CtprocedimentoOdontologia
}

// ProcedimentosExecutados ...
type ProcedimentosExecutados struct {
	XMLName                     xml.Name                 `xml:"procedimentosExecutados"`
	ProcedimentoExecutado       []*ProcedimentoExecutado `xml:"procedimentoExecutado"`
	QuantidadeTotalUS           float64                  `xml:"quantidadeTotalUS"`
	ValorTotal                  float64                  `xml:"valorTotal"`
	TotalFranquiaCoparticipacao float64                  `xml:"totalFranquiaCoparticipacao"`
}

// CtguiaOdontologia ...
type CtguiaOdontologia struct {
	XMLName                   xml.Name                   `xml:"ct_guiaOdontologia"`
	CabecalhoGuia             *CtcabecalhoGuiaOdonto     `xml:"cabecalhoGuia"`
	DadosBeneficiario         *DadosBeneficiario         `xml:"dadosBeneficiario"`
	DadosContratadoExecutante *DadosContratadoExecutante `xml:"dadosContratadoExecutante"`
	ProcedimentosExecutados   *ProcedimentosExecutados   `xml:"procedimentosExecutados"`
	OutrasDespesas            *CtoutrasDespesas          `xml:"outrasDespesas"`
	DadosAtendimento          *CtatendimentoOdontologia  `xml:"dadosAtendimento"`
	TipoFaturamento           string                     `xml:"tipoFaturamento"`
	Observacao                string                     `xml:"observacao"`
}

// CtguiaResumoInternacao ...
type CtguiaResumoInternacao struct {
	XMLName                     xml.Name                       `xml:"ct_guiaResumoInternacao"`
	IdentificacaoGuiaInternacao *CtcabecalhoGuia               `xml:"identificacaoGuiaInternacao"`
	NumeroGuiaSolicitacao       string                         `xml:"numeroGuiaSolicitacao"`
	DadosBeneficiario           *Ctbeneficiario                `xml:"dadosBeneficiario"`
	IdentificacaoExecutante     *Ctcontratado                  `xml:"identificacaoExecutante"`
	DadosAutorizacao            *CtautorizacaoGuia             `xml:"dadosAutorizacao"`
	CaraterInternacao           string                         `xml:"caraterInternacao"`
	Acomodacao                  string                         `xml:"acomodacao"`
	DataHoraInternacao          string                         `xml:"dataHoraInternacao"`
	DataHoraSaidaInternacao     string                         `xml:"dataHoraSaidaInternacao"`
	TipoInternacao              string                         `xml:"tipoInternacao"`
	RegimeInternacao            string                         `xml:"regimeInternacao"`
	InternacaoObstetrica        *CtinternacaoObstetrica        `xml:"internacaoObstetrica"`
	ObitoNeonatal               *CtobitoNeonatal               `xml:"obitoNeonatal"`
	DiagnosticosSaidaInternacao *CtdiagnosticoSaidaInternacao  `xml:"diagnosticosSaidaInternacao"`
	ProcedimentosRealizados     *CtprocedimentoRealizadoEquipe `xml:"procedimentosRealizados"`
	OPMUtilizadas               *CtOPMUtilizada                `xml:"OPMUtilizadas"`
	OutrasDespesas              *CtoutrasDespesas              `xml:"outrasDespesas"`
	TipoFaturamento             string                         `xml:"tipoFaturamento"`
	ValorTotal                  *CtvalorTotalServicos          `xml:"valorTotal"`
	Observacao                  string                         `xml:"observacao"`
}

// CtguiaResumoInternacaoReapresentacao ...
type CtguiaResumoInternacaoReapresentacao struct {
	XMLName                     xml.Name                      `xml:"ct_guiaResumoInternacaoReapresentacao"`
	IdentificacaoGuiaInternacao *CtcabecalhoGuia              `xml:"identificacaoGuiaInternacao"`
	NumeroGuiaSolicitacao       string                        `xml:"numeroGuiaSolicitacao"`
	DadosBeneficiario           *Ctbeneficiario               `xml:"dadosBeneficiario"`
	IdentificacaoExecutante     *Ctcontratado                 `xml:"identificacaoExecutante"`
	DadosAutorizacao            *CtautorizacaoGuia            `xml:"dadosAutorizacao"`
	CaraterInternacao           string                        `xml:"caraterInternacao"`
	Acomodacao                  string                        `xml:"acomodacao"`
	DataHoraInternacao          string                        `xml:"dataHoraInternacao"`
	DataHoraSaidaInternacao     string                        `xml:"dataHoraSaidaInternacao"`
	TipoInternacao              string                        `xml:"tipoInternacao"`
	RegimeInternacao            string                        `xml:"regimeInternacao"`
	InternacaoObstetrica        *CtinternacaoObstetrica       `xml:"internacaoObstetrica"`
	ObitoNeonatal               *CtobitoNeonatal              `xml:"obitoNeonatal"`
	DiagnosticosSaidaInternacao *CtdiagnosticoSaidaInternacao `xml:"diagnosticosSaidaInternacao"`
	ProcedimentosRealizados     *CtprocedimentoRevisao        `xml:"procedimentosRealizados"`
	OPMUtilizadas               *CtOPMUtilizadasRevisao       `xml:"OPMUtilizadas"`
	OutrasDespesas              *CtoutrasDespesasRevisao      `xml:"outrasDespesas"`
	TipoFaturamento             string                        `xml:"tipoFaturamento"`
	ValorTotal                  *CtvalorTotalServicos         `xml:"valorTotal"`
	Observacao                  string                        `xml:"observacao"`
}

// PrestadorSolicitado ...
type PrestadorSolicitado struct {
	XMLName       xml.Name `xml:"prestadorSolicitado"`
	NomePrestador string   `xml:"nomePrestador"`
	*CtidentificacaoPrestador
}

// CtguiaSolicInternacao ...
type CtguiaSolicInternacao struct {
	XMLName                                xml.Name                    `xml:"ct_guiaSolicInternacao"`
	IdentificacaoGuiaSolicitacaoInternacao *CtcabecalhoSolicitacao     `xml:"identificacaoGuiaSolicitacaoInternacao"`
	DadosBeneficiario                      *Ctbeneficiario             `xml:"dadosBeneficiario"`
	DadosSolicitante                       *Ctsolicitante              `xml:"dadosSolicitante"`
	PrestadorSolicitado                    *PrestadorSolicitado        `xml:"prestadorSolicitado"`
	CaraterInternacao                      string                      `xml:"caraterInternacao"`
	TipoInternacao                         string                      `xml:"tipoInternacao"`
	IndicacaoClinica                       string                      `xml:"indicacaoClinica"`
	RegimeInternacao                       string                      `xml:"regimeInternacao"`
	HipotesesDiagnosticas                  *CthipoteseDiagnostica      `xml:"hipotesesDiagnosticas"`
	ProcedimentosExamesSolicitados         *CtprocedimentosSolicitados `xml:"procedimentosExamesSolicitados"`
	OPMsSolicitadas                        *CtOPMSolicitadas           `xml:"OPMsSolicitadas"`
	DiasSolicitados                        int                         `xml:"diasSolicitados"`
	DataProvavelAdmisHosp                  string                      `xml:"dataProvavelAdmisHosp"`
	Observacao                             string                      `xml:"observacao"`
}

// DadosExecutante ...
type DadosExecutante struct {
	XMLName xml.Name `xml:"dadosExecutante"`
	*CtprofissionalExecutante
}

// DadosSolicitante ...
type DadosSolicitante struct {
	XMLName         xml.Name         `xml:"dadosSolicitante"`
	DadosContratado *DadosContratado `xml:"dadosContratado"`
	DadosExecutante *DadosExecutante `xml:"dadosExecutante"`
}

// PlanoTratamento ...
type PlanoTratamento struct {
	XMLName                xml.Name                     `xml:"planoTratamento"`
	ProcedimentoSolicitado []*CtprocedimentoOdontologia `xml:"procedimentoSolicitado"`
}

// CtguiaSolicitacaoOdonto ...
type CtguiaSolicitacaoOdonto struct {
	XMLName           xml.Name               `xml:"ct_guiaSolicitacaoOdonto"`
	CabecalhoGuia     *CtcabecalhoGuiaOdonto `xml:"cabecalhoGuia"`
	DadosBeneficiario *DadosBeneficiario     `xml:"dadosBeneficiario"`
	DadosSolicitante  *DadosSolicitante      `xml:"dadosSolicitante"`
	SituacaoInicial   *CtsituacaoInicial     `xml:"situacaoInicial"`
	PlanoTratamento   *PlanoTratamento       `xml:"planoTratamento"`
	Observacao        string                 `xml:"observacao"`
}

// CtguiaSolicitacaoProrrogacao ...
type CtguiaSolicitacaoProrrogacao struct {
	XMLName                        xml.Name                    `xml:"ct_guiaSolicitacaoProrrogacao"`
	IdentificacaoProrrogacao       *CtcabecalhoGuia            `xml:"identificacaoProrrogacao"`
	IdentificacaoGuiaReferencia    *CtcabecalhoGuia            `xml:"identificacaoGuiaReferencia"`
	DadosBeneficiario              *Ctbeneficiario             `xml:"dadosBeneficiario"`
	DadosSolicitante               *Ctsolicitante              `xml:"dadosSolicitante"`
	IndicacaoClinica               string                      `xml:"indicacaoClinica"`
	ResponsavelAutorizacao         string                      `xml:"responsavelAutorizacao"`
	ProcedimentosExamesSolicitados *CtprocedimentosSolicitados `xml:"procedimentosExamesSolicitados"`
	Diarias                        *CtdiariaProrrogacao        `xml:"diarias"`
	OPMsSolicitadas                *CtOPMSolicitadas           `xml:"OPMsSolicitadas"`
	Observacao                     string                      `xml:"observacao"`
}

// CtguiaSolicitacaoSPSADT ...
type CtguiaSolicitacaoSPSADT struct {
	XMLName                            xml.Name                    `xml:"ct_guiaSolicitacaoSP_SADT"`
	IdentificacaoGuiaSolicitacaoSADTSP *CtcabecalhoSolicitacao     `xml:"identificacaoGuiaSolicitacaoSADTSP"`
	NumeroGuiaPrincipal                int                         `xml:"numeroGuiaPrincipal"`
	DadosBeneficiario                  *Ctbeneficiario             `xml:"dadosBeneficiario"`
	DadosSolicitante                   *Ctsolicitante              `xml:"dadosSolicitante"`
	CaraterSolicitacao                 string                      `xml:"caraterSolicitacao"`
	DataHoraSolicitacao                string                      `xml:"dataHoraSolicitacao"`
	Diagnostico                        *Ctdiagnostico              `xml:"Diagnostico"`
	IndicacaoClinica                   string                      `xml:"indicacaoClinica"`
	ProcedimentosSolicitados           *CtprocedimentosSolicitados `xml:"procedimentosSolicitados"`
	OpmSolicitada                      *CtOPMSolicitadas           `xml:"opmSolicitada"`
	Observacao                         string                      `xml:"observacao"`
}

// ProfissionalExecutanteCompl ...
type ProfissionalExecutanteCompl struct {
	XMLName                 xml.Name                          `xml:"profissionalExecutanteCompl"`
	CodigoProfissionalCompl *CtidentificacaoProfissionalCompl `xml:"codigoProfissionalCompl"`
	*CtprofissionalExecutante
}

// PrestadorExecutante ...
type PrestadorExecutante struct {
	XMLName                     xml.Name                     `xml:"prestadorExecutante"`
	ProfissionalExecutanteCompl *ProfissionalExecutanteCompl `xml:"profissionalExecutanteCompl"`
	*Ctcontratado
}

// CtguiaSPSADT ...
type CtguiaSPSADT struct {
	XMLName                 xml.Name                       `xml:"ct_guiaSP_SADT"`
	IdentificacaoGuiaSADTSP *CtcabecalhoGuia               `xml:"identificacaoGuiaSADTSP"`
	NumeroGuiaPrincipal     string                         `xml:"numeroGuiaPrincipal"`
	DadosAutorizacao        *CtautorizacaoGuia             `xml:"dadosAutorizacao"`
	DadosBeneficiario       *Ctbeneficiario                `xml:"dadosBeneficiario"`
	DadosSolicitante        *Ctsolicitante                 `xml:"dadosSolicitante"`
	PrestadorExecutante     *PrestadorExecutante           `xml:"prestadorExecutante"`
	IndicacaoClinica        string                         `xml:"indicacaoClinica"`
	CaraterAtendimento      string                         `xml:"caraterAtendimento"`
	DataHoraAtendimento     string                         `xml:"dataHoraAtendimento"`
	DiagnosticoAtendimento  *CtdiagnosticoAtendimento      `xml:"diagnosticoAtendimento"`
	TipoSaida               string                         `xml:"tipoSaida"`
	TipoAtendimento         string                         `xml:"tipoAtendimento"`
	ProcedimentosRealizados *CtprocedimentoRealizadoEquipe `xml:"procedimentosRealizados"`
	OutrasDespesas          *CtoutrasDespesas              `xml:"outrasDespesas"`
	OPMUtilizada            *CtOPMUtilizada                `xml:"OPMUtilizada"`
	ValorTotal              *CtvalorTotalServicos          `xml:"valorTotal"`
	Observacao              string                         `xml:"observacao"`
}

// CtguiaSPSADTReapresentacao ...
type CtguiaSPSADTReapresentacao struct {
	XMLName                 xml.Name                  `xml:"ct_guiaSP_SADTReapresentacao"`
	IdentificacaoGuiaSADTSP *CtcabecalhoGuia          `xml:"identificacaoGuiaSADTSP"`
	NumeroGuiaPrincipal     string                    `xml:"numeroGuiaPrincipal"`
	DadosAutorizacao        *CtautorizacaoGuia        `xml:"dadosAutorizacao"`
	DadosBeneficiario       *Ctbeneficiario           `xml:"dadosBeneficiario"`
	DadosSolicitante        *Ctsolicitante            `xml:"dadosSolicitante"`
	PrestadorExecutante     *PrestadorExecutante      `xml:"prestadorExecutante"`
	IndicacaoClinica        string                    `xml:"indicacaoClinica"`
	CaraterAtendimento      string                    `xml:"caraterAtendimento"`
	DataHoraAtendimento     string                    `xml:"dataHoraAtendimento"`
	DiagnosticoGuia         *CtdiagnosticoAtendimento `xml:"diagnosticoGuia"`
	TipoSaida               string                    `xml:"tipoSaida"`
	TipoAtendimento         string                    `xml:"tipoAtendimento"`
	ProcedimentosRealizados *CtprocedimentoRevisao    `xml:"procedimentosRealizados"`
	OutrasDespesas          *CtoutrasDespesasRevisao  `xml:"outrasDespesas"`
	OPMUtilizada            *CtOPMUtilizadasRevisao   `xml:"OPMUtilizada"`
	ValorTotal              *CtvalorTotalServicos     `xml:"valorTotal"`
	Observacao              string                    `xml:"observacao"`
}

// CtguiaTratamentoOdontologicoReapresentacao ...
type CtguiaTratamentoOdontologicoReapresentacao struct {
	XMLName                   xml.Name                   `xml:"ct_guiaTratamentoOdontologicoReapresentacao"`
	CabecalhoGuia             *CtcabecalhoGuiaOdonto     `xml:"cabecalhoGuia"`
	DadosBeneficiario         *DadosBeneficiario         `xml:"dadosBeneficiario"`
	DadosContratadoExecutante *DadosContratadoExecutante `xml:"dadosContratadoExecutante"`
	OutrasDespesas            *CtoutrasDespesas          `xml:"outrasDespesas"`
	DadosAtendimento          *CtatendimentoOdontologia  `xml:"dadosAtendimento"`
	ProcedimentosExecutados   *ProcedimentosExecutados   `xml:"procedimentosExecutados"`
	TipoFaturamento           string                     `xml:"tipoFaturamento"`
	Observacao                string                     `xml:"observacao"`
}
