// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// WsloteAnexo ...
type WsloteAnexo struct {
	XMLName   xml.Name            `xml:"ws_loteAnexo"`
	Cabecalho *CabecalhoTransacao `xml:"cabecalho"`
	LoteAnexo *CtloteAnexo        `xml:"loteAnexo"`
	Hash      string              `xml:"hash"`
}

// WsprotocoloRecebimentoAnexo ...
type WsprotocoloRecebimentoAnexo struct {
	XMLName              xml.Name                     `xml:"ws_protocoloRecebimentoAnexo"`
	Cabecalho            *CabecalhoTransacao          `xml:"cabecalho"`
	ProtocoloRecebimento *CtprotocoloRecebimentoAnexo `xml:"protocoloRecebimento"`
	Hash                 string                       `xml:"hash"`
}

// LoteAnexo ...
type LoteAnexo *WsloteAnexo

// ProtocoloRecebimento ...
type ProtocoloRecebimento *WsprotocoloRecebimentoAnexo

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// VersaoInvalida ...
type VersaoInvalida string

// HashInvalido ...
type HashInvalido string
