// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// WsloteGuias ...
type WsloteGuias struct {
	XMLName   xml.Name            `xml:"ws_loteGuias"`
	Cabecalho *CabecalhoTransacao `xml:"cabecalho"`
	LoteGuias *CtloteGuias        `xml:"loteGuias"`
	Hash      string              `xml:"hash"`
}

// WsprotocoloRecebimento ...
type WsprotocoloRecebimento struct {
	XMLName              xml.Name                `xml:"ws_protocoloRecebimento"`
	Cabecalho            *CabecalhoTransacao     `xml:"cabecalho"`
	ProtocoloRecebimento *CtprotocoloRecebimento `xml:"protocoloRecebimento"`
	Hash                 string                  `xml:"hash"`
}

// LoteGuias ...
type LoteGuias *WsloteGuias

// ProtocoloRecebimento ...
type ProtocoloRecebimento *WsprotocoloRecebimento

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// VersaoInvalida ...
type VersaoInvalida string

// HashInvalido ...
type HashInvalido string
