// Code generated by xgen. DO NOT EDIT.

package v4_01_00

// MensagemTISSString ...
type MensagemTISSString string

// RespostaTISSString ...
type RespostaTISSString string

// SintaxeTISSInvalida ...
type SintaxeTISSInvalida string

// MensagemTISSInesperada ...
type MensagemTISSInesperada string

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// HashInvalido ...
type HashInvalido string
