// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// TissTransmiteMensagemZIPOperation ...
type TissTransmiteMensagemZIPOperation struct {
	XMLName         xml.Name           `xml:"tissTransmiteMensagemZIP_Operation"`
	MensagemTissZIP *WsMensagemTissZIP `xml:"MensagemTissZIP"`
}

// WsMensagemTissZIP ...
type WsMensagemTissZIP struct {
	XMLName         xml.Name         `xml:"ws_MensagemTissZIP"`
	MensagemTissZIP string           `xml:"MensagemTissZIP"`
	TipoMensagem    *SttipoTransacao `xml:"TipoMensagem"`
}

// TissTransmiteMensagemZIPOperationResponse ...
type TissTransmiteMensagemZIPOperationResponse struct {
	XMLName                                 xml.Name                   `xml:"tissTransmiteMensagemZIP_OperationResponse"`
	TissTransmiteMensagemZIPOperationResult *WsRespostaMensagemTissZIP `xml:"tissTransmiteMensagemZIP_OperationResult"`
}

// WsRespostaMensagemTissZIP ...
type WsRespostaMensagemTissZIP struct {
	XMLName                 xml.Name         `xml:"ws_RespostaMensagemTissZIP"`
	RespostaMensagemTissZIP string           `xml:"RespostaMensagemTissZIP"`
	RespostaTipoMensagem    *SttipoTransacao `xml:"RespostaTipoMensagem"`
}

// SintaxeTISSInvalida ...
type SintaxeTISSInvalida string

// MensagemTISSInesperada ...
type MensagemTISSInesperada string

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// HashInvalido ...
type HashInvalido string
