// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// WscomunicacaoBeneficiario ...
type WscomunicacaoBeneficiario struct {
	XMLName                 xml.Name                   `xml:"ws_comunicacaoBeneficiario"`
	Cabecalho               *CabecalhoTransacao        `xml:"cabecalho"`
	ComunicacaoBeneficiario *CtcomunicacaoBeneficiario `xml:"comunicacaoBeneficiario"`
	Hash                    string                     `xml:"hash"`
}

// WsreciboComunicacao ...
type WsreciboComunicacao struct {
	XMLName           xml.Name                         `xml:"ws_reciboComunicacao"`
	Cabecalho         *CabecalhoTransacao              `xml:"cabecalho"`
	ReciboComunicacao *CtreciboComunicacaoBeneficiario `xml:"reciboComunicacao"`
	Hash              string                           `xml:"hash"`
}

// ComunicacaoBeneficiario ...
type ComunicacaoBeneficiario *WscomunicacaoBeneficiario

// ReciboComunicacao ...
type ReciboComunicacao *WsreciboComunicacao

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// VersaoInvalida ...
type VersaoInvalida string

// HashInvalido ...
type HashInvalido string
