// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// CancelaGuiaWS is Prestador solicita cancelamento de guia
type CancelaGuiaWS struct {
	XMLName     xml.Name            `xml:"cancelaGuiaWS"`
	Cabecalho   *CabecalhoTransacao `xml:"cabecalho"`
	CancelaGuia *CtguiaCancelamento `xml:"cancelaGuia"`
	Hash        string              `xml:"hash"`
	Signature   *Signature          `xml:"Signature"`
}

// ReciboCancelaGuiaWS is Operadora responde a solicitação de cancelamento de guia
type ReciboCancelaGuiaWS struct {
	XMLName           xml.Name             `xml:"reciboCancelaGuiaWS"`
	Cabecalho         *CabecalhoTransacao  `xml:"cabecalho"`
	ReciboCancelaGuia *CtreciboCancelaGuia `xml:"reciboCancelaGuia"`
	Hash              string               `xml:"hash"`
	Signature         *Signature           `xml:"Signature"`
}

// ComunicacaoBeneficiarioWS is Prestador envia informação sobre internação/alta de beneficiário
type ComunicacaoBeneficiarioWS struct {
	XMLName                 xml.Name                    `xml:"comunicacaoBeneficiarioWS"`
	Cabecalho               *CabecalhoTransacao         `xml:"cabecalho"`
	ComunicacaoBeneficiario *CtmbeneficiarioComunicacao `xml:"comunicacaoBeneficiario"`
	Hash                    string                      `xml:"hash"`
	Signature               *Signature                  `xml:"Signature"`
}

// ReciboComunicacaoWS is Operadora responde a informação de internação/alta de beneficiário
type ReciboComunicacaoWS struct {
	XMLName           xml.Name             `xml:"reciboComunicacaoWS"`
	Cabecalho         *CabecalhoTransacao  `xml:"cabecalho"`
	ReciboComunicacao *CtreciboComunicacao `xml:"reciboComunicacao"`
	Hash              string               `xml:"hash"`
	Signature         *Signature           `xml:"Signature"`
}

// LoteGuiasWS is Prestador envia lote de guias a operadora
type LoteGuiasWS struct {
	XMLName   xml.Name            `xml:"loteGuiasWS"`
	Cabecalho *CabecalhoTransacao `xml:"cabecalho"`
	LoteGuias *CtmguiaLote        `xml:"loteGuias"`
	Hash      string              `xml:"hash"`
	Signature *Signature          `xml:"Signature"`
}

// ProtocoloRecebimentoWS is Operadora envia protocolo de recebimento das guias
type ProtocoloRecebimentoWS struct {
	XMLName         xml.Name            `xml:"protocoloRecebimentoWS"`
	Cabecalho       *CabecalhoTransacao `xml:"cabecalho"`
	RecebimentoLote *CtrecebimentoLote  `xml:"recebimentoLote"`
	Hash            string              `xml:"hash"`
	Signature       *Signature          `xml:"Signature"`
}

// LoteRecursoGlosaWS is Prestador envia lote com recurso de glosa
type LoteRecursoGlosaWS struct {
	XMLName     xml.Name            `xml:"loteRecursoGlosaWS"`
	Cabecalho   *CabecalhoTransacao `xml:"cabecalho"`
	LoteRecurso *CtguiaRecursoLote  `xml:"loteRecurso"`
	Hash        string              `xml:"hash"`
	Signature   *Signature          `xml:"Signature"`
}

// ProtocoloRecebimentoRecursoWS is Operadora envia protocolo de recebimento de recurso de glosa
type ProtocoloRecebimentoRecursoWS struct {
	XMLName            xml.Name              `xml:"protocoloRecebimentoRecursoWS"`
	Cabecalho          *CabecalhoTransacao   `xml:"cabecalho"`
	RecebimentoRecurso *CtrecebimentoRecurso `xml:"recebimentoRecurso"`
	Hash               string                `xml:"hash"`
	Signature          *Signature            `xml:"Signature"`
}

// SolicitacaoDemonstrativoRetornoWS is Prestador solicita demonstrativo de retorno de pagamentos
type SolicitacaoDemonstrativoRetornoWS struct {
	XMLName                         xml.Name                    `xml:"solicitacaoDemonstrativoRetornoWS"`
	Cabecalho                       *CabecalhoTransacao         `xml:"cabecalho"`
	SolicitacaoDemonstrativoRetorno *CtdemonstrativoSolicitacao `xml:"solicitacaoDemonstrativoRetorno"`
	Hash                            string                      `xml:"hash"`
	Signature                       *Signature                  `xml:"Signature"`
}

// DemonstrativoRetornoWS is Operadora envia demonstrativos de pagamento (até 30)
type DemonstrativoRetornoWS struct {
	XMLName              xml.Name                `xml:"demonstrativoRetornoWS"`
	Cabecalho            *CabecalhoTransacao     `xml:"cabecalho"`
	DemonstrativoRetorno *CtdemonstrativoRetorno `xml:"demonstrativoRetorno"`
	Hash                 string                  `xml:"hash"`
	Signature            *Signature              `xml:"Signature"`
}

// SolicitacaoProcedimentoWS is Prestador solicita autorização de procedimento (SpSADT, Internação ou prorrogação de internação)
type SolicitacaoProcedimentoWS struct {
	XMLName                 xml.Name                   `xml:"solicitacaoProcedimentoWS"`
	Cabecalho               *CabecalhoTransacao        `xml:"cabecalho"`
	SolicitacaoProcedimento *CtsolicitacaoProcedimento `xml:"solicitacaoProcedimento"`
	Hash                    string                     `xml:"hash"`
	Signature               *Signature                 `xml:"Signature"`
}

// AutorizacaoProcedimentoWS is Operadora responde a autorização de procedimento(SpSadt, internação ou prorrogação)
type AutorizacaoProcedimentoWS struct {
	XMLName                 xml.Name               `xml:"autorizacaoProcedimentoWS"`
	Cabecalho               *CabecalhoTransacao    `xml:"cabecalho"`
	AutorizacaoProcedimento *CtsituacaoAutorizacao `xml:"autorizacaoProcedimento"`
	Hash                    string                 `xml:"hash"`
	Signature               *Signature             `xml:"Signature"`
}

// SolicitacaoStatusAutorizacaoWS is Prestador solicita status de pedido de autorização
type SolicitacaoStatusAutorizacaoWS struct {
	XMLName                      xml.Name                     `xml:"solicitacaoStatusAutorizacaoWS"`
	Cabecalho                    *CabecalhoTransacao          `xml:"cabecalho"`
	SolicitacaoStatusAutorizacao *CtautorizacaoSolicitaStatus `xml:"solicitacaoStatusAutorizacao"`
	Hash                         string                       `xml:"hash"`
	Signature                    *Signature                   `xml:"Signature"`
}

// SituacaoAutorizacaoWS is Operadora responde status de autorização
type SituacaoAutorizacaoWS struct {
	XMLName             xml.Name               `xml:"situacaoAutorizacaoWS"`
	Cabecalho           *CabecalhoTransacao    `xml:"cabecalho"`
	SituacaoAutorizacao *CtsituacaoAutorizacao `xml:"situacaoAutorizacao"`
	Hash                string                 `xml:"hash"`
	Signature           *Signature             `xml:"Signature"`
}

// SolicitacaoStatusProtocoloWS is Prestador solicita status de protocolo(s)
type SolicitacaoStatusProtocoloWS struct {
	XMLName                    xml.Name                      `xml:"solicitacaoStatusProtocoloWS"`
	Cabecalho                  *CabecalhoTransacao           `xml:"cabecalho"`
	SolicitacaoStatusProtocolo *CtprotocoloSolicitacaoStatus `xml:"solicitacaoStatusProtocolo"`
	Hash                       string                        `xml:"hash"`
	Signature                  *Signature                    `xml:"Signature"`
}

// SituacaoProtocoloWS is Operadora responde situação do(s) protocolo(s)
type SituacaoProtocoloWS struct {
	XMLName           xml.Name             `xml:"situacaoProtocoloWS"`
	Cabecalho         *CabecalhoTransacao  `xml:"cabecalho"`
	SituacaoProtocolo *CtsituacaoProtocolo `xml:"situacaoProtocolo"`
	Hash              string               `xml:"hash"`
	Signature         *Signature           `xml:"Signature"`
}

// PedidoElegibilidadeWS is Prestador solicita elegibilidade do paciente
type PedidoElegibilidadeWS struct {
	XMLName             xml.Name                 `xml:"pedidoElegibilidadeWS"`
	Cabecalho           *CabecalhoTransacao      `xml:"cabecalho"`
	PedidoElegibilidade *CtelegibilidadeVerifica `xml:"pedidoElegibilidade"`
	Hash                string                   `xml:"hash"`
	Signature           *Signature               `xml:"Signature"`
}

// RespostaElegibilidadeWS is Operadora responde sobre a elegibilidade do paciente
type RespostaElegibilidadeWS struct {
	XMLName               xml.Name                 `xml:"respostaElegibilidadeWS"`
	Cabecalho             *CabecalhoTransacao      `xml:"cabecalho"`
	RespostaElegibilidade *CtrespostaElegibilidade `xml:"respostaElegibilidade"`
	Hash                  string                   `xml:"hash"`
	Signatures            *Signature               `xml:"Signatures"`
}

// LoteAnexoWS is Prestador envia solicitação de quimio, radio e opme
type LoteAnexoWS struct {
	XMLName   xml.Name            `xml:"loteAnexoWS"`
	Cabecalho *CabecalhoTransacao `xml:"cabecalho"`
	LoteAnexo *CtanexoLote        `xml:"loteAnexo"`
	Hash      string              `xml:"hash"`
	Signature *Signature          `xml:"Signature"`
}

// LoteAnexo ...
type LoteAnexo struct {
	XMLName                   xml.Name            `xml:"loteAnexo"`
	MensagemErro              *CtmotivoGlosa      `xml:"mensagemErro"`
	ProtocoloRecebimentoAnexo *CtanexoRecebimento `xml:"protocoloRecebimentoAnexo"`
}

// ProtocoloRecebimentoAnexoWS is Operadora envia protocolo de recebimento dos anexos de quimio, radio e opme
type ProtocoloRecebimentoAnexoWS struct {
	XMLName    xml.Name            `xml:"protocoloRecebimentoAnexoWS"`
	Cabecalho  *CabecalhoTransacao `xml:"cabecalho"`
	LoteAnexo  *LoteAnexo          `xml:"loteAnexo"`
	Hash       string              `xml:"hash"`
	Signatures *Signature          `xml:"Signatures"`
}

// SolicitacaoStatusRecursoGlosaWS is Prestador solicita status de protocolo de recurso de glosa
type SolicitacaoStatusRecursoGlosaWS struct {
	XMLName                           xml.Name                      `xml:"solicitacaoStatusRecursoGlosaWS"`
	Cabecalho                         *CabecalhoTransacao           `xml:"cabecalho"`
	SolicitacaoStatusProtocoloRecurso *CtprotocoloSolicitacaoStatus `xml:"solicitacaoStatusProtocoloRecurso"`
	Hash                              string                        `xml:"hash"`
	Signature                         *Signature                    `xml:"Signature"`
}

// SituacaoProtocoloRecursoWS is Operadora responde situação do protocolo de recurso de glosa
type SituacaoProtocoloRecursoWS struct {
	XMLName                  xml.Name            `xml:"situacaoProtocoloRecursoWS"`
	Cabecalho                *CabecalhoTransacao `xml:"cabecalho"`
	SituacaoProtocoloRecurso *CtrespostaGlosa    `xml:"situacaoProtocoloRecurso"`
	Hash                     string              `xml:"hash"`
	Signature                *Signature          `xml:"Signature"`
}

// TissFaultWS ...
type TissFaultWS struct {
	XMLName   xml.Name `xml:"tissFaultWS"`
	TissFault string   `xml:"tissFault"`
}
