// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
	"time"
)

// OperadoraParaANS ...
type OperadoraParaANS struct {
	XMLName                           xml.Name                               `xml:"operadoraParaANS"`
	SemMovimentoInclusao              string                                 `xml:"semMovimentoInclusao"`
	GuiaMonitoramento                 []*CtmonitoramentoGuia                 `xml:"guiaMonitoramento"`
	FornecimentoDiretoMonitoramento   []*CtmonitoramentoFornecimentoDireto   `xml:"fornecimentoDiretoMonitoramento"`
	OutraRemuneracaoMonitoramento     []*CtmonitoramentoOutraRemuneracao     `xml:"outraRemuneracaoMonitoramento"`
	ValorPreestabelecidoMonitoramento []*CtmonitoramentoValorPreestabelecido `xml:"valorPreestabelecidoMonitoramento"`
}

// ArquivoRejeitado ...
type ArquivoRejeitado struct {
	XMLName        xml.Name `xml:"arquivoRejeitado"`
	NomeArquivo    string   `xml:"nomeArquivo"`
	CodigoRejeicao string   `xml:"codigoRejeicao"`
}

// ContratadoExecutante ...
type ContratadoExecutante struct {
	XMLName                 xml.Name `xml:"contratadoExecutante"`
	CNES                    string   `xml:"CNES"`
	IdentificadorExecutante string   `xml:"identificadorExecutante"`
	CodigoCNPJCPF           string   `xml:"codigoCNPJ_CPF"`
}

// ErrosGuia ...
type ErrosGuia struct {
	XMLName            xml.Name `xml:"errosGuia"`
	IdentificadorCampo string   `xml:"identificadorCampo"`
	CodigoErro         string   `xml:"codigoErro"`
}

// Procedimento ...
type Procedimento struct {
	GrupoProcedimento  string `xml:"grupoProcedimento"`
	CodigoProcedimento string `xml:"codigoProcedimento"`
}

// IdentProcedimento ...
type IdentProcedimento struct {
	XMLName      xml.Name      `xml:"identProcedimento"`
	CodigoTabela string        `xml:"codigoTabela"`
	Procedimento *Procedimento `xml:"Procedimento"`
}

// DenteRegiao ...
type DenteRegiao struct {
	XMLName   xml.Name `xml:"denteRegiao"`
	CodDente  string   `xml:"codDente"`
	CodRegiao string   `xml:"codRegiao"`
}

// RelacaoErros ...
type RelacaoErros struct {
	XMLName            xml.Name `xml:"relacaoErros"`
	IdentificadorCampo string   `xml:"identificadorCampo"`
	CodigoErro         string   `xml:"codigoErro"`
}

// ErrosItensGuia ...
type ErrosItensGuia struct {
	XMLName           xml.Name           `xml:"errosItensGuia"`
	IdentProcedimento *IdentProcedimento `xml:"identProcedimento"`
	DenteRegiao       *DenteRegiao       `xml:"denteRegiao"`
	DenteFace         string             `xml:"denteFace"`
	RelacaoErros      []*RelacaoErros    `xml:"relacaoErros"`
}

// GuiaMonitoramento ...
type GuiaMonitoramento struct {
	XMLName                xml.Name              `xml:"guiaMonitoramento"`
	TipoRegistro           string                `xml:"tipoRegistro"`
	ContratadoExecutante   *ContratadoExecutante `xml:"contratadoExecutante"`
	NumeroGuiaPrestador    string                `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora    string                `xml:"numeroGuiaOperadora"`
	IdentificadorReembolso string                `xml:"identificadorReembolso"`
	DataProcessamento      string                `xml:"dataProcessamento"`
	ErrosGuia              []*ErrosGuia          `xml:"errosGuia"`
	ErrosItensGuia         []*ErrosItensGuia     `xml:"errosItensGuia"`
}

// ErrosFornecimentoDireto ...
type ErrosFornecimentoDireto struct {
	XMLName            xml.Name `xml:"errosFornecimentoDireto"`
	IdentificadorCampo string   `xml:"identificadorCampo"`
	CodigoErro         string   `xml:"codigoErro"`
}

// Procedimento2 ...
type Procedimento2 struct {
	XMLName            xml.Name `xml:"procedimento"`
	GrupoProcedimento  string   `xml:"grupoProcedimento"`
	CodigoProcedimento string   `xml:"codigoProcedimento"`
}

// ErrosItensFornecimentoDireto ...
type ErrosItensFornecimentoDireto struct {
	XMLName           xml.Name           `xml:"errosItensFornecimentoDireto"`
	IdentProcedimento *IdentProcedimento `xml:"identProcedimento"`
	RelacaoErros      []*RelacaoErros    `xml:"relacaoErros"`
}

// FornecimentoDiretoMonitoramento ...
type FornecimentoDiretoMonitoramento struct {
	XMLName                         xml.Name                        `xml:"fornecimentoDiretoMonitoramento"`
	TipoRegistro                    string                          `xml:"tipoRegistro"`
	IdentificacaoFornecimentoDireto string                          `xml:"identificacaoFornecimentoDireto"`
	DataFornecimento                string                          `xml:"dataFornecimento"`
	ErrosFornecimentoDireto         []*ErrosFornecimentoDireto      `xml:"errosFornecimentoDireto"`
	ErrosItensFornecimentoDireto    []*ErrosItensFornecimentoDireto `xml:"errosItensFornecimentoDireto"`
}

// DadosRecebedor ...
type DadosRecebedor struct {
	XMLName                xml.Name `xml:"dadosRecebedor"`
	IdentificadorRecebedor string   `xml:"identificadorRecebedor"`
	CodigoCNPJCPF          string   `xml:"codigoCNPJ_CPF"`
}

// ErrosOutraRemuneracao ...
type ErrosOutraRemuneracao struct {
	XMLName            xml.Name `xml:"errosOutraRemuneracao"`
	IdentificadorCampo string   `xml:"identificadorCampo"`
	CodigoErro         string   `xml:"codigoErro"`
}

// OutraRemuneracaoMonitoramento ...
type OutraRemuneracaoMonitoramento struct {
	XMLName               xml.Name                 `xml:"outraRemuneracaoMonitoramento"`
	TipoRegistro          string                   `xml:"tipoRegistro"`
	DataProcessamento     string                   `xml:"dataProcessamento"`
	DadosRecebedor        *DadosRecebedor          `xml:"dadosRecebedor"`
	ErrosOutraRemuneracao []*ErrosOutraRemuneracao `xml:"errosOutraRemuneracao"`
}

// DadosContratadoExecutante ...
type DadosContratadoExecutante struct {
	XMLName                 xml.Name `xml:"dadosContratadoExecutante"`
	CNES                    string   `xml:"CNES"`
	IdentificadorExecutante string   `xml:"identificadorExecutante"`
	CodigoCNPJCPF           string   `xml:"codigoCNPJ_CPF"`
	MunicipioExecutante     string   `xml:"municipioExecutante"`
}

// ErrosValorPreestabelecido ...
type ErrosValorPreestabelecido struct {
	XMLName            xml.Name `xml:"errosValorPreestabelecido"`
	IdentificadorCampo string   `xml:"identificadorCampo"`
	CodigoErro         string   `xml:"codigoErro"`
}

// ValorPreestabelecidoMonitoramento ...
type ValorPreestabelecidoMonitoramento struct {
	XMLName                           xml.Name                     `xml:"valorPreestabelecidoMonitoramento"`
	TipoRegistro                      string                       `xml:"tipoRegistro"`
	CompetenciaCoberturaContratada    string                       `xml:"competenciaCoberturaContratada"`
	DadosContratadoExecutante         *DadosContratadoExecutante   `xml:"dadosContratadoExecutante"`
	RegistroANSOperadoraIntermediaria string                       `xml:"registroANSOperadoraIntermediaria"`
	IdentificacaoValorPreestabelecido string                       `xml:"identificacaoValorPreestabelecido"`
	ErrosValorPreestabelecido         []*ErrosValorPreestabelecido `xml:"errosValorPreestabelecido"`
}

// RegistrosRejeitados ...
type RegistrosRejeitados struct {
	XMLName                           xml.Name                             `xml:"registrosRejeitados"`
	GuiaMonitoramento                 []*GuiaMonitoramento                 `xml:"guiaMonitoramento"`
	FornecimentoDiretoMonitoramento   []*FornecimentoDiretoMonitoramento   `xml:"fornecimentoDiretoMonitoramento"`
	OutraRemuneracaoMonitoramento     []*OutraRemuneracaoMonitoramento     `xml:"outraRemuneracaoMonitoramento"`
	ValorPreestabelecidoMonitoramento []*ValorPreestabelecidoMonitoramento `xml:"valorPreestabelecidoMonitoramento"`
}

// ResumoProcessamentoTotais ...
type ResumoProcessamentoTotais struct {
	XMLName            xml.Name `xml:"resumoProcessamentoTotais"`
	RegistrosIncluidos int      `xml:"registrosIncluidos"`
	RegistrosAlterados int      `xml:"registrosAlterados"`
	RegistrosExcluidos int      `xml:"registrosExcluidos"`
	RegistrosComErros  int      `xml:"registrosComErros"`
}

// ResumoProcessamento ...
type ResumoProcessamento struct {
	XMLName                   xml.Name                   `xml:"resumoProcessamento"`
	NomeArquivo               string                     `xml:"nomeArquivo"`
	RegistrosRejeitados       *RegistrosRejeitados       `xml:"registrosRejeitados"`
	ResumoProcessamentoTotais *ResumoProcessamentoTotais `xml:"resumoProcessamentoTotais"`
	ArquivoProcessadoPelaANS  string                     `xml:"arquivoProcessadoPelaANS"`
}

// AnsParaOperadora ...
type AnsParaOperadora struct {
	XMLName             xml.Name             `xml:"ansParaOperadora"`
	ArquivoRejeitado    *ArquivoRejeitado    `xml:"arquivoRejeitado"`
	ResumoProcessamento *ResumoProcessamento `xml:"resumoProcessamento"`
}

// Mensagem ...
type Mensagem struct {
	OperadoraParaANS *OperadoraParaANS `xml:"operadoraParaANS"`
	AnsParaOperadora *AnsParaOperadora `xml:"ansParaOperadora"`
}

// MensagemEnvioANS ...
type MensagemEnvioANS struct {
	XMLName   xml.Name            `xml:"mensagemEnvioANS"`
	Cabecalho *CabecalhoTransacao `xml:"cabecalho"`
	Mensagem  *Mensagem           `xml:"Mensagem"`
	Epilogo   *Epilogo            `xml:"epilogo"`
}

// IdentBeneficiario ...
type IdentBeneficiario struct {
	XMLName                   xml.Name `xml:"identBeneficiario"`
	NumeroCartaoNacionalSaude string   `xml:"numeroCartaoNacionalSaude"`
	Sexo                      string   `xml:"sexo"`
	DataNascimento            string   `xml:"dataNascimento"`
	MunicipioResidencia       string   `xml:"municipioResidencia"`
}

// DadosBeneficiario ...
type DadosBeneficiario struct {
	XMLName             xml.Name           `xml:"dadosBeneficiario"`
	IdentBeneficiario   *IdentBeneficiario `xml:"identBeneficiario"`
	NumeroRegistroPlano string             `xml:"numeroRegistroPlano"`
}

// DiagnosticosCID10 ...
type DiagnosticosCID10 struct {
	XMLName        xml.Name `xml:"diagnosticosCID10"`
	DiagnosticoCID []string `xml:"diagnosticoCID"`
}

// ValoresGuia ...
type ValoresGuia struct {
	XMLName                     xml.Name `xml:"valoresGuia"`
	ValorTotalInformado         float64  `xml:"valorTotalInformado"`
	ValorProcessado             float64  `xml:"valorProcessado"`
	ValorTotalPagoProcedimentos float64  `xml:"valorTotalPagoProcedimentos"`
	ValorTotalDiarias           float64  `xml:"valorTotalDiarias"`
	ValorTotalTaxas             float64  `xml:"valorTotalTaxas"`
	ValorTotalMateriais         float64  `xml:"valorTotalMateriais"`
	ValorTotalOPME              float64  `xml:"valorTotalOPME"`
	ValorTotalMedicamentos      float64  `xml:"valorTotalMedicamentos"`
	ValorGlosaGuia              float64  `xml:"valorGlosaGuia"`
	ValorPagoGuia               float64  `xml:"valorPagoGuia"`
	ValorPagoFornecedores       float64  `xml:"valorPagoFornecedores"`
	ValorTotalTabelaPropria     float64  `xml:"valorTotalTabelaPropria"`
	ValorTotalCoParticipacao    float64  `xml:"valorTotalCoParticipacao"`
}

// DetalhePacote ...
type DetalhePacote struct {
	XMLName            xml.Name `xml:"detalhePacote"`
	CodigoTabela       string   `xml:"codigoTabela"`
	CodigoProcedimento string   `xml:"codigoProcedimento"`
	Quantidade         float64  `xml:"quantidade"`
}

// Procedimentos ...
type Procedimentos struct {
	XMLName             xml.Name           `xml:"procedimentos"`
	IdentProcedimento   *IdentProcedimento `xml:"identProcedimento"`
	DenteRegiao         *DenteRegiao       `xml:"denteRegiao"`
	DenteFace           string             `xml:"denteFace"`
	QuantidadeInformada float64            `xml:"quantidadeInformada"`
	ValorInformado      float64            `xml:"valorInformado"`
	QuantidadePaga      float64            `xml:"quantidadePaga"`
	ValorPagoProc       float64            `xml:"valorPagoProc"`
	ValorPagoFornecedor float64            `xml:"valorPagoFornecedor"`
	CNPJFornecedor      string             `xml:"CNPJFornecedor"`
	ValorCoParticipacao float64            `xml:"valorCoParticipacao"`
	DetalhePacote       []*DetalhePacote   `xml:"detalhePacote"`
}

// CtmonitoramentoGuia ...
type CtmonitoramentoGuia struct {
	XMLName                               xml.Name                   `xml:"ct_monitoramentoGuia"`
	TipoRegistro                          string                     `xml:"tipoRegistro"`
	VersaoTISSPrestador                   string                     `xml:"versaoTISSPrestador"`
	FormaEnvio                            string                     `xml:"formaEnvio"`
	DadosContratadoExecutante             *DadosContratadoExecutante `xml:"dadosContratadoExecutante"`
	RegistroANSOperadoraIntermediaria     string                     `xml:"registroANSOperadoraIntermediaria"`
	TipoAtendimentoOperadoraIntermediaria string                     `xml:"tipoAtendimentoOperadoraIntermediaria"`
	DadosBeneficiario                     *DadosBeneficiario         `xml:"dadosBeneficiario"`
	TipoEventoAtencao                     string                     `xml:"tipoEventoAtencao"`
	OrigemEventoAtencao                   string                     `xml:"origemEventoAtencao"`
	NumeroGuiaprestador                   string                     `xml:"numeroGuia_prestador"`
	NumeroGuiaoperadora                   string                     `xml:"numeroGuia_operadora"`
	IdentificacaoReembolso                string                     `xml:"identificacaoReembolso"`
	IdentificacaoValorPreestabelecido     string                     `xml:"identificacaoValorPreestabelecido"`
	GuiaSolicitacaoInternacao             string                     `xml:"guiaSolicitacaoInternacao"`
	DataSolicitacao                       string                     `xml:"dataSolicitacao"`
	NumeroGuiaSPSADTPrincipal             string                     `xml:"numeroGuiaSPSADTPrincipal"`
	DataAutorizacao                       string                     `xml:"dataAutorizacao"`
	DataRealizacao                        string                     `xml:"dataRealizacao"`
	DataInicialFaturamento                string                     `xml:"dataInicialFaturamento"`
	DataFimPeriodo                        string                     `xml:"dataFimPeriodo"`
	DataProtocoloCobranca                 string                     `xml:"dataProtocoloCobranca"`
	DataPagamento                         string                     `xml:"dataPagamento"`
	DataProcessamentoGuia                 string                     `xml:"dataProcessamentoGuia"`
	TipoConsulta                          string                     `xml:"tipoConsulta"`
	CboExecutante                         string                     `xml:"cboExecutante"`
	IndicacaoRecemNato                    string                     `xml:"indicacaoRecemNato"`
	IndicacaoAcidente                     string                     `xml:"indicacaoAcidente"`
	CaraterAtendimento                    string                     `xml:"caraterAtendimento"`
	TipoInternacao                        string                     `xml:"tipoInternacao"`
	RegimeInternacao                      string                     `xml:"regimeInternacao"`
	DiagnosticosCID10                     *DiagnosticosCID10         `xml:"diagnosticosCID10"`
	TipoAtendimento                       string                     `xml:"tipoAtendimento"`
	TipoFaturamento                       string                     `xml:"tipoFaturamento"`
	DiariasAcompanhante                   int                        `xml:"diariasAcompanhante"`
	DiariasUTI                            int                        `xml:"diariasUTI"`
	MotivoSaida                           string                     `xml:"motivoSaida"`
	ValoresGuia                           *ValoresGuia               `xml:"valoresGuia"`
	DeclaracaoNascido                     []string                   `xml:"declaracaoNascido"`
	DeclaracaoObito                       []string                   `xml:"declaracaoObito"`
	Procedimentos                         []*Procedimentos           `xml:"procedimentos"`
}

// DadosSemCartao ...
type DadosSemCartao struct {
	XMLName                   xml.Name `xml:"dadosSemCartao"`
	NumeroCartaoNacionalSaude string   `xml:"numeroCartaoNacionalSaude"`
	Sexo                      string   `xml:"sexo"`
	DataNascimento            string   `xml:"dataNascimento"`
	MunicipioResidencia       string   `xml:"municipioResidencia"`
}

// CtmonitoramentoFornecimentoDireto ...
type CtmonitoramentoFornecimentoDireto struct {
	XMLName                         xml.Name           `xml:"ct_monitoramentoFornecimentoDireto"`
	TipoRegistro                    string             `xml:"tipoRegistro"`
	DadosBeneficiario               *DadosBeneficiario `xml:"dadosBeneficiario"`
	IdentificacaoFornecimentoDireto string             `xml:"identificacaoFornecimentoDireto"`
	DataFornecimento                string             `xml:"dataFornecimento"`
	ValorTotalFornecimento          float64            `xml:"valorTotalFornecimento"`
	ValorTotalTabelaPropria         float64            `xml:"valorTotalTabelaPropria"`
	ValorTotalCoParticipacao        float64            `xml:"valorTotalCoParticipacao"`
	Procedimentos                   []*Procedimentos   `xml:"procedimentos"`
}

// CtmonitoramentoOutraRemuneracao ...
type CtmonitoramentoOutraRemuneracao struct {
	XMLName             xml.Name        `xml:"ct_monitoramentoOutraRemuneracao"`
	TipoRegistro        string          `xml:"tipoRegistro"`
	DataProcessamento   string          `xml:"dataProcessamento"`
	DadosRecebedor      *DadosRecebedor `xml:"dadosRecebedor"`
	ValorTotalInformado float64         `xml:"valorTotalInformado"`
	ValorTotalGlosa     float64         `xml:"valorTotalGlosa"`
	ValorTotalPago      float64         `xml:"valorTotalPago"`
}

// DadosPrestador ...
type DadosPrestador struct {
	XMLName                xml.Name `xml:"dadosPrestador"`
	CNES                   string   `xml:"CNES"`
	IdentificadorPrestador string   `xml:"identificadorPrestador"`
	CodigoCNPJCPF          string   `xml:"codigoCNPJ_CPF"`
	MunicipioPrestador     string   `xml:"municipioPrestador"`
}

// CtmonitoramentoValorPreestabelecido ...
type CtmonitoramentoValorPreestabelecido struct {
	XMLName                           xml.Name        `xml:"ct_monitoramentoValorPreestabelecido"`
	TipoRegistro                      string          `xml:"tipoRegistro"`
	CompetenciaCoberturaContratada    string          `xml:"competenciaCoberturaContratada"`
	DadosPrestador                    *DadosPrestador `xml:"dadosPrestador"`
	RegistroANSOperadoraIntermediaria string          `xml:"registroANSOperadoraIntermediaria"`
	IdentificacaoValorPreestabelecido string          `xml:"identificacaoValorPreestabelecido"`
	ValorPreestabelecido              float64         `xml:"valorPreestabelecido"`
}

// Epilogo ...
type Epilogo struct {
	XMLName xml.Name `xml:"epilogo"`
	Hash    string   `xml:"hash"`
}

// IdentificacaoTransacao ...
type IdentificacaoTransacao struct {
	XMLName               xml.Name  `xml:"identificacaoTransacao"`
	TipoTransacao         string    `xml:"tipoTransacao"`
	NumeroLote            string    `xml:"numeroLote"`
	CompetenciaLote       string    `xml:"competenciaLote"`
	DataRegistroTransacao string    `xml:"dataRegistroTransacao"`
	HoraRegistroTransacao time.Time `xml:"horaRegistroTransacao"`
}

// CabecalhoTransacao ...
type CabecalhoTransacao struct {
	XMLName                xml.Name                `xml:"cabecalhoTransacao"`
	IdentificacaoTransacao *IdentificacaoTransacao `xml:"identificacaoTransacao"`
	RegistroANS            string                  `xml:"registroANS"`
	VersaoPadrao           string                  `xml:"versaoPadrao"`
}
