// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// WssolicitacaoStatusAutorizacao ...
type WssolicitacaoStatusAutorizacao struct {
	XMLName                      xml.Name                     `xml:"ws_solicitacaoStatusAutorizacao"`
	Cabecalho                    *CabecalhoTransacao          `xml:"cabecalho"`
	SolicitacaoStatusAutorizacao *CtsolicitaStatusAutorizacao `xml:"solicitacaoStatusAutorizacao"`
	Hash                         string                       `xml:"hash"`
}

// WssituacaoAutorizacao ...
type WssituacaoAutorizacao struct {
	XMLName             xml.Name               `xml:"ws_situacaoAutorizacao"`
	Cabecalho           *CabecalhoTransacao    `xml:"cabecalho"`
	SituacaoAutorizacao *CtsituacaoAutorizacao `xml:"situacaoAutorizacao"`
	Hash                string                 `xml:"hash"`
}

// SolicitacaoStatusAutorizacao ...
type SolicitacaoStatusAutorizacao *WssolicitacaoStatusAutorizacao

// SituacaoAutorizacao ...
type SituacaoAutorizacao *WssituacaoAutorizacao

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// VersaoInvalida ...
type VersaoInvalida string

// HashInvalido ...
type HashInvalido string

// SolicitacaoInexistente ...
type SolicitacaoInexistente string
