// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// WsverificaElegibilidade ...
type WsverificaElegibilidade struct {
	XMLName               xml.Name                 `xml:"ws_verificaElegibilidade"`
	Cabecalho             *CabecalhoTransacao      `xml:"cabecalho"`
	VerificaElegibilidade *CtsolicitaElegibilidade `xml:"verificaElegibilidade"`
	Hash                  string                   `xml:"hash"`
}

// WsrespostaElegibilidade ...
type WsrespostaElegibilidade struct {
	XMLName               xml.Name                `xml:"ws_respostaElegibilidade"`
	Cabecalho             *CabecalhoTransacao     `xml:"cabecalho"`
	RespostaElegibilidade *CtretornoElegibilidade `xml:"respostaElegibilidade"`
	Hash                  string                  `xml:"hash"`
}

// SolicitaElegibilidade ...
type SolicitaElegibilidade *WsverificaElegibilidade

// RetornoElegibilidade ...
type RetornoElegibilidade *WsrespostaElegibilidade

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// VersaoInvalida ...
type VersaoInvalida string

// HashInvalido ...
type HashInvalido string
