// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// IdentificacaoTransacao ...
type IdentificacaoTransacao struct {
	XMLName               xml.Name `xml:"identificacaoTransacao"`
	TipoTransacao         string   `xml:"tipoTransacao"`
	SequencialTransacao   int      `xml:"sequencialTransacao"`
	DataRegistroTransacao string   `xml:"dataRegistroTransacao"`
	HoraRegistroTransacao string   `xml:"horaRegistroTransacao"`
}

// FalhaNegocio ...
type FalhaNegocio struct {
	XMLName    xml.Name `xml:"falhaNegocio"`
	Observacao string   `xml:"observacao"`
	*CtmotivoGlosa
}

// Origem ...
type Origem struct {
	XMLName                    xml.Name                            `xml:"origem"`
	CodigoPrestadorNaOperadora *CtidentificacaoPrestadorExecutante `xml:"codigoPrestadorNaOperadora"`
	RegistroANS                string                              `xml:"registroANS"`
}

// Destino ...
type Destino struct {
	XMLName                    xml.Name                            `xml:"destino"`
	CodigoPrestadorNaOperadora *CtidentificacaoPrestadorExecutante `xml:"codigoPrestadorNaOperadora"`
	RegistroANS                string                              `xml:"registroANS"`
}

// CabecalhoTransacao ...
type CabecalhoTransacao struct {
	XMLName                xml.Name                `xml:"cabecalhoTransacao"`
	IdentificacaoTransacao *IdentificacaoTransacao `xml:"identificacaoTransacao"`
	FalhaNegocio           *FalhaNegocio           `xml:"falhaNegocio"`
	Origem                 *Origem                 `xml:"origem"`
	Destino                *Destino                `xml:"destino"`
	VersaoPadrao           string                  `xml:"versaoPadrao"`
}

// DemonstrativosRetorno ...
type DemonstrativosRetorno struct {
	XMLName                   xml.Name                       `xml:"demonstrativosRetorno"`
	DemonstrativoAnaliseConta []*CtdemonstrativoAnaliseConta `xml:"demonstrativoAnaliseConta"`
	DemonstrativoOdontologia  []*CtdemonstrativoOdontologia  `xml:"demonstrativoOdontologia"`
	DemonstrativoPagamento    []*CtdemonstrativoPagamento    `xml:"demonstrativoPagamento"`
}

// TotalOdonto ...
type TotalOdonto struct {
	XMLName                     xml.Name `xml:"totalOdonto"`
	Totalvalor                  float64  `xml:"totalvalor"`
	TotalFranquiaCoparticipacao float64  `xml:"totalFranquiaCoparticipacao"`
	TotalquantidadeUS           float64  `xml:"totalquantidadeUS"`
}

// DiariaProrrogacaoAutorizada ...
type DiariaProrrogacaoAutorizada struct {
	XMLName                  xml.Name       `xml:"diariaProrrogacaoAutorizada"`
	TipoAcomodacaoAutorizada string         `xml:"tipoAcomodacaoAutorizada"`
	QuantidadeAutorizada     float64        `xml:"quantidadeAutorizada"`
	MotivoGlosa              *CtmotivoGlosa `xml:"motivoGlosa"`
	*CtdiariaProrrogacao
}

// AutorizacaoServico ...
type AutorizacaoServico struct {
	XMLName                     xml.Name                     `xml:"autorizacaoServico"`
	TotalOdonto                 *TotalOdonto                 `xml:"totalOdonto"`
	DiariaProrrogacaoAutorizada *DiariaProrrogacaoAutorizada `xml:"diariaProrrogacaoAutorizada"`
	*CtautorizacaoProcedimento
}

// OperadoraParaPrestador ...
type OperadoraParaPrestador struct {
	XMLName               xml.Name                `xml:"operadoraParaPrestador"`
	ProtocoloRecebimento  *CtprotocoloRecebimento `xml:"protocoloRecebimento"`
	DemonstrativosRetorno *DemonstrativosRetorno  `xml:"demonstrativosRetorno"`
	SituacaoProtocolo     *CtStatusProtocolo      `xml:"situacaoProtocolo"`
	AutorizacaoServico    []*AutorizacaoServico   `xml:"autorizacaoServico"`
	SituacaoAutorizacao   *CtsituacaoAutorizacao  `xml:"situacaoAutorizacao"`
	RespostaElegibilidade *CtretornoElegibilidade `xml:"respostaElegibilidade"`
	ReciboCancelaGuia     *CtreciboCancelaGuia    `xml:"reciboCancelaGuia"`
}

// SolicitacaoProcedimento ...
type SolicitacaoProcedimento struct {
	XMLName                    xml.Name                      `xml:"solicitacaoProcedimento"`
	GuiaSolicInternacao        *CtguiaSolicInternacao        `xml:"guiaSolicInternacao"`
	GuiaSolicitacaoSADT        *CtguiaSolicitacaoSPSADT      `xml:"guiaSolicitacaoSADT"`
	GuiaSolicitacaoOdontologia *CtguiaSolicitacaoOdonto      `xml:"guiaSolicitacaoOdontologia"`
	GuiaSolicitacaoProrrogacao *CtguiaSolicitacaoProrrogacao `xml:"guiaSolicitacaoProrrogacao"`
}

// PrestadorParaOperadora ...
type PrestadorParaOperadora struct {
	XMLName                         xml.Name                             `xml:"prestadorParaOperadora"`
	LoteGuias                       *CtloteGuias                         `xml:"loteGuias"`
	SolicitacaoDemonstrativoRetorno *CtsolicitacaoDemonstrativoPagamento `xml:"solicitacaoDemonstrativoRetorno"`
	SolicitacaoStatusProtocolo      *CtsolicitacaoStatusProtocolo        `xml:"solicitacaoStatusProtocolo"`
	SolicitacaoProcedimento         *SolicitacaoProcedimento             `xml:"solicitacaoProcedimento"`
	SolicitaStatusAutorizacao       *CtsolicitaStatusAutorizacao         `xml:"solicitaStatusAutorizacao"`
	VerificaElegibilidade           *CtsolicitaElegibilidade             `xml:"verificaElegibilidade"`
	CancelaGuia                     *CtcancelaGuia                       `xml:"cancelaGuia"`
}

// Epilogo ...
type Epilogo struct {
	XMLName xml.Name `xml:"epilogo"`
	Hash    string   `xml:"hash"`
}

// MensagemTISS ...
type MensagemTISS struct {
	XMLName                xml.Name                `xml:"mensagemTISS"`
	Cabecalho              *CabecalhoTransacao     `xml:"cabecalho"`
	OperadoraParaPrestador *OperadoraParaPrestador `xml:"operadoraParaPrestador"`
	PrestadorParaOperadora *PrestadorParaOperadora `xml:"prestadorParaOperadora"`
	Epilogo                *Epilogo                `xml:"epilogo"`
}
