// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// WscancelaGuia ...
type WscancelaGuia struct {
	XMLName     xml.Name            `xml:"ws_cancelaGuia"`
	Cabecalho   *CabecalhoTransacao `xml:"cabecalho"`
	CancelaGuia *CtcancelaGuia      `xml:"cancelaGuia"`
	Hash        string              `xml:"hash"`
}

// WsreciboCancelaGuia ...
type WsreciboCancelaGuia struct {
	XMLName           xml.Name             `xml:"ws_reciboCancelaGuia"`
	Cabecalho         *CabecalhoTransacao  `xml:"cabecalho"`
	ReciboCancelaGuia *CtreciboCancelaGuia `xml:"reciboCancelaGuia"`
	Hash              string               `xml:"hash"`
}

// CancelaGuia ...
type CancelaGuia *WscancelaGuia

// ReciboCancelaGuia ...
type ReciboCancelaGuia *WsreciboCancelaGuia

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// VersaoInvalida ...
type VersaoInvalida string

// HashInvalido ...
type HashInvalido string
