// Code generated by xgen. DO NOT EDIT.

package v4_01_00

import (
	"encoding/xml"
)

// WssolicitacaoDemonstrativoRetorno ...
type WssolicitacaoDemonstrativoRetorno struct {
	XMLName                         xml.Name                             `xml:"ws_solicitacaoDemonstrativoRetorno"`
	Cabecalho                       *CabecalhoTransacao                  `xml:"cabecalho"`
	SolicitacaoDemonstrativoRetorno *CtsolicitacaoDemonstrativoPagamento `xml:"solicitacaoDemonstrativoRetorno"`
	Hash                            string                               `xml:"hash"`
}

// DemonstrativoRetorno ...
type DemonstrativoRetorno struct {
	XMLName                   xml.Name                       `xml:"demonstrativoRetorno"`
	DemonstrativoAnaliseConta []*CtdemonstrativoAnaliseConta `xml:"demonstrativoAnaliseConta"`
	DemonstrativoOdontologia  []*CtdemonstrativoOdontologia  `xml:"demonstrativoOdontologia"`
	DemonstrativoPagamento    []*CtdemonstrativoPagamento    `xml:"demonstrativoPagamento"`
}

// WsDemonstrativoRetorno ...
type WsDemonstrativoRetorno struct {
	XMLName              xml.Name              `xml:"ws_DemonstrativoRetorno"`
	Cabecalho            *CabecalhoTransacao   `xml:"cabecalho"`
	DemonstrativoRetorno *DemonstrativoRetorno `xml:"demonstrativoRetorno"`
	Hash                 string                `xml:"hash"`
}

// SolicitacaoDemonstrativoRetorno ...
type SolicitacaoDemonstrativoRetorno *WssolicitacaoDemonstrativoRetorno

// DemonstrativoRetorno ...
type DemonstrativoRetorno *WsDemonstrativoRetorno

// DestinatarioInvalido ...
type DestinatarioInvalido string

// RemetenteInvalido ...
type RemetenteInvalido string

// VersaoInvalida ...
type VersaoInvalida string

// HashInvalido ...
type HashInvalido string
