// Code generated by xgen. DO NOT EDIT.

package tiss

import (
	"encoding/xml"
	"time"
)

// DadosBeneficiario ...
type DadosBeneficiario struct {
	XMLName        xml.Name `xml:"dadosBeneficiario"`
	NomeEmpresa    string   `xml:"nomeEmpresa"`
	NumeroTelefone string   `xml:"numeroTelefone"`
	NomeTitular    string   `xml:"nomeTitular"`
	*Ctbeneficiario
}

// DadosContratado ...
type DadosContratado struct {
	XMLName              xml.Name                `xml:"dadosContratado"`
	ConselhoProfissional *CtconselhoProfissional `xml:"conselhoProfissional"`
	*Ctcontratado
}

// DadosContratadoExecutante ...
type DadosContratadoExecutante struct {
	XMLName         xml.Name                  `xml:"dadosContratadoExecutante"`
	DadosContratado *DadosContratado          `xml:"dadosContratado"`
	DadosExecutante *CtprofissionalExecutante `xml:"dadosExecutante"`
}

// CtanexoSituacaoInicial ...
type CtanexoSituacaoInicial struct {
	XMLName                   xml.Name                   `xml:"ct_anexoSituacaoInicial"`
	CabecalhoAnexoGuia        *CtcabecalhoAnexoOdonto    `xml:"cabecalhoAnexoGuia"`
	DadosBeneficiario         *DadosBeneficiario         `xml:"dadosBeneficiario"`
	DadosContratadoExecutante *DadosContratadoExecutante `xml:"dadosContratadoExecutante"`
	SituacaoInicial           *CtsituacaoInicial         `xml:"situacaoInicial"`
	Observacao                string                     `xml:"observacao"`
}

// Procedimento ...
type Procedimento struct {
	XMLName            xml.Name `xml:"procedimento"`
	CodigoTabela       string   `xml:"codigoTabela"`
	CodigoProcedimento string   `xml:"codigoProcedimento"`
}

// CtatendimentoConsulta ...
type CtatendimentoConsulta struct {
	XMLName         xml.Name      `xml:"ct_atendimentoConsulta"`
	DataAtendimento string        `xml:"dataAtendimento"`
	Procedimento    *Procedimento `xml:"procedimento"`
	TipoConsulta    string        `xml:"tipoConsulta"`
	TipoSaida       string        `xml:"tipoSaida"`
}

// CtatendimentoConsultaReapr ...
type CtatendimentoConsultaReapr struct {
	XMLName         xml.Name      `xml:"ct_atendimentoConsultaReapr"`
	Procedimento    *Procedimento `xml:"procedimento"`
	TipoConsulta    string        `xml:"tipoConsulta"`
	TipoSaida       string        `xml:"tipoSaida"`
	DataAtendimento string        `xml:"dataAtendimento"`
}

// CtatendimentoOdontologia ...
type CtatendimentoOdontologia struct {
	XMLName               xml.Name `xml:"ct_atendimentoOdontologia"`
	DataTerminoTratamento string   `xml:"dataTerminoTratamento"`
	TipoAtendimento       string   `xml:"tipoAtendimento"`
}

// CtautorizacaoGuia ...
type CtautorizacaoGuia struct {
	XMLName          xml.Name `xml:"ct_autorizacaoGuia"`
	DataAutorizacao  string   `xml:"dataAutorizacao"`
	SenhaAutorizacao string   `xml:"senhaAutorizacao"`
	ValidadeSenha    string   `xml:"validadeSenha"`
}

// CtautorizacaoGuiaInternacao ...
type CtautorizacaoGuiaInternacao struct {
	XMLName               xml.Name `xml:"ct_autorizacaoGuiaInternacao"`
	DiasAutorizado        int      `xml:"diasAutorizado"`
	DataProvavelAdmisHosp string   `xml:"dataProvavelAdmisHosp"`
	TipoAcomodacao        string   `xml:"tipoAcomodacao"`
	*CtautorizacaoGuia
}

// MotivoNegativa ...
type MotivoNegativa struct {
	XMLName     xml.Name         `xml:"motivoNegativa"`
	MotivoGlosa []*CtmotivoGlosa `xml:"motivoGlosa"`
}

// Procedimentos ...
type Procedimentos struct {
	XMLName      xml.Name             `xml:"procedimentos"`
	Procedimento []*CtitemSolicitacao `xml:"procedimento"`
}

// CtautorizacaoProcedimento ...
type CtautorizacaoProcedimento struct {
	XMLName                  xml.Name                     `xml:"ct_autorizacaoProcedimento"`
	IdentificacaoAutorizacao *CtcabecalhoGuia             `xml:"identificacaoAutorizacao"`
	StatusSolicitacao        string                       `xml:"statusSolicitacao"`
	MotivoNegativa           *MotivoNegativa              `xml:"motivoNegativa"`
	Beneficiario             *Ctbeneficiario              `xml:"beneficiario"`
	PrestadorAutorizado      *Ctcontratado                `xml:"prestadorAutorizado"`
	DadosAutorizacao         *CtautorizacaoGuiaInternacao `xml:"dadosAutorizacao"`
	Procedimentos            *Procedimentos               `xml:"procedimentos"`
}

// TotalOdonto ...
type TotalOdonto struct {
	XMLName                     xml.Name `xml:"totalOdonto"`
	Totalvalor                  float64  `xml:"totalvalor"`
	TotalFranquiaCoparticipacao float64  `xml:"totalFranquiaCoparticipacao"`
	TotalquantidadeUS           float64  `xml:"totalquantidadeUS"`
}

// CtautorizacaoProcedimentoOdonto ...
type CtautorizacaoProcedimentoOdonto struct {
	XMLName                  xml.Name                     `xml:"ct_autorizacaoProcedimentoOdonto"`
	IdentificacaoAutorizacao *CtcabecalhoGuia             `xml:"identificacaoAutorizacao"`
	StatusSolicitacao        string                       `xml:"statusSolicitacao"`
	MotivoNegativa           *MotivoNegativa              `xml:"motivoNegativa"`
	Beneficiario             *Ctbeneficiario              `xml:"beneficiario"`
	PrestadorAutorizado      *Ctcontratado                `xml:"prestadorAutorizado"`
	DadosAutorizacao         *CtautorizacaoGuiaInternacao `xml:"dadosAutorizacao"`
	Procedimentos            *Procedimentos               `xml:"procedimentos"`
	TotalOdonto              *TotalOdonto                 `xml:"totalOdonto"`
}

// Ctbeneficiario ...
type Ctbeneficiario struct {
	XMLName                   xml.Name `xml:"ct_beneficiario"`
	NumeroCarteira            string   `xml:"numeroCarteira"`
	NomeBeneficiario          string   `xml:"nomeBeneficiario"`
	NomePlano                 string   `xml:"nomePlano"`
	ValidadeCarteira          string   `xml:"validadeCarteira"`
	NumeroCNS                 string   `xml:"numeroCNS"`
	IdentificadorBeneficiario string   `xml:"identificadorBeneficiario"`
}

// CtcabecalhoAnexoOdonto ...
type CtcabecalhoAnexoOdonto struct {
	XMLName             xml.Name `xml:"ct_cabecalhoAnexoOdonto"`
	NumeroGuiaPrincipal string   `xml:"numeroGuiaPrincipal"`
}

// IdentificacaoFontePagadora ...
type IdentificacaoFontePagadora struct {
	XMLName           xml.Name `xml:"identificacaoFontePagadora"`
	RegistroANS       string   `xml:"registroANS"`
	CnpjFontePagadora string   `xml:"cnpjFontePagadora"`
}

// CtcabecalhoGuia ...
type CtcabecalhoGuia struct {
	XMLName                    xml.Name                    `xml:"ct_cabecalhoGuia"`
	IdentificacaoFontePagadora *IdentificacaoFontePagadora `xml:"identificacaoFontePagadora"`
	DataEmissaoGuia            string                      `xml:"dataEmissaoGuia"`
	NumeroGuiaPrestador        string                      `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora        string                      `xml:"numeroGuiaOperadora"`
}

// CtcabecalhoGuiaOdonto ...
type CtcabecalhoGuiaOdonto struct {
	XMLName                    xml.Name                    `xml:"ct_cabecalhoGuiaOdonto"`
	IdentificacaoFontePagadora *IdentificacaoFontePagadora `xml:"identificacaoFontePagadora"`
	NumeroGuiaPrestador        string                      `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora        string                      `xml:"numeroGuiaOperadora"`
	DataEmissaoGuia            string                      `xml:"dataEmissaoGuia"`
	NumeroGuiaPrincipal        string                      `xml:"numeroGuiaPrincipal"`
	DataAutorizacao            string                      `xml:"dataAutorizacao"`
	SenhaAutorizacao           string                      `xml:"senhaAutorizacao"`
	ValidadeSenha              string                      `xml:"validadeSenha"`
}

// CtcabecalhoDemonstrativo ...
type CtcabecalhoDemonstrativo struct {
	XMLName             xml.Name `xml:"ct_cabecalhoDemonstrativo"`
	NumeroDemonstrativo string   `xml:"numeroDemonstrativo"`
	DataEmissao         string   `xml:"dataEmissao"`
}

// CtcabecalhoSolicitacao ...
type CtcabecalhoSolicitacao struct {
	XMLName                    xml.Name                    `xml:"ct_cabecalhoSolicitacao"`
	IdentificacaoFontePagadora *IdentificacaoFontePagadora `xml:"identificacaoFontePagadora"`
	DataEmissaoGuia            string                      `xml:"dataEmissaoGuia"`
	NumeroGuiaOperadora        string                      `xml:"numeroGuiaOperadora"`
	NumeroGuiaPrestador        string                      `xml:"numeroGuiaPrestador"`
}

// Guia ...
type Guia struct {
	XMLName   xml.Name           `xml:"guia"`
	DadosGuia []*CtcabecalhoGuia `xml:"dadosGuia"`
}

// CtcancelaGuia ...
type CtcancelaGuia struct {
	XMLName        xml.Name      `xml:"ct_cancelaGuia"`
	DadosPrestador *Ctcontratado `xml:"dadosPrestador"`
	TipoGuia       string        `xml:"tipoGuia"`
	Guia           *Guia         `xml:"guia"`
	Observacao     string        `xml:"observacao"`
}

// Ctcontratado ...
type Ctcontratado struct {
	XMLName            xml.Name                            `xml:"ct_contratado"`
	Identificacao      *CtidentificacaoPrestadorExecutante `xml:"identificacao"`
	NomeContratado     string                              `xml:"nomeContratado"`
	EnderecoContratado *Ctendereco                         `xml:"enderecoContratado"`
	NumeroCNES         string                              `xml:"numeroCNES"`
}

// CtcontratadoSolicitante ...
type CtcontratadoSolicitante struct {
	XMLName            xml.Name                  `xml:"ct_contratadoSolicitante"`
	Identificacao      *CtidentificacaoPrestador `xml:"identificacao"`
	NomeContratado     string                    `xml:"nomeContratado"`
	EnderecoContratado *Ctendereco               `xml:"enderecoContratado"`
	NumeroCNES         string                    `xml:"numeroCNES"`
}

// CtconselhoProfissional ...
type CtconselhoProfissional struct {
	XMLName        xml.Name `xml:"ct_conselhoProfissional"`
	SiglaConselho  string   `xml:"siglaConselho"`
	NumeroConselho string   `xml:"numeroConselho"`
	UfConselho     string   `xml:"ufConselho"`
}

// CtcreditoOdonto ...
type CtcreditoOdonto struct {
	XMLName       xml.Name `xml:"ct_creditoOdonto"`
	ValorDesconto float64  `xml:"valorDesconto"`
	Descricao     string   `xml:"descricao"`
}

// CtdadoBancario ...
type CtdadoBancario struct {
	XMLName        xml.Name `xml:"ct_dadoBancario"`
	DataPagamento  string   `xml:"dataPagamento"`
	FormaPagamento string   `xml:"formaPagamento"`
	Banco          int      `xml:"banco"`
	Agencia        string   `xml:"agencia"`
	ContaCorrente  string   `xml:"contaCorrente"`
}

// Lote ...
type Lote struct {
	XMLName   xml.Name       `xml:"lote"`
	DadosLote []*CtdadosLote `xml:"dadosLote"`
}

// CtdadosConta ...
type CtdadosConta struct {
	XMLName               xml.Name `xml:"ct_dadosConta"`
	NumeroFatura          string   `xml:"numeroFatura"`
	Lote                  *Lote    `xml:"lote"`
	ValorProcessadoFatura float64  `xml:"valorProcessadoFatura"`
	ValorLiberadoFatura   float64  `xml:"valorLiberadoFatura"`
	ValorGlosaFatura      float64  `xml:"valorGlosaFatura"`
}

// CtdadosGuia ...
type CtdadosGuia struct {
	XMLName             xml.Name         `xml:"ct_dadosGuia"`
	NumeroGuiaPrestador string           `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora string           `xml:"numeroGuiaOperadora"`
	Beneficiario        *Ctbeneficiario  `xml:"beneficiario"`
	DataRealizacao      string           `xml:"dataRealizacao"`
	ValorProcessadoGuia float64          `xml:"valorProcessadoGuia"`
	ValorLiberadoGuia   float64          `xml:"valorLiberadoGuia"`
	ValorGlosaGuia      float64          `xml:"valorGlosaGuia"`
	Procedimentos       *Procedimentos   `xml:"procedimentos"`
	CodigoGlosaGuia     []*CtmotivoGlosa `xml:"codigoGlosaGuia"`
}

// CtdadosLote ...
type CtdadosLote struct {
	XMLName              xml.Name `xml:"ct_dadosLote"`
	NumeroLote           string   `xml:"numeroLote"`
	DataEnvioLote        string   `xml:"dataEnvioLote"`
	NumeroProtocolo      string   `xml:"numeroProtocolo"`
	ValorProtocolo       float64  `xml:"valorProtocolo"`
	ValorGlosaProtocolo  float64  `xml:"valorGlosaProtocolo"`
	CodigoGlosaProtocolo []string `xml:"codigoGlosaProtocolo"`
	Guia                 *Guia    `xml:"guia"`
}

// LoteOdonto ...
type LoteOdonto struct {
	XMLName        xml.Name           `xml:"loteOdonto"`
	TotalGeralLote *CttotalDemoOdonto `xml:"totalGeralLote"`
	*CtloteOdonto
}

// CtdadosPagamento ...
type CtdadosPagamento struct {
	XMLName       xml.Name      `xml:"ct_dadosPagamento"`
	DataPagamento string        `xml:"dataPagamento"`
	LoteOdonto    []*LoteOdonto `xml:"loteOdonto"`
}

// RelacaoGlosa ...
type RelacaoGlosa struct {
	XMLName    xml.Name         `xml:"relacaoGlosa"`
	TipoGlosa  []*CtmotivoGlosa `xml:"tipoGlosa"`
	ValorGlosa float64          `xml:"valorGlosa"`
}

// CtdadosProcedimento ...
type CtdadosProcedimento struct {
	XMLName             xml.Name      `xml:"ct_dadosProcedimento"`
	Procedimento        *Cttabela     `xml:"procedimento"`
	QuantidadeExecutada int           `xml:"quantidadeExecutada"`
	ValorProcessado     float64       `xml:"valorProcessado"`
	ValorLiberado       float64       `xml:"valorLiberado"`
	GrauParticipacao    string        `xml:"grauParticipacao"`
	RelacaoGlosa        *RelacaoGlosa `xml:"relacaoGlosa"`
}

// CtdadosResumo ...
type CtdadosResumo struct {
	XMLName         xml.Name `xml:"ct_dadosResumo"`
	NumeroFatura    string   `xml:"numeroFatura"`
	NumeroLote      string   `xml:"numeroLote"`
	DataEnvioLote   string   `xml:"dataEnvioLote"`
	NumeroProtocolo string   `xml:"numeroProtocolo"`
	ValorInformado  float64  `xml:"valorInformado"`
	ValorProcessado float64  `xml:"valorProcessado"`
	ValorLiberado   float64  `xml:"valorLiberado"`
	ValorGlosa      float64  `xml:"valorGlosa"`
}

// Fatura ...
type Fatura struct {
	XMLName     xml.Name      `xml:"fatura"`
	DadosFatura *CtdadosConta `xml:"dadosFatura"`
}

// CtdemonstrativoAnaliseConta ...
type CtdemonstrativoAnaliseConta struct {
	XMLName                    xml.Name                      `xml:"ct_demonstrativoAnaliseConta"`
	IdentificacaoFontePagadora *CtidentificacaoFontePagadora `xml:"identificacaoFontePagadora"`
	CabecalhoDemonstrativo     *CtcabecalhoDemonstrativo     `xml:"cabecalhoDemonstrativo"`
	DadosPrestador             *Ctcontratado                 `xml:"dadosPrestador"`
	Fatura                     *Fatura                       `xml:"fatura"`
	ValorProcessadoGeral       float64                       `xml:"valorProcessadoGeral"`
	ValorLiberadoGeral         float64                       `xml:"valorLiberadoGeral"`
	ValorGlosaGeral            float64                       `xml:"valorGlosaGeral"`
}

// DadosResumo ...
type DadosResumo struct {
	XMLName              xml.Name         `xml:"dadosResumo"`
	DetalheResumo        []*CtdadosResumo `xml:"detalheResumo"`
	TotalGeralInformado  float64          `xml:"totalGeralInformado"`
	TotalGeralProcessado float64          `xml:"TotalGeralProcessado"`
	TotalGeralGlosa      float64          `xml:"TotalGeralGlosa"`
	TotalGeralLiberado   float64          `xml:"TotalGeralLiberado"`
}

// CtdemonstrativoPagamento ...
type CtdemonstrativoPagamento struct {
	XMLName                    xml.Name                      `xml:"ct_demonstrativoPagamento"`
	CabecalhoDemonstrativo     *CtcabecalhoDemonstrativo     `xml:"cabecalhoDemonstrativo"`
	IdentificacaoFontePagadora *CtidentificacaoFontePagadora `xml:"identificacaoFontePagadora"`
	DadosPrestador             *Ctcontratado                 `xml:"dadosPrestador"`
	DadosPagamento             *CtdadoBancario               `xml:"dadosPagamento"`
	DadosResumo                *DadosResumo                  `xml:"dadosResumo"`
	ValorTotal                 float64                       `xml:"valorTotal"`
	DemaisDescontos            *Ctdescontos                  `xml:"demaisDescontos"`
	ValorFinalLiberado         float64                       `xml:"valorFinalLiberado"`
}

// DadosPrestador ...
type DadosPrestador struct {
	XMLName                    xml.Name                        `xml:"dadosPrestador"`
	CodigoPrestadorNaOperadora string                          `xml:"codigoPrestadorNaOperadora"`
	IdentificadorPrestador     *CtidentificadorPrestOdontoDemo `xml:"identificadorPrestador"`
	NomeContratado             string                          `xml:"nomeContratado"`
	NumeroCNES                 string                          `xml:"numeroCNES"`
}

// DadosPagamento ...
type DadosPagamento struct {
	XMLName    xml.Name           `xml:"dadosPagamento"`
	TotalGeral *CttotalDemoOdonto `xml:"totalGeral"`
	*CtdadosPagamento
}

// DebitosCreditosTributaveis ...
type DebitosCreditosTributaveis struct {
	XMLName              xml.Name            `xml:"debitosCreditosTributaveis"`
	Descontos            []*CtdescontoOdonto `xml:"descontos"`
	Creditos             []*CtcreditoOdonto  `xml:"creditos"`
	ValorTotalTributavel float64             `xml:"valorTotalTributavel"`
}

// DemaisImpostos ...
type DemaisImpostos struct {
	XMLName            xml.Name            `xml:"demaisImpostos"`
	Descontos          []*CtdescontoOdonto `xml:"descontos"`
	ValorTotalImpostos float64             `xml:"valorTotalImpostos"`
}

// DebitosCreditosNaoTributaveis ...
type DebitosCreditosNaoTributaveis struct {
	XMLName                 xml.Name            `xml:"debitosCreditosNaoTributaveis"`
	Descontos               []*CtdescontoOdonto `xml:"descontos"`
	Creditos                []*CtcreditoOdonto  `xml:"creditos"`
	ValorTotalNaoTributavel float64             `xml:"valorTotalNaoTributavel"`
}

// CtdemonstrativoOdontologia ...
type CtdemonstrativoOdontologia struct {
	XMLName                       xml.Name                       `xml:"ct_demonstrativoOdontologia"`
	CabecalhoDemonstrativo        *CtcabecalhoDemonstrativo      `xml:"cabecalhoDemonstrativo"`
	IdentificacaoFontePagadora    *CtidentificacaoFontePagadora  `xml:"identificacaoFontePagadora"`
	DadosPrestador                *DadosPrestador                `xml:"dadosPrestador"`
	DadosPagamento                []*DadosPagamento              `xml:"dadosPagamento"`
	DebitosCreditosTributaveis    *DebitosCreditosTributaveis    `xml:"debitosCreditosTributaveis"`
	DemaisImpostos                *DemaisImpostos                `xml:"demaisImpostos"`
	DebitosCreditosNaoTributaveis *DebitosCreditosNaoTributaveis `xml:"debitosCreditosNaoTributaveis"`
	ValorFinalReceber             float64                        `xml:"valorFinalReceber"`
	Observacao                    string                         `xml:"observacao"`
}

// CtdescontoOdonto ...
type CtdescontoOdonto struct {
	XMLName       xml.Name `xml:"ct_descontoOdonto"`
	Descricao     string   `xml:"descricao"`
	ValorDesconto float64  `xml:"valorDesconto"`
}

// ProcedimentoRealizado ...
type ProcedimentoRealizado struct {
	XMLName             xml.Name                         `xml:"procedimentoRealizado"`
	ProcedimentosOdonto []*CtprocedimentoOdontoRealizado `xml:"procedimentosOdonto"`
}

// CtdetalheGuiaOdonto ...
type CtdetalheGuiaOdonto struct {
	XMLName                  xml.Name               `xml:"ct_detalheGuiaOdonto"`
	NumeroGuiaPrestador      string                 `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora      string                 `xml:"numeroGuiaOperadora"`
	CodigoBeneficiario       string                 `xml:"codigoBeneficiario"`
	NomeBeneficiario         string                 `xml:"NomeBeneficiario"`
	ProcedimentoRealizado    *ProcedimentoRealizado `xml:"procedimentoRealizado"`
	ValorTotalGlosaGuia      float64                `xml:"valorTotalGlosaGuia"`
	ValorTotalLiberadoGuia   float64                `xml:"valorTotalLiberadoGuia"`
	ValorTotalProcessadoGuia float64                `xml:"valorTotalProcessadoGuia"`
}

// CodigoGlosaProtocolo ...
type CodigoGlosaProtocolo struct {
	XMLName             xml.Name         `xml:"codigoGlosaProtocolo"`
	MotivoGlosa         []*CtmotivoGlosa `xml:"motivoGlosa"`
	ValorGlosaProtocolo float64          `xml:"valorGlosaProtocolo"`
}

// Guias ...
type Guias struct {
	XMLName   xml.Name       `xml:"guias"`
	DadosGuia []*CtdadosGuia `xml:"dadosGuia"`
}

// CtdetalheProtocolo ...
type CtdetalheProtocolo struct {
	XMLName              xml.Name              `xml:"ct_detalheProtocolo"`
	NumeroProtocolo      string                `xml:"numeroProtocolo"`
	ValorProtocolo       float64               `xml:"valorProtocolo"`
	CodigoGlosaProtocolo *CodigoGlosaProtocolo `xml:"codigoGlosaProtocolo"`
	Guias                *Guias                `xml:"guias"`
}

// CtdenteRegiao ...
type CtdenteRegiao struct {
	XMLName xml.Name `xml:"ct_denteRegiao"`
	Dente   string   `xml:"dente"`
	Regiao  string   `xml:"regiao"`
}

// ItemDesconto ...
type ItemDesconto struct {
	XMLName       xml.Name `xml:"itemDesconto"`
	ValorDesconto float64  `xml:"valorDesconto"`
	Descricao     string   `xml:"descricao"`
}

// Ctdescontos ...
type Ctdescontos struct {
	XMLName      xml.Name        `xml:"ct_descontos"`
	ItemDesconto []*ItemDesconto `xml:"itemDesconto"`
}

// Ctdiagnostico ...
type Ctdiagnostico struct {
	XMLName              xml.Name `xml:"ct_diagnostico"`
	NomeTabela           string   `xml:"nomeTabela"`
	CodigoDiagnostico    string   `xml:"codigoDiagnostico"`
	DescricaoDiagnostico string   `xml:"descricaoDiagnostico"`
}

// CtdiagnosticoAtendimento ...
type CtdiagnosticoAtendimento struct {
	XMLName                     xml.Name               `xml:"ct_diagnosticoAtendimento"`
	CID                         *Ctdiagnostico         `xml:"CID"`
	TipoDoenca                  string                 `xml:"tipoDoenca"`
	TempoReferidoEvolucaoDoenca *CttempoEvolucaoDoenca `xml:"tempoReferidoEvolucaoDoenca"`
	IndicadorAcidente           string                 `xml:"indicadorAcidente"`
}

// CtdiagnosticoGuia ...
type CtdiagnosticoGuia struct {
	XMLName                     xml.Name               `xml:"ct_diagnosticoGuia"`
	CID                         *Ctdiagnostico         `xml:"CID"`
	TipoDoenca                  string                 `xml:"tipoDoenca"`
	TempoReferidoEvolucaoDoenca *CttempoEvolucaoDoenca `xml:"tempoReferidoEvolucaoDoenca"`
	IndicadorAcidente           string                 `xml:"indicadorAcidente"`
}

// CtdiagnosticoSaidaInternacao ...
type CtdiagnosticoSaidaInternacao struct {
	XMLName                 xml.Name                   `xml:"ct_diagnosticoSaidaInternacao"`
	DiagnosticoPrincipal    *Ctdiagnostico             `xml:"diagnosticoPrincipal"`
	IndicadorAcidente       string                     `xml:"indicadorAcidente"`
	DiagnosticosSecundarios *CtdiagnosticosSecundarios `xml:"diagnosticosSecundarios"`
	MotivoSaidaInternacao   string                     `xml:"motivoSaidaInternacao"`
	Obito                   []*CtobitoInternacao       `xml:"obito"`
}

// CtdiagnosticosSecundarios ...
type CtdiagnosticosSecundarios struct {
	XMLName xml.Name         `xml:"ct_diagnosticosSecundarios"`
	CID     []*Ctdiagnostico `xml:"CID"`
}

// CtdiariaProrrogacaoAutorizada ...
type CtdiariaProrrogacaoAutorizada struct {
	XMLName              xml.Name       `xml:"ct_diariaProrrogacaoAutorizada"`
	QuantidadeAutorizada float64        `xml:"quantidadeAutorizada"`
	MotivoGlosa          *CtmotivoGlosa `xml:"motivoGlosa"`
	*CtdiariaProrrogacao
}

// CtdiariaProrrogacao ...
type CtdiariaProrrogacao struct {
	XMLName          xml.Name `xml:"ct_diariaProrrogacao"`
	TipoAcomodacao   string   `xml:"tipoAcomodacao"`
	QuantidadeDiaria float64  `xml:"quantidadeDiaria"`
}

// Ctendereco ...
type Ctendereco struct {
	XMLName             xml.Name `xml:"ct_endereco"`
	TipoLogradouro      string   `xml:"tipoLogradouro"`
	Logradouro          string   `xml:"logradouro"`
	Numero              string   `xml:"numero"`
	Complemento         string   `xml:"complemento"`
	CodigoIBGEMunicipio string   `xml:"codigoIBGEMunicipio"`
	Municipio           string   `xml:"municipio"`
	CodigoUF            string   `xml:"codigoUF"`
	Cep                 string   `xml:"cep"`
}

// CtexecutanteComplementar ...
type CtexecutanteComplementar struct {
	XMLName                 xml.Name                  `xml:"ct_executanteComplementar"`
	CodigoProfissionalCompl *CtidentificacaoPrestador `xml:"codigoProfissionalCompl"`
	NomeProfissionalCompl   string                    `xml:"nomeProfissionalCompl"`
}

// CthipoteseDiagnostica ...
type CthipoteseDiagnostica struct {
	XMLName                 xml.Name                   `xml:"ct_hipoteseDiagnostica"`
	CIDPrincipal            *CtdiagnosticoGuia         `xml:"CIDPrincipal"`
	DiagnosticosSecundarios *CtdiagnosticosSecundarios `xml:"diagnosticosSecundarios"`
}

// MembroEquipe ...
type MembroEquipe struct {
	XMLName                   xml.Name                        `xml:"membroEquipe"`
	CodigoProfissional        *CtidentificacaoPrestadorEquipe `xml:"codigoProfissional"`
	IdentificacaoProfissional *CtprofissionalExecutante       `xml:"identificacaoProfissional"`
	Cpf                       string                          `xml:"cpf"`
	PosicaoProfissional       string                          `xml:"posicaoProfissional"`
}

// CtidentificacaoEquipe ...
type CtidentificacaoEquipe struct {
	XMLName      xml.Name        `xml:"ct_identificacaoEquipe"`
	MembroEquipe []*MembroEquipe `xml:"membroEquipe"`
}

// OperadoraRegulada ...
type OperadoraRegulada struct {
	XMLName       xml.Name `xml:"operadoraRegulada"`
	RegistroANS   string   `xml:"registroANS"`
	CNPJ          string   `xml:"CNPJ"`
	NomeOperadora string   `xml:"nomeOperadora"`
}

// EntidadeNaoRegulada ...
type EntidadeNaoRegulada struct {
	XMLName               xml.Name `xml:"entidadeNaoRegulada"`
	CNPJ                  string   `xml:"CNPJ"`
	NomeOperadoraEntidade string   `xml:"nomeOperadoraEntidade"`
}

// CtidentificacaoFontePagadora ...
type CtidentificacaoFontePagadora struct {
	XMLName             xml.Name             `xml:"ct_identificacaoFontePagadora"`
	OperadoraRegulada   *OperadoraRegulada   `xml:"operadoraRegulada"`
	EntidadeNaoRegulada *EntidadeNaoRegulada `xml:"entidadeNaoRegulada"`
}

// CtidentificacaoPrestador ...
type CtidentificacaoPrestador struct {
	XMLName                    xml.Name                `xml:"ct_identificacaoPrestador"`
	CNPJ                       string                  `xml:"CNPJ"`
	Cpf                        string                  `xml:"cpf"`
	CodigoPrestadorNaOperadora string                  `xml:"codigoPrestadorNaOperadora"`
	ConselhoProfissional       *CtconselhoProfissional `xml:"conselhoProfissional"`
}

// CtidentificacaoPrestadorEquipe ...
type CtidentificacaoPrestadorEquipe struct {
	XMLName                    xml.Name                `xml:"ct_identificacaoPrestadorEquipe"`
	Cpf                        string                  `xml:"cpf"`
	CodigoPrestadorNaOperadora string                  `xml:"codigoPrestadorNaOperadora"`
	ConselhoProfissional       *CtconselhoProfissional `xml:"conselhoProfissional"`
}

// CtidentificacaoPrestadorExecutante ...
type CtidentificacaoPrestadorExecutante struct {
	XMLName                    xml.Name `xml:"ct_identificacaoPrestadorExecutante"`
	CNPJ                       string   `xml:"CNPJ"`
	CPF                        string   `xml:"CPF"`
	CodigoPrestadorNaOperadora string   `xml:"codigoPrestadorNaOperadora"`
}

// CtidentificacaoProfissional ...
type CtidentificacaoProfissional struct {
	XMLName              xml.Name                `xml:"ct_identificacaoProfissional"`
	NomeProfissional     string                  `xml:"nomeProfissional"`
	ConselhoProfissional *CtconselhoProfissional `xml:"conselhoProfissional"`
	Cbos                 string                  `xml:"cbos"`
}

// CtidentificacaoProfissionalCompl ...
type CtidentificacaoProfissionalCompl struct {
	XMLName                    xml.Name `xml:"ct_identificacaoProfissionalCompl"`
	Cpf                        string   `xml:"cpf"`
	CodigoPrestadorNaOperadora string   `xml:"codigoPrestadorNaOperadora"`
}

// CtidentificadorPrestOdontoDemo ...
type CtidentificadorPrestOdontoDemo struct {
	XMLName xml.Name `xml:"ct_identificadorPrestOdontoDemo"`
	CNPJ    string   `xml:"CNPJ"`
	Cpf     string   `xml:"cpf"`
}

// CtinternacaoObstetrica ...
type CtinternacaoObstetrica struct {
	XMLName                      xml.Name    `xml:"ct_internacaoObstetrica"`
	EmGestacao                   bool        `xml:"emGestacao"`
	Aborto                       bool        `xml:"aborto"`
	TranstornoMaternoRelGravidez bool        `xml:"transtornoMaternoRelGravidez"`
	ComplicacaoPeriodoPuerperio  bool        `xml:"complicacaoPeriodoPuerperio"`
	AtendimentoRNSalaParto       bool        `xml:"atendimentoRNSalaParto"`
	ComplicacaoNeonatal          bool        `xml:"complicacaoNeonatal"`
	BaixoPeso                    bool        `xml:"baixoPeso"`
	PartoCesareo                 bool        `xml:"partoCesareo"`
	PartoNormal                  bool        `xml:"partoNormal"`
	DeclaracoesNascidosVivos     *CtnumeroDN `xml:"declaracoesNascidosVivos"`
	QtdNascidosVivosTermo        int         `xml:"qtdNascidosVivosTermo"`
	QtdNascidosMortos            int         `xml:"qtdNascidosMortos"`
	QtdVivosPrematuros           int         `xml:"qtdVivosPrematuros"`
	ObitoMulher                  string      `xml:"obitoMulher"`
}

// Glosas ...
type Glosas struct {
	XMLName     xml.Name         `xml:"glosas"`
	MotivoGlosa []*CtmotivoGlosa `xml:"motivoGlosa"`
}

// CtitemSolicitacao ...
type CtitemSolicitacao struct {
	XMLName                       xml.Name  `xml:"ct_itemSolicitacao"`
	IdentificacaoProcedimentos    *Cttabela `xml:"identificacaoProcedimentos"`
	QuantidadeSolicitada          float64   `xml:"quantidadeSolicitada"`
	QuantidadeAutorizada          float64   `xml:"quantidadeAutorizada"`
	StatusSolicitacaoProcedimento string    `xml:"statusSolicitacaoProcedimento"`
	Glosas                        *Glosas   `xml:"glosas"`
	Observacao                    string    `xml:"observacao"`
}

// CtitemSolicitacaoOdonto ...
type CtitemSolicitacaoOdonto struct {
	XMLName                       xml.Name       `xml:"ct_itemSolicitacaoOdonto"`
	IdentificacaoProcedimentos    *Cttabela      `xml:"identificacaoProcedimentos"`
	DenteRegiao                   *CtdenteRegiao `xml:"denteRegiao"`
	Face                          string         `xml:"face"`
	QuantidadeSolicitada          float64        `xml:"quantidadeSolicitada"`
	QuantidadeAutorizada          float64        `xml:"quantidadeAutorizada"`
	Glosas                        *Glosas        `xml:"glosas"`
	StatusSolicitacaoProcedimento string         `xml:"statusSolicitacaoProcedimento"`
	Observacao                    string         `xml:"observacao"`
}

// CtloteOdonto ...
type CtloteOdonto struct {
	XMLName                  xml.Name               `xml:"ct_loteOdonto"`
	NumeroLote               string                 `xml:"numeroLote"`
	DetalheGuia              []*CtdetalheGuiaOdonto `xml:"detalheGuia"`
	ValorTotalLiberadoLote   float64                `xml:"valorTotalLiberadoLote"`
	ValorTotalProcessadoLote float64                `xml:"valorTotalProcessadoLote"`
	ValorTotalGlosaLote      float64                `xml:"valorTotalGlosaLote"`
}

// CtmotivoGlosa ...
type CtmotivoGlosa struct {
	XMLName        xml.Name `xml:"ct_motivoGlosa"`
	CodigoGlosa    string   `xml:"codigoGlosa"`
	DescricaoGlosa string   `xml:"descricaoGlosa"`
}

// CtnumeroDN ...
type CtnumeroDN struct {
	XMLName  xml.Name `xml:"ct_numeroDN"`
	NumeroDN []string `xml:"numeroDN"`
}

// CtobitoInternacao ...
type CtobitoInternacao struct {
	XMLName          xml.Name       `xml:"ct_obitoInternacao"`
	CID              *Ctdiagnostico `xml:"CID"`
	NumeroDeclaracao string         `xml:"numeroDeclaracao"`
}

// CtobitoNeonatal ...
type CtobitoNeonatal struct {
	XMLName          xml.Name `xml:"ct_obitoNeonatal"`
	QtdeobitoPrecoce int      `xml:"qtdeobitoPrecoce"`
	QtdeobitoTardio  int      `xml:"qtdeobitoTardio"`
}

// OPMAutorizada ...
type OPMAutorizada struct {
	QuantidadeAutorizada float64   `xml:"quantidadeAutorizada"`
	Fabricante           string    `xml:"fabricante"`
	OPM                  *Cttabela `xml:"OPM"`
}

// CtOPMAutorizada ...
type CtOPMAutorizada struct {
	XMLName       xml.Name         `xml:"ct_OPMAutorizada"`
	OPMAutorizada []*OPMAutorizada `xml:"OPMAutorizada"`
}

// OPMSolicitada ...
type OPMSolicitada struct {
	QuantidadeSolicitada float64   `xml:"quantidadeSolicitada"`
	Fabricante           string    `xml:"fabricante"`
	Valor                float64   `xml:"valor"`
	OPM                  *Cttabela `xml:"OPM"`
}

// CtOPMSolicitadas ...
type CtOPMSolicitadas struct {
	XMLName       xml.Name         `xml:"ct_OPMSolicitadas"`
	OPMSolicitada []*OPMSolicitada `xml:"OPMSolicitada"`
}

// IdentificacaoOPM ...
type IdentificacaoOPM struct {
	XMLName       xml.Name  `xml:"identificacaoOPM"`
	OPM           *Cttabela `xml:"OPM"`
	Quantidade    float64   `xml:"quantidade"`
	CodigoBarra   string    `xml:"codigoBarra"`
	ValorUnitario float64   `xml:"valorUnitario"`
	ValorTotal    float64   `xml:"valorTotal"`
}

// OPM ...
type OPM struct {
	IdentificacaoOPM []*IdentificacaoOPM `xml:"identificacaoOPM"`
}

// CtOPMUtilizada ...
type CtOPMUtilizada struct {
	XMLName       xml.Name `xml:"ct_OPMUtilizada"`
	OPM           *OPM     `xml:"OPM"`
	ValorTotalOPM float64  `xml:"valorTotalOPM"`
}

// OPMUtilizada ...
type OPMUtilizada struct {
	OPM []*OPM `xml:"OPM"`
}

// CtOPMUtilizadasRevisao ...
type CtOPMUtilizadasRevisao struct {
	XMLName       xml.Name      `xml:"ct_OPMUtilizadasRevisao"`
	OPMUtilizada  *OPMUtilizada `xml:"OPMUtilizada"`
	ValorTotalOPM float64       `xml:"valorTotalOPM"`
}

// Despesa ...
type Despesa struct {
	XMLName              xml.Name  `xml:"despesa"`
	IdentificadorDespesa *Cttabela `xml:"identificadorDespesa"`
	TipoDespesa          string    `xml:"tipoDespesa"`
	DataRealizacao       string    `xml:"dataRealizacao"`
	HoraInicial          time.Time `xml:"horaInicial"`
	HoraFinal            time.Time `xml:"horaFinal"`
	ReducaoAcrescimo     float64   `xml:"reducaoAcrescimo"`
	Quantidade           float64   `xml:"quantidade"`
	ValorUnitario        float64   `xml:"valorUnitario"`
	ValorTotal           float64   `xml:"valorTotal"`
}

// CtoutrasDespesas ...
type CtoutrasDespesas struct {
	XMLName                  xml.Name   `xml:"ct_outrasDespesas"`
	Despesa                  []*Despesa `xml:"despesa"`
	TotalGeralOutrasDespesas float64    `xml:"totalGeralOutrasDespesas"`
}

// ItensDespesas ...
type ItensDespesas struct {
	XMLName          xml.Name  `xml:"itensDespesas"`
	TipoDespesa      string    `xml:"tipoDespesa"`
	DataRealizacao   string    `xml:"dataRealizacao"`
	Despesa          *Cttabela `xml:"despesa"`
	ReducaoAcrescimo float64   `xml:"reducaoAcrescimo"`
	Quantidade       float64   `xml:"quantidade"`
	ValorUnitario    float64   `xml:"valorUnitario"`
	ValorTotal       float64   `xml:"valorTotal"`
	Justificativa    string    `xml:"justificativa"`
}

// CtoutrasDespesasRevisao ...
type CtoutrasDespesasRevisao struct {
	XMLName                  xml.Name         `xml:"ct_outrasDespesasRevisao"`
	ItensDespesas            []*ItensDespesas `xml:"itensDespesas"`
	TotalGeralOutrasDespesas float64          `xml:"totalGeralOutrasDespesas"`
}

// CtperiodoProcessamento ...
type CtperiodoProcessamento struct {
	XMLName     xml.Name `xml:"ct_periodoProcessamento"`
	DataInicial string   `xml:"dataInicial"`
	DataFinal   string   `xml:"dataFinal"`
}

// CtprocedimentoOdontologia ...
type CtprocedimentoOdontologia struct {
	XMLName                xml.Name       `xml:"ct_procedimentoOdontologia"`
	ProcedimentoOdonto     *Cttabela      `xml:"procedimentoOdonto"`
	DenteRegiao            *CtdenteRegiao `xml:"denteRegiao"`
	Face                   string         `xml:"face"`
	Quantidade             int            `xml:"quantidade"`
	QuantidadeUS           float64        `xml:"quantidadeUS"`
	Valor                  float64        `xml:"valor"`
	FranquiaCoparticipacao float64        `xml:"franquiaCoparticipacao"`
}

// CtprocedimentoOdontoRealizado ...
type CtprocedimentoOdontoRealizado struct {
	XMLName            xml.Name       `xml:"ct_procedimentoOdontoRealizado"`
	ProcedimentoOdonto *Cttabela      `xml:"procedimentoOdonto"`
	DenteRegiao        *CtdenteRegiao `xml:"denteRegiao"`
	Face               string         `xml:"face"`
	DataRealizacao     string         `xml:"dataRealizacao"`
	Quantidade         int            `xml:"quantidade"`
	ValorProcessado    float64        `xml:"valorProcessado"`
	ValorGlosaEstorno  float64        `xml:"valorGlosaEstorno"`
	Glosas             *Glosas        `xml:"glosas"`
	ValorLiberado      float64        `xml:"valorLiberado"`
}

// CtprocedimentosRealizados ...
type CtprocedimentosRealizados struct {
	XMLName               xml.Name                 `xml:"ct_procedimentosRealizados"`
	ProcedimentoRealizado []*ProcedimentoRealizado `xml:"procedimentoRealizado"`
}

// ProcedimentoOdontologia ...
type ProcedimentoOdontologia struct {
	XMLName        xml.Name `xml:"procedimentoOdontologia"`
	DataRealizacao string   `xml:"dataRealizacao"`
	*CtprocedimentoOdontologia
}

// CtprocedimentoOdontoRevisao ...
type CtprocedimentoOdontoRevisao struct {
	XMLName                     xml.Name                 `xml:"ct_procedimentoOdontoRevisao"`
	ProcedimentoOdontologia     *ProcedimentoOdontologia `xml:"procedimentoOdontologia"`
	ValorTotal                  float64                  `xml:"valorTotal"`
	QuantidadeTotalUS           float64                  `xml:"quantidadeTotalUS"`
	TotalFranquiaCoparticipacao float64                  `xml:"totalFranquiaCoparticipacao"`
	JustificativaRevisao        string                   `xml:"justificativaRevisao"`
}

// CtprocedimentoRealizadoEquipe ...
type CtprocedimentoRealizadoEquipe struct {
	XMLName       xml.Name         `xml:"ct_procedimentoRealizadoEquipe"`
	Procedimentos []*Procedimentos `xml:"procedimentos"`
}

// ProcedimentosRevisao ...
type ProcedimentosRevisao struct {
	XMLName              xml.Name  `xml:"procedimentosRevisao"`
	Data                 string    `xml:"data"`
	HoraInicio           time.Time `xml:"horaInicio"`
	HoraFim              time.Time `xml:"horaFim"`
	Procedimento         *Cttabela `xml:"procedimento"`
	QuantidadeRealizada  int       `xml:"quantidadeRealizada"`
	ViaAcesso            string    `xml:"viaAcesso"`
	TecnicaUtilizada     string    `xml:"tecnicaUtilizada"`
	ReducaoAcrescimo     float64   `xml:"reducaoAcrescimo"`
	Valor                float64   `xml:"valor"`
	ValorTotal           float64   `xml:"valorTotal"`
	JustificativaRevisao string    `xml:"justificativaRevisao"`
}

// CtprocedimentoRevisao ...
type CtprocedimentoRevisao struct {
	XMLName              xml.Name                `xml:"ct_procedimentoRevisao"`
	ProcedimentosRevisao []*ProcedimentosRevisao `xml:"procedimentosRevisao"`
}

// ProcedimentoSolicitado ...
type ProcedimentoSolicitado struct {
	XMLName              xml.Name  `xml:"procedimentoSolicitado"`
	QuantidadeSolicitada int       `xml:"quantidadeSolicitada"`
	Procedimento         *Cttabela `xml:"procedimento"`
}

// CtprocedimentosSolicitados ...
type CtprocedimentosSolicitados struct {
	XMLName                xml.Name                  `xml:"ct_procedimentosSolicitados"`
	ProcedimentoSolicitado []*ProcedimentoSolicitado `xml:"procedimentoSolicitado"`
}

// CtprofissionalExecutante ...
type CtprofissionalExecutante struct {
	XMLName              xml.Name                `xml:"ct_profissionalExecutante"`
	NomeExecutante       string                  `xml:"nomeExecutante"`
	ConselhoProfissional *CtconselhoProfissional `xml:"conselhoProfissional"`
	CodigoCBOS           string                  `xml:"codigoCBOS"`
}

// RelacaoAnexo ...
type RelacaoAnexo struct {
	XMLName             xml.Name `xml:"relacaoAnexo"`
	NumeroGuiaPrincipal []string `xml:"numeroGuiaPrincipal"`
}

// ProtocoloRecebimento ...
type ProtocoloRecebimento struct {
	XMLName                    xml.Name                      `xml:"protocoloRecebimento"`
	NumeroProtocoloRecebimento string                        `xml:"numeroProtocoloRecebimento"`
	DadosOperadora             *CtidentificacaoFontePagadora `xml:"dadosOperadora"`
	DadosPrestador             *Ctcontratado                 `xml:"dadosPrestador"`
	DataEnvioAnexo             string                        `xml:"dataEnvioAnexo"`
	NumeroLote                 string                        `xml:"numeroLote"`
	QuantidadeAnexo            int                           `xml:"quantidadeAnexo"`
	RelacaoAnexo               *RelacaoAnexo                 `xml:"relacaoAnexo"`
	Observacao                 string                        `xml:"observacao"`
}

// CtprotocoloRecebimentoAnexo ...
type CtprotocoloRecebimentoAnexo struct {
	XMLName              xml.Name              `xml:"ct_protocoloRecebimentoAnexo"`
	ProtocoloRecebimento *ProtocoloRecebimento `xml:"protocoloRecebimento"`
	MensagemErro         string                `xml:"mensagemErro"`
}

// CtprotocoloRecebimento ...
type CtprotocoloRecebimento struct {
	XMLName              xml.Name              `xml:"ct_protocoloRecebimento"`
	ProtocoloRecebimento *ProtocoloRecebimento `xml:"protocoloRecebimento"`
	MensagemErro         string                `xml:"mensagemErro"`
}

// DadosGuia ...
type DadosGuia struct {
	XMLName            xml.Name `xml:"dadosGuia"`
	StatusCancelamento string   `xml:"statusCancelamento"`
	Observacao         string   `xml:"observacao"`
	*CtcabecalhoGuia
}

// GuiasCanceladas ...
type GuiasCanceladas struct {
	XMLName   xml.Name     `xml:"guiasCanceladas"`
	DadosGuia []*DadosGuia `xml:"dadosGuia"`
}

// CtreciboCancelaGuia ...
type CtreciboCancelaGuia struct {
	XMLName         xml.Name                      `xml:"ct_reciboCancelaGuia"`
	Operadora       *CtidentificacaoFontePagadora `xml:"operadora"`
	GuiasCanceladas *GuiasCanceladas              `xml:"guiasCanceladas"`
}

// CtretornoElegibilidade ...
type CtretornoElegibilidade struct {
	XMLName             xml.Name                      `xml:"ct_retornoElegibilidade"`
	DadosOperadora      *CtidentificacaoFontePagadora `xml:"dadosOperadora"`
	DadosBeneficiario   *Ctbeneficiario               `xml:"dadosBeneficiario"`
	RespostaSolicitacao bool                          `xml:"respostaSolicitacao"`
	MotivoNegacao       *CtmotivoGlosa                `xml:"motivoNegacao"`
}

// IdentificacaoSolicitacao ...
type IdentificacaoSolicitacao struct {
	XMLName                   xml.Name                 `xml:"identificacaoSolicitacao"`
	ProfissionalSolicitante   *CtcontratadoSolicitante `xml:"profissionalSolicitante"`
	IdentificacaoBeneficiario *Ctbeneficiario          `xml:"identificacaoBeneficiario"`
	*CtcabecalhoSolicitacao
}

// IdentificacaoAutorizacao ...
type IdentificacaoAutorizacao struct {
	XMLName                  xml.Name                    `xml:"identificacaoAutorizacao"`
	IdentificacaoSolicitacao []*IdentificacaoSolicitacao `xml:"identificacaoSolicitacao"`
}

// CtsolicitaStatusAutorizacao ...
type CtsolicitaStatusAutorizacao struct {
	XMLName                  xml.Name                  `xml:"ct_solicitaStatusAutorizacao"`
	IdentificacaoAutorizacao *IdentificacaoAutorizacao `xml:"identificacaoAutorizacao"`
	DataSolicitaStatus       string                    `xml:"dataSolicitaStatus"`
}

// DadosAutorizacao ...
type DadosAutorizacao struct {
	XMLName                       xml.Name                       `xml:"dadosAutorizacao"`
	TotalOdonto                   *TotalOdonto                   `xml:"totalOdonto"`
	CtdiariaProrrogacaoAutorizada *CtdiariaProrrogacaoAutorizada `xml:"ct_diariaProrrogacaoAutorizada"`
	*CtautorizacaoProcedimento
}

// CtsituacaoAutorizacao ...
type CtsituacaoAutorizacao struct {
	XMLName          xml.Name            `xml:"ct_situacaoAutorizacao"`
	DadosAutorizacao []*DadosAutorizacao `xml:"dadosAutorizacao"`
}

// Dentes ...
type Dentes struct {
	XMLName          xml.Name `xml:"dentes"`
	ElementoDentario string   `xml:"elementoDentario"`
	CondicaoClinica  string   `xml:"condicaoClinica"`
}

// CtsituacaoClinica ...
type CtsituacaoClinica struct {
	XMLName xml.Name  `xml:"ct_situacaoClinica"`
	Dentes  []*Dentes `xml:"dentes"`
}

// CtsituacaoDentes ...
type CtsituacaoDentes struct {
	XMLName  xml.Name `xml:"ct_situacaoDentes"`
	Dente    string   `xml:"dente"`
	Obturado bool     `xml:"obturado"`
	Careado  bool     `xml:"careado"`
	Perdido  bool     `xml:"perdido"`
}

// CtsituacaoInicial ...
type CtsituacaoInicial struct {
	XMLName             xml.Name           `xml:"ct_situacaoInicial"`
	SituacaoClinica     *CtsituacaoClinica `xml:"situacaoClinica"`
	DoencaPeriodontal   bool               `xml:"doencaPeriodontal"`
	AlteracaoTecidoMole bool               `xml:"alteracaoTecidoMole"`
	Observacao          string             `xml:"observacao"`
}

// CtsolicitaElegibilidade ...
type CtsolicitaElegibilidade struct {
	XMLName           xml.Name        `xml:"ct_solicitaElegibilidade"`
	DadosPrestador    *Ctcontratado   `xml:"dadosPrestador"`
	DadosBeneficiario *Ctbeneficiario `xml:"dadosBeneficiario"`
}

// Ctsolicitante ...
type Ctsolicitante struct {
	XMLName      xml.Name                     `xml:"ct_solicitante"`
	Contratado   *CtcontratadoSolicitante     `xml:"contratado"`
	Profissional *CtidentificacaoProfissional `xml:"profissional"`
}

// CtsolicitacaoDemonstrativoPagamento ...
type CtsolicitacaoDemonstrativoPagamento struct {
	XMLName           xml.Name      `xml:"ct_solicitacaoDemonstrativoPagamento"`
	DadosPrestador    *Ctcontratado `xml:"dadosPrestador"`
	DataSolicitacao   string        `xml:"dataSolicitacao"`
	TipoDemonstrativo string        `xml:"tipoDemonstrativo"`
	DataInicial       string        `xml:"dataInicial"`
	DataFinal         string        `xml:"dataFinal"`
	NumeroProtocolo   string        `xml:"numeroProtocolo"`
}

// DetalheProtocolo ...
type DetalheProtocolo struct {
	XMLName         xml.Name `xml:"detalheProtocolo"`
	NumeroProtocolo []string `xml:"numeroProtocolo"`
}

// CtsolicitacaoStatusProtocolo ...
type CtsolicitacaoStatusProtocolo struct {
	XMLName          xml.Name          `xml:"ct_solicitacaoStatusProtocolo"`
	DadosPrestador   *Ctcontratado     `xml:"dadosPrestador"`
	DataSolicitacao  string            `xml:"dataSolicitacao"`
	DetalheProtocolo *DetalheProtocolo `xml:"detalheProtocolo"`
}

// ProcedimentosAnalisados ...
type ProcedimentosAnalisados struct {
	XMLName      xml.Name             `xml:"procedimentosAnalisados"`
	Procedimento []*CtitemSolicitacao `xml:"procedimento"`
}

// DetalheguiaMedica ...
type DetalheguiaMedica struct {
	XMLName                 xml.Name                 `xml:"detalheguiaMedica"`
	IdentificacaoGuia       *CtcabecalhoGuia         `xml:"identificacaoGuia"`
	ProcedimentosAnalisados *ProcedimentosAnalisados `xml:"procedimentosAnalisados"`
}

// DetalheguiaOdonto ...
type DetalheguiaOdonto struct {
	XMLName                 xml.Name                 `xml:"detalheguiaOdonto"`
	IdentificacaoGuia       *CtcabecalhoGuia         `xml:"identificacaoGuia"`
	ProcedimentosAnalisados *ProcedimentosAnalisados `xml:"procedimentosAnalisados"`
}

// CtstatusLote ...
type CtstatusLote struct {
	XMLName         xml.Name `xml:"ct_statusLote"`
	NumeroProtocolo string   `xml:"numeroProtocolo"`
	NumeroLote      int      `xml:"numeroLote"`
	DataEnvioLote   string   `xml:"dataEnvioLote"`
	NumeroFatura    int      `xml:"numeroFatura"`
	ValorProcessado float64  `xml:"valorProcessado"`
	ValorLiberado   float64  `xml:"valorLiberado"`
	ValorGlosa      float64  `xml:"valorGlosa"`
	Status          string   `xml:"status"`
	Guias           *Guias   `xml:"guias"`
}

// CtStatusProtocolo ...
type CtStatusProtocolo struct {
	XMLName                    xml.Name                      `xml:"ct_StatusProtocolo"`
	IdentificacaoFontePagadora *CtidentificacaoFontePagadora `xml:"identificacaoFontePagadora"`
	StatusProtocolo            string                        `xml:"statusProtocolo"`
	DadosPrestador             *Ctcontratado                 `xml:"dadosPrestador"`
	CNESPrestador              string                        `xml:"CNESPrestador"`
	Lote                       *Lote                         `xml:"lote"`
}

// Cttabela ...
type Cttabela struct {
	XMLName    xml.Name `xml:"ct_tabela"`
	Codigo     string   `xml:"codigo"`
	TipoTabela string   `xml:"tipoTabela"`
	Descricao  string   `xml:"descricao"`
}

// CttempoEvolucaoDoenca ...
type CttempoEvolucaoDoenca struct {
	XMLName      xml.Name `xml:"ct_tempoEvolucaoDoenca"`
	Valor        int      `xml:"valor"`
	UnidadeTempo string   `xml:"unidadeTempo"`
}

// CttotalDemoOdonto ...
type CttotalDemoOdonto struct {
	XMLName                  xml.Name `xml:"ct_totalDemoOdonto"`
	ValorTotalGeralGlosa     float64  `xml:"valorTotalGeralGlosa"`
	ValorTotalGeralLiberado  float64  `xml:"valorTotalGeralLiberado"`
	ValorTotalProcessadoGuia float64  `xml:"valorTotalProcessadoGuia"`
}

// CttotaisOdonto ...
type CttotaisOdonto struct {
	XMLName          xml.Name `xml:"ct_totaisOdonto"`
	ServicoExecutado float64  `xml:"servicoExecutado"`
	Taxas            float64  `xml:"taxas"`
	Materiais        float64  `xml:"materiais"`
	Medicamentos     float64  `xml:"medicamentos"`
	TotalGeral       float64  `xml:"totalGeral"`
}

// CttratamenteOdontoRealizado ...
type CttratamenteOdontoRealizado struct {
	XMLName      xml.Name  `xml:"ct_tratamenteOdontoRealizado"`
	Data         string    `xml:"data"`
	Procedimento *Cttabela `xml:"procedimento"`
	Dente        string    `xml:"dente"`
	Face         string    `xml:"face"`
}

// CttratamentoOdontoSolicitado ...
type CttratamentoOdontoSolicitado struct {
	XMLName      xml.Name  `xml:"ct_tratamentoOdontoSolicitado"`
	Procedimento *Cttabela `xml:"procedimento"`
	Dente        string    `xml:"dente"`
	Face         string    `xml:"face"`
}

// CtvalorTotalServicos ...
type CtvalorTotalServicos struct {
	XMLName            xml.Name `xml:"ct_valorTotalServicos"`
	ServicosExecutados float64  `xml:"servicosExecutados"`
	Diarias            float64  `xml:"diarias"`
	Taxas              float64  `xml:"taxas"`
	Materiais          float64  `xml:"materiais"`
	Medicamentos       float64  `xml:"medicamentos"`
	Gases              float64  `xml:"gases"`
	TotalGeral         float64  `xml:"totalGeral"`
}
