// Code generated by xgen. DO NOT EDIT.

package tiss

import (
	"encoding/xml"
	"time"
)

// OpmeSolicitada ...
type OpmeSolicitada struct {
	XMLName                  xml.Name             `xml:"opmeSolicitada"`
	IdentificacaoOPME        *CtprocedimentoDados `xml:"identificacaoOPME"`
	OpcaoFabricante          string               `xml:"opcaoFabricante"`
	QuantidadeSolicitada     int                  `xml:"quantidadeSolicitada"`
	ValorSolicitado          float64              `xml:"valorSolicitado"`
	RegistroANVISA           string               `xml:"registroANVISA"`
	CodigoRefFabricante      string               `xml:"codigoRefFabricante"`
	AutorizacaoFuncionamento string               `xml:"autorizacaoFuncionamento"`
}

// OpmeSolicitadas ...
type OpmeSolicitadas struct {
	XMLName        xml.Name          `xml:"opmeSolicitadas"`
	OpmeSolicitada []*OpmeSolicitada `xml:"opmeSolicitada"`
}

// CtmanexoSolicitacaoOPME ...
type CtmanexoSolicitacaoOPME struct {
	XMLName                 xml.Name             `xml:"ctm_anexoSolicitacaoOPME"`
	CabecalhoAnexo          *CtanexoCabecalho    `xml:"cabecalhoAnexo"`
	DadosBeneficiario       *CtbeneficiarioDados `xml:"dadosBeneficiario"`
	ProfissionalSolicitante *CtmanexoSolicitante `xml:"profissionalSolicitante"`
	JustificativaTecnica    string               `xml:"justificativaTecnica"`
	EspecificacaoMaterial   string               `xml:"especificacaoMaterial"`
	OpmeSolicitadas         *OpmeSolicitadas     `xml:"opmeSolicitadas"`
	Observacao              string               `xml:"Observacao"`
}

// DiagnosticoOncologicoQuimioterapia ...
type DiagnosticoOncologicoQuimioterapia struct {
	XMLName           xml.Name                 `xml:"diagnosticoOncologicoQuimioterapia"`
	DiagQuimio        *CtdiagnosticoOncologico `xml:"diagQuimio"`
	Tumor             string                   `xml:"tumor"`
	Nodulo            string                   `xml:"nodulo"`
	Metastase         string                   `xml:"metastase"`
	TipoQuimioterapia string                   `xml:"tipoQuimioterapia"`
	PlanoTerapeutico  string                   `xml:"planoTerapeutico"`
}

// DrogasSolicitadas ...
type DrogasSolicitadas struct {
	XMLName         xml.Name               `xml:"drogasSolicitadas"`
	DrogaSolicitada []*CtdrogasSolicitadas `xml:"drogaSolicitada"`
}

// TratamentosAnteriores ...
type TratamentosAnteriores struct {
	XMLName        xml.Name `xml:"tratamentosAnteriores"`
	Cirurgia       string   `xml:"cirurgia"`
	Datacirurgia   string   `xml:"datacirurgia"`
	AreaIrradiada  string   `xml:"areaIrradiada"`
	DataIrradiacao string   `xml:"dataIrradiacao"`
}

// CtmanexoSolicitacaoQuimio ...
type CtmanexoSolicitacaoQuimio struct {
	XMLName                            xml.Name                            `xml:"ctm_anexoSolicitacaoQuimio"`
	CabecalhoAnexo                     *CtanexoCabecalho                   `xml:"cabecalhoAnexo"`
	DadosBeneficiario                  *CtbeneficiarioDados                `xml:"dadosBeneficiario"`
	DadosComplementaresBeneficiario    *CtdadosComplementaresBeneficiario  `xml:"dadosComplementaresBeneficiario"`
	MedicoSolicitante                  *CtmanexoSolicitante                `xml:"medicoSolicitante"`
	DiagnosticoOncologicoQuimioterapia *DiagnosticoOncologicoQuimioterapia `xml:"diagnosticoOncologicoQuimioterapia"`
	DrogasSolicitadas                  *DrogasSolicitadas                  `xml:"drogasSolicitadas"`
	TratamentosAnteriores              *TratamentosAnteriores              `xml:"tratamentosAnteriores"`
	NumeroCiclos                       int                                 `xml:"numeroCiclos"`
	CicloAtual                         int                                 `xml:"cicloAtual"`
	DiasCicloAtual                     int                                 `xml:"diasCicloAtual"`
	IntervaloCiclos                    int                                 `xml:"intervaloCiclos"`
	Observacao                         string                              `xml:"observacao"`
}

// DiagnosticoOncologicoRadio ...
type DiagnosticoOncologicoRadio struct {
	XMLName           xml.Name                 `xml:"diagnosticoOncologicoRadio"`
	DiagRadio         *CtdiagnosticoOncologico `xml:"diagRadio"`
	DiagnosticoImagem string                   `xml:"diagnosticoImagem"`
}

// CtmanexoSolicitacaoRadio ...
type CtmanexoSolicitacaoRadio struct {
	XMLName                         xml.Name                                `xml:"ctm_anexoSolicitacaoRadio"`
	CabecalhoAnexo                  *CtanexoCabecalho                       `xml:"cabecalhoAnexo"`
	DadosBeneficiario               *CtbeneficiarioDados                    `xml:"dadosBeneficiario"`
	DadosComplementaresBeneficiario *CtdadosComplementaresBeneficiarioRadio `xml:"dadosComplementaresBeneficiario"`
	MedicoSolicitante               *CtmanexoSolicitante                    `xml:"medicoSolicitante"`
	DiagnosticoOncologicoRadio      *DiagnosticoOncologicoRadio             `xml:"diagnosticoOncologicoRadio"`
	TratamentosAnteriores           *TratamentosAnteriores                  `xml:"tratamentosAnteriores"`
	NumeroCampos                    int                                     `xml:"numeroCampos"`
	DoseCampo                       int                                     `xml:"doseCampo"`
	DoseTotal                       int                                     `xml:"doseTotal"`
	NrDias                          int                                     `xml:"nrDias"`
	DtPrevistaInicio                string                                  `xml:"dtPrevistaInicio"`
	Observacao                      string                                  `xml:"observacao"`
}

// CtmanexoSolicitante ...
type CtmanexoSolicitante struct {
	XMLName              xml.Name `xml:"ctm_anexoSolicitante"`
	NomeProfissional     string   `xml:"nomeProfissional"`
	TelefoneProfissional string   `xml:"telefoneProfissional"`
	EmailProfissional    string   `xml:"emailProfissional"`
}

// CtmautorizacaoProrrogacao ...
type CtmautorizacaoProrrogacao struct {
	XMLName                xml.Name               `xml:"ctm_autorizacaoProrrogacao"`
	AutorizacaoDosServicos *CtmautorizacaoServico `xml:"autorizacaoDosServicos"`
	NomeContratado         string                 `xml:"nomeContratado"`
	DiariasAutorizadas     int                    `xml:"diariasAutorizadas"`
	AcomodacaoAutorizada   string                 `xml:"acomodacaoAutorizada"`
	JustificativaOperadora string                 `xml:"justificativaOperadora"`
}

// CtmautorizacaoInternacao ...
type CtmautorizacaoInternacao struct {
	XMLName                  xml.Name               `xml:"ctm_autorizacaoInternacao"`
	AutorizacaoDosServicos   *CtmautorizacaoServico `xml:"autorizacaoDosServicos"`
	DataProvavelAdmissao     string                 `xml:"dataProvavelAdmissao"`
	QtdDiariasAutorizadas    int                    `xml:"qtdDiariasAutorizadas"`
	TipoAcomodacaoAutorizada string                 `xml:"tipoAcomodacaoAutorizada"`
}

// MotivosNegativa ...
type MotivosNegativa struct {
	XMLName        xml.Name         `xml:"motivosNegativa"`
	MotivoNegativa []*CtmotivoGlosa `xml:"motivoNegativa"`
}

// ServicosAutorizadosOPME ...
type ServicosAutorizadosOPME struct {
	XMLName xml.Name `xml:"servicosAutorizadosOPME"`
	*CtprocedimentoAutorizado
}

// CtmautorizacaoOPME ...
type CtmautorizacaoOPME struct {
	XMLName                 xml.Name                   `xml:"ctm_autorizacaoOPME"`
	DadosAutorizacao        *CtautorizacaoDados        `xml:"dadosAutorizacao"`
	DadosBeneficiario       *CtbeneficiarioDados       `xml:"dadosBeneficiario"`
	Nomebeneficiario        string                     `xml:"nomebeneficiario"`
	NomeSocialBeneficiario  string                     `xml:"nomeSocialBeneficiario"`
	StatusSolicitacao       string                     `xml:"statusSolicitacao"`
	MotivosNegativa         *MotivosNegativa           `xml:"motivosNegativa"`
	PrestadorAutorizado     *CtcontratadoDados         `xml:"prestadorAutorizado"`
	ServicosAutorizadosOPME []*ServicosAutorizadosOPME `xml:"servicosAutorizadosOPME"`
}

// CtmautorizacaoRadio ...
type CtmautorizacaoRadio struct {
	XMLName                         xml.Name                                `xml:"ctm_autorizacaoRadio"`
	DadosAutorizacao                *CtautorizacaoDados                     `xml:"dadosAutorizacao"`
	NumeroCarteira                  string                                  `xml:"numeroCarteira"`
	NomeBeneficiario                string                                  `xml:"nomeBeneficiario"`
	NomeSocialBeneficiario          string                                  `xml:"nomeSocialBeneficiario"`
	StatusSolicitacao               string                                  `xml:"statusSolicitacao"`
	DadosComplementaresBeneficiario *CtdadosComplementaresBeneficiarioRadio `xml:"dadosComplementaresBeneficiario"`
	MedicoSolicitante               *CtmanexoSolicitante                    `xml:"medicoSolicitante"`
	DiagnosticoOncologicoRadio      *DiagnosticoOncologicoRadio             `xml:"diagnosticoOncologicoRadio"`
	TratamentosAnteriores           *TratamentosAnteriores                  `xml:"tratamentosAnteriores"`
	NumeroCampos                    int                                     `xml:"numeroCampos"`
	DoseCampo                       int                                     `xml:"doseCampo"`
	DoseTotal                       int                                     `xml:"doseTotal"`
	NrDias                          int                                     `xml:"nrDias"`
	DtPrevistaInicio                string                                  `xml:"dtPrevistaInicio"`
	MotivosNegativa                 *MotivosNegativa                        `xml:"motivosNegativa"`
}

// CtmautorizacaoQuimio ...
type CtmautorizacaoQuimio struct {
	XMLName                            xml.Name                            `xml:"ctm_autorizacaoQuimio"`
	DadosAutorizacao                   *CtautorizacaoDados                 `xml:"dadosAutorizacao"`
	NumeroCarteira                     string                              `xml:"numeroCarteira"`
	StatusSolicitacao                  string                              `xml:"statusSolicitacao"`
	NomeBeneficiario                   string                              `xml:"nomeBeneficiario"`
	NomeSocialBeneficiario             string                              `xml:"nomeSocialBeneficiario"`
	DadosComplementaresBeneficiario    *CtdadosComplementaresBeneficiario  `xml:"dadosComplementaresBeneficiario"`
	MedicoSolicitante                  *CtmanexoSolicitante                `xml:"medicoSolicitante"`
	DiagnosticoOncologicoQuimioterapia *DiagnosticoOncologicoQuimioterapia `xml:"diagnosticoOncologicoQuimioterapia"`
	DrogasSolicitadas                  *DrogasSolicitadas                  `xml:"drogasSolicitadas"`
	TratamentosAnteriores              *TratamentosAnteriores              `xml:"tratamentosAnteriores"`
	NumeroCiclos                       int                                 `xml:"numeroCiclos"`
	CicloAtual                         int                                 `xml:"cicloAtual"`
	DiasCicloAtual                     int                                 `xml:"diasCicloAtual"`
	IntervaloCiclos                    int                                 `xml:"intervaloCiclos"`
	MotivosNegativa                    *MotivosNegativa                    `xml:"motivosNegativa"`
}

// PrestadorAutorizado ...
type PrestadorAutorizado struct {
	XMLName         xml.Name           `xml:"prestadorAutorizado"`
	DadosContratado *CtcontratadoDados `xml:"dadosContratado"`
	CnesContratado  string             `xml:"cnesContratado"`
}

// ServicosAutorizados ...
type ServicosAutorizados struct {
	XMLName           xml.Name                    `xml:"servicosAutorizados"`
	ServicoAutorizado []*CtprocedimentoAutorizado `xml:"servicoAutorizado"`
}

// CtmautorizacaoServico ...
type CtmautorizacaoServico struct {
	XMLName                xml.Name              `xml:"ctm_autorizacaoServico"`
	DadosAutorizacao       *CtautorizacaoDados   `xml:"dadosAutorizacao"`
	TipoEtapaAutorizacao   *Sttexto1             `xml:"tipoEtapaAutorizacao"`
	DadosBeneficiario      *CtbeneficiarioDados  `xml:"dadosBeneficiario"`
	NomeBeneficiario       string                `xml:"nomeBeneficiario"`
	NomeSocialBeneficiario string                `xml:"nomeSocialBeneficiario"`
	PrestadorAutorizado    *PrestadorAutorizado  `xml:"prestadorAutorizado"`
	StatusSolicitacao      string                `xml:"statusSolicitacao"`
	MotivosNegativa        *MotivosNegativa      `xml:"motivosNegativa"`
	ServicosAutorizados    *ServicosAutorizados  `xml:"servicosAutorizados"`
	Observacao             string                `xml:"observacao"`
	AutorizacaoQuimio      *CtmautorizacaoQuimio `xml:"autorizacaoQuimio"`
	AutorizacaoRadio       *CtmautorizacaoRadio  `xml:"autorizacaoRadio"`
}

// DadosInternacao ...
type DadosInternacao struct {
	XMLName            xml.Name `xml:"dadosInternacao"`
	MotivoEncerramento string   `xml:"motivoEncerramento"`
	TipoInternacao     string   `xml:"tipoInternacao"`
}

// CtmbeneficiarioComunicacao ...
type CtmbeneficiarioComunicacao struct {
	XMLName           xml.Name             `xml:"ctm_beneficiarioComunicacao"`
	DadosBeneficiario *CtbeneficiarioDados `xml:"dadosBeneficiario"`
	DataEvento        string               `xml:"dataEvento"`
	TipoEvento        string               `xml:"tipoEvento"`
	DadosInternacao   *DadosInternacao     `xml:"dadosInternacao"`
}

// CtmbeneficiarioComunicacaoRet ...
type CtmbeneficiarioComunicacaoRet struct {
	XMLName                xml.Name             `xml:"ctm_beneficiarioComunicacaoRet"`
	DadosBeneficiario      *CtbeneficiarioDados `xml:"dadosBeneficiario"`
	NomeBeneficiario       string               `xml:"nomeBeneficiario"`
	NomeSocialBeneficiario string               `xml:"nomeSocialBeneficiario"`
	TipoEvento             string               `xml:"tipoEvento"`
	DadosInternacao        *DadosInternacao     `xml:"dadosInternacao"`
}

// CtmbeneficiarioComunicacaoRecibo ...
type CtmbeneficiarioComunicacaoRecibo struct {
	XMLName                    xml.Name                       `xml:"ctm_beneficiarioComunicacaoRecibo"`
	StatusComunicacao          string                         `xml:"statusComunicacao"`
	BeneficiarioComunicacaoRet *CtmbeneficiarioComunicacaoRet `xml:"beneficiarioComunicacaoRet"`
	CodigoGlosa                string                         `xml:"codigoGlosa"`
}

// Procedimento ...
type Procedimento struct {
	XMLName            xml.Name `xml:"procedimento"`
	CodigoTabela       string   `xml:"codigoTabela"`
	CodigoProcedimento string   `xml:"codigoProcedimento"`
	ValorProcedimento  float64  `xml:"valorProcedimento"`
}

// CtmconsultaAtendimento ...
type CtmconsultaAtendimento struct {
	XMLName           xml.Name      `xml:"ctm_consultaAtendimento"`
	CoberturaEspecial string        `xml:"coberturaEspecial"`
	RegimeAtendimento string        `xml:"regimeAtendimento"`
	SaudeOcupacional  string        `xml:"saudeOcupacional"`
	DataAtendimento   string        `xml:"dataAtendimento"`
	TipoConsulta      string        `xml:"tipoConsulta"`
	Procedimento      *Procedimento `xml:"procedimento"`
}

// ContratadoExecutante ...
type ContratadoExecutante struct {
	XMLName xml.Name `xml:"contratadoExecutante"`
	CNES    string   `xml:"CNES"`
	*CtcontratadoDados
}

// CtmconsultaGuia ...
type CtmconsultaGuia struct {
	XMLName                xml.Name                       `xml:"ctm_consultaGuia"`
	CabecalhoConsulta      *CtguiaCabecalho               `xml:"cabecalhoConsulta"`
	NumeroGuiaOperadora    string                         `xml:"numeroGuiaOperadora"`
	AusenciaCodValidacao   string                         `xml:"ausenciaCodValidacao"`
	CodValidacao           string                         `xml:"codValidacao"`
	DadosBeneficiario      *CtbeneficiarioDados           `xml:"dadosBeneficiario"`
	ContratadoExecutante   *ContratadoExecutante          `xml:"contratadoExecutante"`
	ProfissionalExecutante *CtcontratadoProfissionalDados `xml:"profissionalExecutante"`
	IndicacaoAcidente      string                         `xml:"indicacaoAcidente"`
	DadosAtendimento       *CtmconsultaAtendimento        `xml:"dadosAtendimento"`
	Observacao             string                         `xml:"observacao"`
	AssinaturaDigitalGuia  *Signature                     `xml:"assinaturaDigitalGuia"`
}

// DadosPrestador ...
type DadosPrestador struct {
	XMLName         xml.Name           `xml:"dadosPrestador"`
	DadosContratado *CtcontratadoDados `xml:"dadosContratado"`
	CNES            string             `xml:"CNES"`
}

// DadosProtocolo ...
type DadosProtocolo struct {
	XMLName xml.Name `xml:"dadosProtocolo"`
	*CtcontaMedicaResumo
}

// DadosConta ...
type DadosConta struct {
	XMLName        xml.Name          `xml:"dadosConta"`
	DadosProtocolo []*DadosProtocolo `xml:"dadosProtocolo"`
}

// CtmdemonstrativoAnaliseConta ...
type CtmdemonstrativoAnaliseConta struct {
	XMLName                xml.Name                  `xml:"ctm_demonstrativoAnaliseConta"`
	CabecalhoDemonstrativo *CtdemonstrativoCabecalho `xml:"cabecalhoDemonstrativo"`
	DadosPrestador         *DadosPrestador           `xml:"dadosPrestador"`
	DadosConta             *DadosConta               `xml:"dadosConta"`
	ValorInformadoGeral    float64                   `xml:"valorInformadoGeral"`
	ValorProcessadoGeral   float64                   `xml:"valorProcessadoGeral"`
	ValorLiberadoGeral     float64                   `xml:"valorLiberadoGeral"`
	ValorGlosaGeral        float64                   `xml:"valorGlosaGeral"`
}

// DadosContratado ...
type DadosContratado struct {
	XMLName        xml.Name           `xml:"dadosContratado"`
	DadosPrestador *CtcontratadoDados `xml:"dadosPrestador"`
	CNES           string             `xml:"CNES"`
}

// DadosResumo ...
type DadosResumo struct {
	XMLName           xml.Name                      `xml:"dadosResumo"`
	RelacaoProtocolos []*CtdadosResumoDemonstrativo `xml:"relacaoProtocolos"`
}

// TotaisBrutosPorData ...
type TotaisBrutosPorData struct {
	XMLName                xml.Name `xml:"totaisBrutosPorData"`
	TotalInformadoPorData  float64  `xml:"totalInformadoPorData"`
	TotalProcessadoPorData float64  `xml:"totalProcessadoPorData"`
	TotaLiberadoPorData    float64  `xml:"totaLiberadoPorData"`
	TotalGlosaPorData      float64  `xml:"totalGlosaPorData"`
}

// DebitosCreditosPorData ...
type DebitosCreditosPorData struct {
	XMLName         xml.Name       `xml:"debitosCreditosPorData"`
	DebitosCreditos []*Ctdescontos `xml:"debitosCreditos"`
}

// TotaisLiquidosPorData ...
type TotaisLiquidosPorData struct {
	XMLName              xml.Name `xml:"totaisLiquidosPorData"`
	TotalDebitosPorData  float64  `xml:"totalDebitosPorData"`
	TotalCreditosPorData float64  `xml:"totalCreditosPorData"`
	LiquidoPorData       float64  `xml:"liquidoPorData"`
}

// PagamentosPorData ...
type PagamentosPorData struct {
	XMLName                xml.Name                `xml:"pagamentosPorData"`
	DadosPagamento         *CtpagamentoDados       `xml:"dadosPagamento"`
	DadosResumo            *DadosResumo            `xml:"dadosResumo"`
	TotaisBrutosPorData    *TotaisBrutosPorData    `xml:"totaisBrutosPorData"`
	DebitosCreditosPorData *DebitosCreditosPorData `xml:"debitosCreditosPorData"`
	TotaisLiquidosPorData  *TotaisLiquidosPorData  `xml:"totaisLiquidosPorData"`
}

// Pagamentos ...
type Pagamentos struct {
	XMLName           xml.Name             `xml:"pagamentos"`
	PagamentosPorData []*PagamentosPorData `xml:"pagamentosPorData"`
}

// TotaisBrutosDemonstrativo ...
type TotaisBrutosDemonstrativo struct {
	XMLName              xml.Name `xml:"totaisBrutosDemonstrativo"`
	ValorInformadoBruto  float64  `xml:"valorInformadoBruto"`
	ValorProcessadoBruto float64  `xml:"valorProcessadoBruto"`
	ValorLiberadoBruto   float64  `xml:"valorLiberadoBruto"`
	ValorGlosaBruto      float64  `xml:"valorGlosaBruto"`
}

// TotaisLiquidosDemonstrativo ...
type TotaisLiquidosDemonstrativo struct {
	XMLName                    xml.Name `xml:"totaisLiquidosDemonstrativo"`
	TotalDebitosDemonstrativo  float64  `xml:"totalDebitosDemonstrativo"`
	TotalCreditosdemonstrativo float64  `xml:"totalCreditosdemonstrativo"`
	ValorLiberadoDemonstrativo float64  `xml:"valorLiberadoDemonstrativo"`
}

// TotaisDemonstrativo ...
type TotaisDemonstrativo struct {
	XMLName                      xml.Name                     `xml:"totaisDemonstrativo"`
	TotaisBrutosDemonstrativo    *TotaisBrutosDemonstrativo   `xml:"totaisBrutosDemonstrativo"`
	DebitosCreditosDemonstrativo []*Ctdescontos               `xml:"debitosCreditosDemonstrativo"`
	TotaisLiquidosDemonstrativo  *TotaisLiquidosDemonstrativo `xml:"totaisLiquidosDemonstrativo"`
}

// CtmdemonstrativoPagamento ...
type CtmdemonstrativoPagamento struct {
	XMLName                xml.Name                  `xml:"ctm_demonstrativoPagamento"`
	CabecalhoDemonstrativo *CtdemonstrativoCabecalho `xml:"cabecalhoDemonstrativo"`
	DadosContratado        *DadosContratado          `xml:"dadosContratado"`
	Pagamentos             *Pagamentos               `xml:"pagamentos"`
	TotaisDemonstrativo    *TotaisDemonstrativo      `xml:"totaisDemonstrativo"`
	Observacao             string                    `xml:"observacao"`
}

// GuiasTISS ...
type GuiasTISS struct {
	XMLName              xml.Name                      `xml:"guiasTISS"`
	GuiaSPSADT           []*CtmspsadtGuia              `xml:"guiaSP-SADT"`
	GuiaResumoInternacao []*CtminternacaoResumoGuia    `xml:"guiaResumoInternacao"`
	GuiaHonorarios       []*CtmhonorarioIndividualGuia `xml:"guiaHonorarios"`
	GuiaConsulta         []*CtmconsultaGuia            `xml:"guiaConsulta"`
	GuiaOdonto           []*CtoguiaOdontologia         `xml:"guiaOdonto"`
}

// CtmguiaLote ...
type CtmguiaLote struct {
	XMLName    xml.Name   `xml:"ctm_guiaLote"`
	NumeroLote string     `xml:"numeroLote"`
	GuiasTISS  *GuiasTISS `xml:"guiasTISS"`
}

// Beneficiario ...
type Beneficiario struct {
	XMLName        xml.Name `xml:"beneficiario"`
	NumeroCarteira string   `xml:"numeroCarteira"`
	AtendimentoRN  string   `xml:"atendimentoRN"`
}

// CodigoContratado ...
type CodigoContratado struct {
	XMLName             xml.Name `xml:"codigoContratado"`
	CodigoNaOperadora   string   `xml:"codigoNaOperadora"`
	CnpjLocalExecutante string   `xml:"cnpjLocalExecutante"`
}

// LocalContratado ...
type LocalContratado struct {
	XMLName          xml.Name          `xml:"localContratado"`
	CodigoContratado *CodigoContratado `xml:"codigoContratado"`
	NomeContratado   string            `xml:"nomeContratado"`
	Cnes             string            `xml:"cnes"`
}

// DadosContratadoExecutante ...
type DadosContratadoExecutante struct {
	XMLName                  xml.Name `xml:"dadosContratadoExecutante"`
	CodigonaOperadora        string   `xml:"codigonaOperadora"`
	CnesContratadoExecutante string   `xml:"cnesContratadoExecutante"`
}

// ProcedimentosRealizados ...
type ProcedimentosRealizados struct {
	XMLName               xml.Name                             `xml:"procedimentosRealizados"`
	ProcedimentoRealizado []*CtprocedimentoExecutadoHonorIndiv `xml:"procedimentoRealizado"`
}

// CtmhonorarioIndividualGuia ...
type CtmhonorarioIndividualGuia struct {
	XMLName                   xml.Name                   `xml:"ctm_honorarioIndividualGuia"`
	CabecalhoGuia             *CtguiaCabecalho           `xml:"cabecalhoGuia"`
	GuiaSolicInternacao       string                     `xml:"guiaSolicInternacao"`
	Senha                     string                     `xml:"senha"`
	NumeroGuiaOperadora       string                     `xml:"numeroGuiaOperadora"`
	Beneficiario              *Beneficiario              `xml:"beneficiario"`
	LocalContratado           *LocalContratado           `xml:"localContratado"`
	DadosContratadoExecutante *DadosContratadoExecutante `xml:"dadosContratadoExecutante"`
	DadosInternacao           *DadosInternacao           `xml:"dadosInternacao"`
	ProcedimentosRealizados   *ProcedimentosRealizados   `xml:"procedimentosRealizados"`
	Observacao                string                     `xml:"observacao"`
	ValorTotalHonorarios      float64                    `xml:"valorTotalHonorarios"`
	DataEmissaoGuia           string                     `xml:"dataEmissaoGuia"`
	AssinaturaDigitalGuia     *Signature                 `xml:"assinaturaDigitalGuia"`
}

// Declaracoes ...
type Declaracoes struct {
	XMLName           xml.Name `xml:"declaracoes"`
	DeclaracaoNascido string   `xml:"declaracaoNascido"`
	DiagnosticoObito  string   `xml:"diagnosticoObito"`
	DeclaracaoObito   string   `xml:"declaracaoObito"`
	IndicadorDORN     string   `xml:"indicadorDORN"`
}

// CtminternacaoDados ...
type CtminternacaoDados struct {
	XMLName               xml.Name       `xml:"ctm_internacaoDados"`
	CaraterAtendimento    string         `xml:"caraterAtendimento"`
	TipoFaturamento       string         `xml:"tipoFaturamento"`
	DataInicioFaturamento string         `xml:"dataInicioFaturamento"`
	HoraInicioFaturamento time.Time      `xml:"horaInicioFaturamento"`
	DataFinalFaturamento  string         `xml:"dataFinalFaturamento"`
	HoraFinalFaturamento  time.Time      `xml:"horaFinalFaturamento"`
	TipoInternacao        string         `xml:"tipoInternacao"`
	RegimeInternacao      string         `xml:"regimeInternacao"`
	Declaracoes           []*Declaracoes `xml:"declaracoes"`
}

// CtminternacaoDadosSaida ...
type CtminternacaoDadosSaida struct {
	XMLName            xml.Name `xml:"ctm_internacaoDadosSaida"`
	Diagnostico        []string `xml:"diagnostico"`
	IndicadorAcidente  string   `xml:"indicadorAcidente"`
	MotivoEncerramento string   `xml:"motivoEncerramento"`
}

// DadosExecutante ...
type DadosExecutante struct {
	XMLName              xml.Name           `xml:"dadosExecutante"`
	ContratadoExecutante *CtcontratadoDados `xml:"contratadoExecutante"`
	CNES                 string             `xml:"CNES"`
}

// ProcedimentosExecutados ...
type ProcedimentosExecutados struct {
	XMLName               xml.Name                      `xml:"procedimentosExecutados"`
	ProcedimentoExecutado []*CtprocedimentoExecutadoInt `xml:"procedimentoExecutado"`
}

// CtminternacaoResumoGuia ...
type CtminternacaoResumoGuia struct {
	XMLName                         xml.Name                 `xml:"ctm_internacaoResumoGuia"`
	CabecalhoGuia                   *CtguiaCabecalho         `xml:"cabecalhoGuia"`
	NumeroGuiaSolicitacaoInternacao string                   `xml:"numeroGuiaSolicitacaoInternacao"`
	DadosAutorizacao                *CtautorizacaoInternacao `xml:"dadosAutorizacao"`
	DadosBeneficiario               *CtbeneficiarioDados     `xml:"dadosBeneficiario"`
	DadosExecutante                 *DadosExecutante         `xml:"dadosExecutante"`
	DadosInternacao                 *CtminternacaoDados      `xml:"dadosInternacao"`
	DadosSaidaInternacao            *CtminternacaoDadosSaida `xml:"dadosSaidaInternacao"`
	ProcedimentosExecutados         *ProcedimentosExecutados `xml:"procedimentosExecutados"`
	ValorTotal                      *CtguiaValorTotal        `xml:"valorTotal"`
	OutrasDespesas                  *CtoutrasDespesas        `xml:"outrasDespesas"`
	Observacao                      string                   `xml:"observacao"`
	AssinaturaDigitalGuia           *Signature               `xml:"assinaturaDigitalGuia"`
}

// IdentificacaoSolicitante ...
type IdentificacaoSolicitante struct {
	XMLName                     xml.Name                       `xml:"identificacaoSolicitante"`
	DadosDoContratado           *CtcontratadoDados             `xml:"dadosDoContratado"`
	DadosProfissionalContratado *CtcontratadoProfissionalDados `xml:"dadosProfissionalContratado"`
}

// DadosHospitalSolicitado ...
type DadosHospitalSolicitado struct {
	XMLName                   xml.Name `xml:"dadosHospitalSolicitado"`
	CodigoIndicadonaOperadora string   `xml:"codigoIndicadonaOperadora"`
	NomeContratadoIndicado    string   `xml:"nomeContratadoIndicado"`
	DataSugeridaInternacao    string   `xml:"dataSugeridaInternacao"`
}

// HipotesesDiagnosticas ...
type HipotesesDiagnosticas struct {
	XMLName           xml.Name `xml:"hipotesesDiagnosticas"`
	DiagnosticoCID    []string `xml:"diagnosticoCID"`
	IndicadorAcidente string   `xml:"indicadorAcidente"`
}

// ProcedimentosSolicitados ...
type ProcedimentosSolicitados struct {
	XMLName              xml.Name             `xml:"procedimentosSolicitados"`
	Procedimento         *CtprocedimentoDados `xml:"procedimento"`
	QuantidadeSolicitada int                  `xml:"quantidadeSolicitada"`
}

// AnexoClinico ...
type AnexoClinico struct {
	XMLName                  xml.Name                   `xml:"anexoClinico"`
	SolicitacaoQuimioterapia *CtmanexoSolicitacaoQuimio `xml:"solicitacaoQuimioterapia"`
	SolicitacaoRadioterapia  *CtmanexoSolicitacaoRadio  `xml:"solicitacaoRadioterapia"`
	SolicitacaoOPME          *CtmanexoSolicitacaoOPME   `xml:"solicitacaoOPME"`
}

// CtminternacaoSolicitacaoGuia ...
type CtminternacaoSolicitacaoGuia struct {
	XMLName                  xml.Name                    `xml:"ctm_internacaoSolicitacaoGuia"`
	RegistroANS              string                      `xml:"registroANS"`
	NumeroGuiaPrestador      string                      `xml:"numeroGuiaPrestador"`
	AusenciaCodValidacao     string                      `xml:"ausenciaCodValidacao"`
	CodValidacao             string                      `xml:"codValidacao"`
	TipoEtapaAutorizacao     *Sttexto1                   `xml:"tipoEtapaAutorizacao"`
	DadosBeneficiario        *CtbeneficiarioDados        `xml:"dadosBeneficiario"`
	IdentificacaoSolicitante *IdentificacaoSolicitante   `xml:"identificacaoSolicitante"`
	DadosHospitalSolicitado  *DadosHospitalSolicitado    `xml:"dadosHospitalSolicitado"`
	DadosInternacao          *DadosInternacao            `xml:"dadosInternacao"`
	HipotesesDiagnosticas    *HipotesesDiagnosticas      `xml:"hipotesesDiagnosticas"`
	ProcedimentosSolicitados []*ProcedimentosSolicitados `xml:"procedimentosSolicitados"`
	DataSolicitacao          string                      `xml:"dataSolicitacao"`
	Observacao               string                      `xml:"observacao"`
	AnexoClinico             *AnexoClinico               `xml:"anexoClinico"`
}

// DadosBeneficiario ...
type DadosBeneficiario struct {
	XMLName                   xml.Name  `xml:"dadosBeneficiario"`
	NumeroCarteira            string    `xml:"numeroCarteira"`
	TipoIdent                 *Sttexto2 `xml:"tipoIdent"`
	IdentificadorBeneficiario string    `xml:"identificadorBeneficiario"`
}

// ProcedimentosAdicionais ...
type ProcedimentosAdicionais struct {
	XMLName              xml.Name             `xml:"procedimentosAdicionais"`
	Procedimento         *CtprocedimentoDados `xml:"procedimento"`
	QuantidadeSolicitada int                  `xml:"quantidadeSolicitada"`
}

// AnexoClinicoProrrogacao ...
type AnexoClinicoProrrogacao struct {
	XMLName                  xml.Name                   `xml:"anexoClinicoProrrogacao"`
	SolicitacaoQuimioterapia *CtmanexoSolicitacaoQuimio `xml:"solicitacaoQuimioterapia"`
	SolicitacaoRadioterapia  *CtmanexoSolicitacaoRadio  `xml:"solicitacaoRadioterapia"`
	SolicitacaoOPME          *CtmanexoSolicitacaoOPME   `xml:"solicitacaoOPME"`
}

// CtmprorrogacaoSolicitacaoGuia ...
type CtmprorrogacaoSolicitacaoGuia struct {
	XMLName                      xml.Name                       `xml:"ctm_prorrogacaoSolicitacaoGuia"`
	RegistroANS                  string                         `xml:"registroANS"`
	NumeroGuiaPrestador          string                         `xml:"numeroGuiaPrestador"`
	NrGuiaReferenciada           string                         `xml:"nrGuiaReferenciada"`
	DadosBeneficiario            *DadosBeneficiario             `xml:"dadosBeneficiario"`
	DadosContratadoSolicitante   *CtcontratadoDados             `xml:"dadosContratadoSolicitante"`
	NomeContratadoSolicitante    string                         `xml:"nomeContratadoSolicitante"`
	DadosProfissionalSolicitante *CtcontratadoProfissionalDados `xml:"dadosProfissionalSolicitante"`
	DadosInternacao              *DadosInternacao               `xml:"dadosInternacao"`
	ProcedimentosAdicionais      []*ProcedimentosAdicionais     `xml:"procedimentosAdicionais"`
	AnexoClinicoProrrogacao      *AnexoClinicoProrrogacao       `xml:"anexoClinicoProrrogacao"`
	Observacao                   string                         `xml:"observacao"`
	DataSolicitacao              string                         `xml:"dataSolicitacao"`
}

// CtmspsadtAtendimento ...
type CtmspsadtAtendimento struct {
	XMLName            xml.Name `xml:"ctm_sp-sadtAtendimento"`
	TipoAtendimento    string   `xml:"tipoAtendimento"`
	IndicacaoAcidente  string   `xml:"indicacaoAcidente"`
	TipoConsulta       string   `xml:"tipoConsulta"`
	MotivoEncerramento string   `xml:"motivoEncerramento"`
	RegimeAtendimento  string   `xml:"regimeAtendimento"`
	SaudeOcupacional   string   `xml:"saudeOcupacional"`
}

// CtmsolicitacaoLote ...
type CtmsolicitacaoLote struct {
	XMLName                xml.Name                       `xml:"ctm_solicitacaoLote"`
	SolicitacaoSPSADT      *CtmspsadtSolicitacaoGuia      `xml:"solicitacaoSP-SADT"`
	SolicitacaoInternacao  *CtminternacaoSolicitacaoGuia  `xml:"solicitacaoInternacao"`
	SolicitacaoProrrogacao *CtmprorrogacaoSolicitacaoGuia `xml:"solicitacaoProrrogacao"`
	SolicitacaoOdontologia *CtoodontoSolicitacaoGuia      `xml:"solicitacaoOdontologia"`
}

// CabecalhoGuia ...
type CabecalhoGuia struct {
	XMLName       xml.Name `xml:"cabecalhoGuia"`
	GuiaPrincipal string   `xml:"guiaPrincipal"`
	*CtguiaCabecalho
}

// DadosSolicitante ...
type DadosSolicitante struct {
	XMLName                   xml.Name                       `xml:"dadosSolicitante"`
	ContratadoSolicitante     *CtcontratadoDados             `xml:"contratadoSolicitante"`
	NomeContratadoSolicitante string                         `xml:"nomeContratadoSolicitante"`
	ProfissionalSolicitante   *CtcontratadoProfissionalDados `xml:"profissionalSolicitante"`
}

// DadosSolicitacao ...
type DadosSolicitacao struct {
	XMLName            xml.Name `xml:"dadosSolicitacao"`
	DataSolicitacao    string   `xml:"dataSolicitacao"`
	CaraterAtendimento string   `xml:"caraterAtendimento"`
	IndicacaoClinica   string   `xml:"indicacaoClinica"`
	IndCobEspecial     string   `xml:"indCobEspecial"`
}

// CtmspsadtGuia ...
type CtmspsadtGuia struct {
	XMLName                 xml.Name                 `xml:"ctm_sp-sadtGuia"`
	CabecalhoGuia           *CabecalhoGuia           `xml:"cabecalhoGuia"`
	DadosAutorizacao        *CtautorizacaoSADT       `xml:"dadosAutorizacao"`
	DadosBeneficiario       *CtbeneficiarioDados     `xml:"dadosBeneficiario"`
	DadosSolicitante        *DadosSolicitante        `xml:"dadosSolicitante"`
	DadosSolicitacao        *DadosSolicitacao        `xml:"dadosSolicitacao"`
	DadosExecutante         *DadosExecutante         `xml:"dadosExecutante"`
	DadosAtendimento        *CtmspsadtAtendimento    `xml:"dadosAtendimento"`
	ProcedimentosExecutados *ProcedimentosExecutados `xml:"procedimentosExecutados"`
	OutrasDespesas          *CtoutrasDespesas        `xml:"outrasDespesas"`
	Observacao              string                   `xml:"observacao"`
	ValorTotal              *CtguiaValorTotal        `xml:"valorTotal"`
	AssinaturaDigitalGuia   *Signature               `xml:"assinaturaDigitalGuia"`
}

// CtmspsadtSolicitacaoGuia ...
type CtmspsadtSolicitacaoGuia struct {
	XMLName                  xml.Name                    `xml:"ctm_sp-sadtSolicitacaoGuia"`
	CabecalhoSolicitacao     *CtguiaCabecalho            `xml:"cabecalhoSolicitacao"`
	NumeroGuiaPrincipal      string                      `xml:"numeroGuiaPrincipal"`
	AusenciaCodValidacao     string                      `xml:"ausenciaCodValidacao"`
	CodValidacao             string                      `xml:"codValidacao"`
	TipoEtapaAutorizacao     *Sttexto1                   `xml:"tipoEtapaAutorizacao"`
	DadosBeneficiario        *CtbeneficiarioDados        `xml:"dadosBeneficiario"`
	DadosSolicitante         *DadosSolicitante           `xml:"dadosSolicitante"`
	CaraterAtendimento       string                      `xml:"caraterAtendimento"`
	DataSolicitacao          string                      `xml:"dataSolicitacao"`
	IndicacaoClinica         string                      `xml:"indicacaoClinica"`
	CoberturaEspecial        string                      `xml:"coberturaEspecial"`
	ProcedimentosSolicitados []*ProcedimentosSolicitados `xml:"procedimentosSolicitados"`
	DadosExecutante          *DadosExecutante            `xml:"dadosExecutante"`
	AnexoClinico             *AnexoClinico               `xml:"anexoClinico"`
	Observacao               string                      `xml:"observacao"`
}

// RecursoProtocolo ...
type RecursoProtocolo struct {
	XMLName                xml.Name `xml:"recursoProtocolo"`
	CodigoGlosaProtocolo   string   `xml:"codigoGlosaProtocolo"`
	JustificativaProtocolo string   `xml:"justificativaProtocolo"`
}

// RecursoGuiaCompleta ...
type RecursoGuiaCompleta struct {
	XMLName           xml.Name `xml:"recursoGuiaCompleta"`
	CodGlosaGuia      string   `xml:"codGlosaGuia"`
	JustificativaGuia string   `xml:"justificativaGuia"`
}

// ItensGuia ...
type ItensGuia struct {
	XMLName           xml.Name             `xml:"itensGuia"`
	SequencialItem    int                  `xml:"sequencialItem"`
	DataInicio        string               `xml:"dataInicio"`
	DataFim           string               `xml:"dataFim"`
	ProcRecurso       *CtprocedimentoDados `xml:"procRecurso"`
	GrauParticipacao  string               `xml:"grauParticipacao"`
	CodGlosaItem      string               `xml:"codGlosaItem"`
	ValorRecursado    float64              `xml:"valorRecursado"`
	JustificativaItem string               `xml:"justificativaItem"`
}

// OpcaoRecursoGuia ...
type OpcaoRecursoGuia struct {
	XMLName             xml.Name               `xml:"opcaoRecursoGuia"`
	RecursoGuiaCompleta []*RecursoGuiaCompleta `xml:"recursoGuiaCompleta"`
	ItensGuia           []*ItensGuia           `xml:"itensGuia"`
}

// RecursoGuia ...
type RecursoGuia struct {
	XMLName             xml.Name          `xml:"recursoGuia"`
	NumeroGuiaOrigem    string            `xml:"numeroGuiaOrigem"`
	NumeroGuiaOperadora string            `xml:"numeroGuiaOperadora"`
	Senha               string            `xml:"senha"`
	OpcaoRecursoGuia    *OpcaoRecursoGuia `xml:"opcaoRecursoGuia"`
}

// OpcaoRecurso ...
type OpcaoRecurso struct {
	XMLName          xml.Name          `xml:"opcaoRecurso"`
	RecursoProtocolo *RecursoProtocolo `xml:"recursoProtocolo"`
	RecursoGuia      []*RecursoGuia    `xml:"recursoGuia"`
}

// CtmrecursoGlosa ...
type CtmrecursoGlosa struct {
	XMLName                     xml.Name           `xml:"ctm_recursoGlosa"`
	RegistroANS                 string             `xml:"registroANS"`
	NumeroGuiaRecGlosaPrestador string             `xml:"numeroGuiaRecGlosaPrestador"`
	NomeOperadora               string             `xml:"nomeOperadora"`
	ObjetoRecurso               string             `xml:"objetoRecurso"`
	NumeroGuiaRecGlosaOperadora string             `xml:"numeroGuiaRecGlosaOperadora"`
	DadosContratado             *CtcontratadoDados `xml:"dadosContratado"`
	NumeroLote                  string             `xml:"numeroLote"`
	NumeroProtocolo             int                `xml:"numeroProtocolo"`
	OpcaoRecurso                *OpcaoRecurso      `xml:"opcaoRecurso"`
	ValorTotalRecursado         float64            `xml:"valorTotalRecursado"`
	DataRecurso                 string             `xml:"dataRecurso"`
}

// DenteRegiao ...
type DenteRegiao struct {
	XMLName   xml.Name `xml:"denteRegiao"`
	CodDente  string   `xml:"codDente"`
	CodRegiao string   `xml:"codRegiao"`
}

// ProcedimentosAutorizados ...
type ProcedimentosAutorizados struct {
	XMLName         xml.Name             `xml:"procedimentosAutorizados"`
	SequencialItem  int                  `xml:"sequencialItem"`
	ProcSolic       *CtprocedimentoDados `xml:"procSolic"`
	DenteRegiao     *DenteRegiao         `xml:"denteRegiao"`
	DenteFace       string               `xml:"denteFace"`
	QtdProc         int                  `xml:"qtdProc"`
	QtdUS           float64              `xml:"qtdUS"`
	ValorProc       float64              `xml:"valorProc"`
	ValorFranquia   float64              `xml:"valorFranquia"`
	Aut             string               `xml:"aut"`
	MotivosNegativa *MotivosNegativa     `xml:"motivosNegativa"`
}

// CtoautorizacaoServico ...
type CtoautorizacaoServico struct {
	XMLName                   xml.Name                    `xml:"cto_autorizacaoServico"`
	DadosAutorizacao          *CtautorizacaoDados         `xml:"dadosAutorizacao"`
	NumeroCarteira            string                      `xml:"numeroCarteira"`
	NomeBeneficiario          string                      `xml:"nomeBeneficiario"`
	NomeSocialBeneficiario    string                      `xml:"nomeSocialBeneficiario"`
	TipoIdent                 *Sttexto2                   `xml:"tipoIdent"`
	IdentificadorBeneficiario string                      `xml:"identificadorBeneficiario"`
	StatusSolicitacao         string                      `xml:"statusSolicitacao"`
	PrestadorAutorizado       *CtcontratadoDados          `xml:"prestadorAutorizado"`
	ProcedimentosAutorizados  []*ProcedimentosAutorizados `xml:"procedimentosAutorizados"`
	MotivosNegativa           *MotivosNegativa            `xml:"motivosNegativa"`
}

// CtsituacaoInicial ...
type CtsituacaoInicial struct {
	XMLName             xml.Name           `xml:"ct_situacaoInicial"`
	SituacaoClinica     *CtsituacaoClinica `xml:"situacaoClinica"`
	DoencaPeriodontal   bool               `xml:"doencaPeriodontal"`
	AlteracaoTecidoMole bool               `xml:"alteracaoTecidoMole"`
	Observacao          string             `xml:"observacao"`
}

// CtoanexoSituacaoInicial ...
type CtoanexoSituacaoInicial struct {
	XMLName                xml.Name           `xml:"cto_anexoSituacaoInicial"`
	RegistroANS            string             `xml:"registroANS"`
	NumeroGuiaAnexo        string             `xml:"numeroGuiaAnexo"`
	NumeroGuiaReferenciada string             `xml:"numeroGuiaReferenciada"`
	NumeroGuiaOperadora    string             `xml:"numeroGuiaOperadora"`
	NumeroCarteira         string             `xml:"numeroCarteira"`
	CtsituacaoInicial      *CtsituacaoInicial `xml:"ct_situacaoInicial"`
}

// CtoanexoSituacaoInicialnaGTO ...
type CtoanexoSituacaoInicialnaGTO struct {
	XMLName                xml.Name           `xml:"cto_anexoSituacaoInicialnaGTO"`
	NumeroGuiaAnexo        string             `xml:"numeroGuiaAnexo"`
	NumeroGuiaReferenciada string             `xml:"numeroGuiaReferenciada"`
	NumeroGuiaOperadora    string             `xml:"numeroGuiaOperadora"`
	CtsituacaoInicial      *CtsituacaoInicial `xml:"ct_situacaoInicial"`
}

// PeriodoProc ...
type PeriodoProc struct {
	XMLName    xml.Name `xml:"periodoProc"`
	Datainicio string   `xml:"datainicio"`
	Datafim    string   `xml:"datafim"`
}

// CabecalhoDemonstrativoOdonto ...
type CabecalhoDemonstrativoOdonto struct {
	XMLName             xml.Name     `xml:"cabecalhoDemonstrativoOdonto"`
	RegistroANS         string       `xml:"registroANS"`
	NumeroDemonstrativo string       `xml:"numeroDemonstrativo"`
	NomeOperadora       string       `xml:"nomeOperadora"`
	CnpjOper            string       `xml:"cnpjOper"`
	PeriodoProc         *PeriodoProc `xml:"periodoProc"`
}

// CpfCNPJContratado ...
type CpfCNPJContratado struct {
	XMLName       xml.Name `xml:"cpfCNPJContratado"`
	CnpjPrestador string   `xml:"cnpjPrestador"`
	CpfContratado string   `xml:"cpfContratado"`
}

// DadosPagamento ...
type DadosPagamento struct {
	XMLName       xml.Name `xml:"dadosPagamento"`
	DataPagamento string   `xml:"dataPagamento"`
	Banco         string   `xml:"banco"`
	Agencia       string   `xml:"agencia"`
	Conta         string   `xml:"conta"`
}

// DadosPagamentoGuia ...
type DadosPagamentoGuia struct {
	XMLName                  xml.Name          `xml:"dadosPagamentoGuia"`
	NumeroGuiaPrestador      string            `xml:"numeroGuiaPrestador"`
	NumeroGuiaOperadora      string            `xml:"numeroGuiaOperadora"`
	Recurso                  string            `xml:"recurso"`
	NomeExecutante           string            `xml:"nomeExecutante"`
	CarteiraBeneficiario     string            `xml:"carteiraBeneficiario"`
	DadosPagamento           []*DadosPagamento `xml:"dadosPagamento"`
	ObservacaoGuia           string            `xml:"observacaoGuia"`
	ValorTotalInformadoGuia  float64           `xml:"valorTotalInformadoGuia"`
	ValorTotalProcessadoGuia float64           `xml:"valorTotalProcessadoGuia"`
	ValorTotalGlosaGuia      float64           `xml:"valorTotalGlosaGuia"`
	ValorTotalFranquiaGuia   float64           `xml:"valorTotalFranquiaGuia"`
	ValorTotalLiberadoGuia   float64           `xml:"valorTotalLiberadoGuia"`
}

// TotaisPorProtocolo ...
type TotaisPorProtocolo struct {
	XMLName                          xml.Name `xml:"totaisPorProtocolo"`
	ValorTotalInformadoPorProtocolo  float64  `xml:"valorTotalInformadoPorProtocolo"`
	ValorTotalProcessadoPorProtocolo float64  `xml:"valorTotalProcessadoPorProtocolo"`
	ValorTotalGlosaPorProtocolo      float64  `xml:"valorTotalGlosaPorProtocolo"`
	ValorTotalFranquiaPorProtocolo   float64  `xml:"valorTotalFranquiaPorProtocolo"`
	ValorTotalLiberadoPorProtocolo   float64  `xml:"valorTotalLiberadoPorProtocolo"`
}

// Protocolos ...
type Protocolos struct {
	XMLName            xml.Name              `xml:"protocolos"`
	NumeroLote         string                `xml:"numeroLote"`
	NumeroProtocolo    string                `xml:"numeroProtocolo"`
	DadosPagamentoGuia []*DadosPagamentoGuia `xml:"dadosPagamentoGuia"`
	TotaisPorProtocolo *TotaisPorProtocolo   `xml:"totaisPorProtocolo"`
}

// TotaisPorData ...
type TotaisPorData struct {
	XMLName                     xml.Name `xml:"totaisPorData"`
	ValorBrutonformadoPorData   float64  `xml:"valorBrutonformadoPorData"`
	ValorBrutoProcessadoPorData float64  `xml:"valorBrutoProcessadoPorData"`
	ValorBrutoGlosaPorData      float64  `xml:"valorBrutoGlosaPorData"`
	ValorBrutoFranquiaPorData   float64  `xml:"valorBrutoFranquiaPorData"`
	ValorBrutoLiberadoPorData   float64  `xml:"valorBrutoLiberadoPorData"`
}

// DebCredPorDataPagamento ...
type DebCredPorDataPagamento struct {
	XMLName   xml.Name       `xml:"debCredPorDataPagamento"`
	Descontos []*Ctdescontos `xml:"descontos"`
}

// TotalLiquidoPorData ...
type TotalLiquidoPorData struct {
	XMLName                   xml.Name `xml:"totalLiquidoPorData"`
	ValorTotalDebitosPorData  float64  `xml:"valorTotalDebitosPorData"`
	ValorTotalCreditosPorData float64  `xml:"valorTotalCreditosPorData"`
	ValorFinalAReceberPorData float64  `xml:"valorFinalAReceberPorData"`
}

// DadosPagamentoPorData ...
type DadosPagamentoPorData struct {
	XMLName                 xml.Name                 `xml:"dadosPagamentoPorData"`
	DadosPagamento          *DadosPagamento          `xml:"dadosPagamento"`
	Protocolos              []*Protocolos            `xml:"protocolos"`
	TotaisPorData           *TotaisPorData           `xml:"totaisPorData"`
	DebCredPorDataPagamento *DebCredPorDataPagamento `xml:"debCredPorDataPagamento"`
	TotalLiquidoPorData     *TotalLiquidoPorData     `xml:"totalLiquidoPorData"`
}

// TotaisBrutoDemonstrativo ...
type TotaisBrutoDemonstrativo struct {
	XMLName                            xml.Name `xml:"totaisBrutoDemonstrativo"`
	ValorInformadoPorDemonstrativoData float64  `xml:"valorInformadoPorDemonstrativoData"`
	ValorlProcessadoPorDemonstrativo   float64  `xml:"valorlProcessadoPorDemonstrativo"`
	ValorlGlosaPorDemonstrativo        float64  `xml:"valorlGlosaPorDemonstrativo"`
	ValoFranquiaPorDemonstrativo       float64  `xml:"valoFranquiaPorDemonstrativo"`
	ValorLiberadoPorDemonstrativo      float64  `xml:"valorLiberadoPorDemonstrativo"`
}

// DebCredDemonstrativo ...
type DebCredDemonstrativo struct {
	XMLName   xml.Name       `xml:"debCredDemonstrativo"`
	Descontos []*Ctdescontos `xml:"descontos"`
}

// CtodemonstrativoOdontologia ...
type CtodemonstrativoOdontologia struct {
	XMLName                      xml.Name                      `xml:"cto_demonstrativoOdontologia"`
	CabecalhoDemonstrativoOdonto *CabecalhoDemonstrativoOdonto `xml:"cabecalhoDemonstrativoOdonto"`
	DadosPrestador               *DadosPrestador               `xml:"dadosPrestador"`
	DadosPagamentoPorData        []*DadosPagamentoPorData      `xml:"dadosPagamentoPorData"`
	TotaisBrutoDemonstrativo     *TotaisBrutoDemonstrativo     `xml:"totaisBrutoDemonstrativo"`
	DebCredDemonstrativo         *DebCredDemonstrativo         `xml:"debCredDemonstrativo"`
	TotalDebitosDemonstativo     float64                       `xml:"totalDebitosDemonstativo"`
	TotalCreditosDemonstrativo   float64                       `xml:"totalCreditosDemonstrativo"`
	ValorRecebidoDemonstrativo   float64                       `xml:"valorRecebidoDemonstrativo"`
	Observacao                   string                        `xml:"observacao"`
}

// DadosProfissionaisResponsaveis ...
type DadosProfissionaisResponsaveis struct {
	XMLName        xml.Name `xml:"dadosProfissionaisResponsaveis"`
	NomeProfSolic  string   `xml:"nomeProfSolic"`
	CroSolic       string   `xml:"croSolic"`
	UfSolic        string   `xml:"ufSolic"`
	CbosSolic      string   `xml:"cbosSolic"`
	CodigoProfExec string   `xml:"codigoProfExec"`
	CroExec        string   `xml:"croExec"`
	UfExec         string   `xml:"ufExec"`
	CnesExec       string   `xml:"cnesExec"`
	NomeProfExec2  string   `xml:"nomeProfExec2"`
	CroExec2       string   `xml:"croExec2"`
	UfExec2        string   `xml:"ufExec2"`
	CbosExec2      string   `xml:"cbosExec2"`
}

// CtoguiaOdontologia ...
type CtoguiaOdontologia struct {
	XMLName                        xml.Name                        `xml:"cto_guiaOdontologia"`
	RegistroANS                    string                          `xml:"registroANS"`
	NumeroGuiaPrestador            string                          `xml:"numeroGuiaPrestador"`
	NumeroGuiaPrincipal            string                          `xml:"numeroGuiaPrincipal"`
	DataAutorizacao                string                          `xml:"dataAutorizacao"`
	SenhaAutorizacao               string                          `xml:"senhaAutorizacao"`
	ValidadeSenha                  string                          `xml:"validadeSenha"`
	NumeroGuiaOperadora            string                          `xml:"numeroGuiaOperadora"`
	AusenciaCodValidacao           string                          `xml:"ausenciaCodValidacao"`
	CodValidacao                   string                          `xml:"codValidacao"`
	DadosBeneficiario              *CtbeneficiarioDados            `xml:"dadosBeneficiario"`
	PlanoBeneficiario              string                          `xml:"planoBeneficiario"`
	NomeEmpresa                    string                          `xml:"nomeEmpresa"`
	DadosProfissionaisResponsaveis *DadosProfissionaisResponsaveis `xml:"dadosProfissionaisResponsaveis"`
	ProcedimentosExecutados        []*ProcedimentosExecutados      `xml:"procedimentosExecutados"`
	DataTerminoTrat                string                          `xml:"dataTerminoTrat"`
	TipoAtendimento                string                          `xml:"tipoAtendimento"`
	TipoFaturamento                string                          `xml:"tipoFaturamento"`
	QtdTotalUS                     float64                         `xml:"qtdTotalUS"`
	ValorTotalProc                 float64                         `xml:"valorTotalProc"`
	ValorTotalFranquia             float64                         `xml:"valorTotalFranquia"`
	Observacao                     string                          `xml:"observacao"`
	OdontoInicial                  *CtoanexoSituacaoInicialnaGTO   `xml:"odontoInicial"`
	AssinaturaDigitalGuia          *Signature                      `xml:"assinaturaDigitalGuia"`
}

// CtoodontoSolicitacaoGuia ...
type CtoodontoSolicitacaoGuia struct {
	XMLName                        xml.Name                        `xml:"cto_odontoSolicitacaoGuia"`
	RegistroANS                    string                          `xml:"registroANS"`
	NumeroGuiaPrestador            string                          `xml:"numeroGuiaPrestador"`
	NumeroGuiaPrincipal            string                          `xml:"numeroGuiaPrincipal"`
	AusenciaCodValidacao           string                          `xml:"ausenciaCodValidacao"`
	CodValidacao                   string                          `xml:"codValidacao"`
	NumeroCarteira                 string                          `xml:"numeroCarteira"`
	AtendimentoRN                  string                          `xml:"atendimentoRN"`
	TipoIdent                      *Sttexto2                       `xml:"tipoIdent"`
	IdentificadorBeneficiario      string                          `xml:"identificadorBeneficiario"`
	PlanoBeneficiario              string                          `xml:"planoBeneficiario"`
	NomeEmpresa                    string                          `xml:"nomeEmpresa"`
	DadosProfissionaisResponsaveis *DadosProfissionaisResponsaveis `xml:"dadosProfissionaisResponsaveis"`
	ProcedimentosSolicitados       []*ProcedimentosSolicitados     `xml:"procedimentosSolicitados"`
	DataTerminoTrat                string                          `xml:"dataTerminoTrat"`
	TipoAtendimento                string                          `xml:"tipoAtendimento"`
	QtdTotalUS                     float64                         `xml:"qtdTotalUS"`
	ValorTotalProc                 float64                         `xml:"valorTotalProc"`
	ValorTotalFranquia             float64                         `xml:"valorTotalFranquia"`
	Observacao                     string                          `xml:"observacao"`
	OdontoInicial                  *CtoanexoSituacaoInicial        `xml:"odontoInicial"`
}

// RecursoProcedimento ...
type RecursoProcedimento struct {
	XMLName           xml.Name             `xml:"recursoProcedimento"`
	SequencialItem    int                  `xml:"sequencialItem"`
	DataRealizacao    string               `xml:"dataRealizacao"`
	DenteRegiao       *DenteRegiao         `xml:"denteRegiao"`
	DenteFace         string               `xml:"denteFace"`
	Quantidade        int                  `xml:"quantidade"`
	ProcRecurso       *CtprocedimentoDados `xml:"procRecurso"`
	CodGlosaProc      string               `xml:"codGlosaProc"`
	JustificativaProc string               `xml:"justificativaProc"`
	ValorRecursado    float64              `xml:"valorRecursado"`
}

// CtorecursoGlosaOdonto ...
type CtorecursoGlosaOdonto struct {
	XMLName                     xml.Name           `xml:"cto_recursoGlosaOdonto"`
	RegistroANS                 string             `xml:"registroANS"`
	NumeroGuiaRecGlosaPrestador string             `xml:"numeroGuiaRecGlosaPrestador"`
	NomeOperadora               string             `xml:"nomeOperadora"`
	ObjetoRecurso               string             `xml:"objetoRecurso"`
	NumeroGuiaRecGlosaOperadora string             `xml:"numeroGuiaRecGlosaOperadora"`
	DadosContratado             *CtcontratadoDados `xml:"dadosContratado"`
	NumeroLote                  string             `xml:"numeroLote"`
	NumeroProtocolo             int                `xml:"numeroProtocolo"`
	OpcaoRecurso                *OpcaoRecurso      `xml:"opcaoRecurso"`
	ValorTotalRecursado         float64            `xml:"valorTotalRecursado"`
	DataRecurso                 string             `xml:"dataRecurso"`
}
